### ISSUE TITLE
Cannot assert that object has no keys without reverting to object.keys().length

### ISSUE THREAD

**Issue by alasdairhurst** [chaijs/chai#1001]
It would be nice to be able to assert that an object has no keys without doing this:
```
expect(Object.keys({}).to.have.length(0);
```
when i can do any of these:
```
expect({foo: 'bar'}).to.have.all.keys('foo');
expect({foo: 'bar'}).to.have.all.keys(['foo']);
```

I would expect that i would be able to do one or more of the following to determine no keys in a consistent way:
```
expect({}).to.have.all.keys([]);
expect({}).to.have.no.keys();
```

**Comment by keithamus** [comment]
Hey @alasdairhurst thanks for the issue.

The good news is we already have an assertion for that! Take a look at http://chaijs.com/api/bdd/#method_empty which should do what you're after. Example:

```js
expect({}).to.be.empty.and.an('object')
expect([]).to.be.empty.and.an('array')
expect('').to.be.empty.and.a('string')
```

I'll close this issue, as I believe this should solve your issue. Feel free to continue the discussion though, we can always re-open the issue!
