### ISSUE TITLE
expect(array).to.have.ordered.members fails when array contains NaN

### ISSUE THREAD

**Issue by solmsted** [chaijs/chai#1003]
I received this assertion error:
```
      AssertionError: expected [ 'a', 'b', 'c', null, NaN, undefined ] to have the same ordered members as [ 'a', 'b', 'c', null, NaN, undefined ]
      + expected - actual
```
The array is obviously in the expected order.  I assume this fails because NaN does not equal itself.

**Comment by keithamus** [comment]
Hey @solmsted thanks for the issue.

Yes, we use [`indexOf`](https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L2900) on `members` checks which uses Strict Equality (`===`) and not `SameValue`/`SameValueZero` (like `Object.is`). I don't think we'll be changing this anytime soon as it's a breaking change.

`.deep.equal` uses `SameValueZero` so you could use that instead:

```js
expect([ 'a', 'b', 'c', null, NaN, undefined ]).to.deep.equal([ 'a', 'b', 'c', null, NaN, undefined ])
```

**Comment by keithamus** [comment]
I'll close this issue for now. The above solution should work for most folk. People are welcome to continue the discussion, and we can re-open at a later date if it warrants it.
