### ISSUE TITLE
Broken tests with more recent node 6.11.0

### ISSUE THREAD

**Issue by SnarkBoojum** [chaijs/chai#1006]
Hi,

I was investigating whether uploading node 6.11.0 would give problems in Debian, and chai was one of the broken packages ; the reason is that in quite a few places in test/should.js, the new error messages are too precise, like:
     "blah: expected 2 to satisfy [Function: matcher]"
instead of:
    "blah: expected 2 to satisfy [Function]"

Perhaps those tests could be made to pass by detecting "[Function*]"?

**Comment by keithamus** [comment]
Good catch, thanks for this @SnarkBoojum.

We would welcome a PR to fix these tests!

**Comment by SnarkBoojum** [comment]
Well, I'm already investigating a dozen of packages (and reporting if needs be), so I'm not sure I'll be able to work on one of them just yet :-/

**Comment by keithamus** [comment]
Not to worry - anyone an pick this up, if you have time to do so, it'd be much appreciated!

**Comment by SnarkBoojum** [comment]
Well, I tried:
    sed -i should.js -e "s/\[Function\]/[Function*]/g"
but it didn't work : are the expectations textual and not regex?

**Comment by keithamus** [comment]
Hmm, it looks like we actually check for `matcher`. Here's those assertions:

https://github.com/chaijs/chai/blob/3397ddaebfe372484d0fcd69680ae66fece4addb/test/expect.js#L2889-L2896

What version of chai are you using?

**Comment by SnarkBoojum** [comment]
Ah, Debian has 3.5.0 which isn't the latest, but I had a look at the current tree and it still has [Function] everywhere. Notice that your link is to test/expect.js while the problems are in node/should.js.

**Comment by keithamus** [comment]
Okay, the same is true of `should.js` tests: https://github.com/chaijs/chai/blob/3397ddaebfe372484d0fcd69680ae66fece4addb/test/should.js#L2474-L2477.

I'll close this. We've fixed this in 4.0 - and 3.5.0 is no longer supported (we do not have the bandwidth to support any but the latest version).
