### ISSUE TITLE
Assert.isNotEmpty is not a function error.

### ISSUE THREAD

**Issue by JpOnline** [chaijs/chai#1018]
I'm new using Chai, this is why I'm guiding mostly by the documentation and when I tried to use the `assert.isNotEmpty(target)` method i got a `is not a function` error. I used it as it was described [in the doc](http://chaijs.com/api/assert/#method_isnotempty), and after a while I found the syntax `assert.notEmpty` what I see it's an alias. I didn't understand very well the concept of the alias, but it should at least be in the documentation.

**Comment by meeber** [comment]
Gonna go ahead and close this one. Please feel free to reopen with a reproducible example.

**Comment by bora89** [comment]
I reproduced it in chai version 3.5.0
