### ISSUE TITLE
Suggestion: Move Support Channel to Gitter

### ISSUE THREAD

**Issue by shellscape** [chaijs/chai#1038]
As the title suggests; http://gitter.im is a much friendlier support and discussion vector these days than IRC, which the website lists as one of two preferred methods. Mocha, and most other large OSS projects, have Gitter channels and they're rather successful in providing help to users. Oddly enough, chai even has it's own channel here: https://gitter.im/chaijs/chai.

I'm posting here for discussion, rather than the chai-docs repo, as there's no support vectors listed on the README for this repo, something which I think would be very helpful to users.

**Comment by keithamus** [comment]
Hey @shellscape thanks for the issue.

We already have gitter and slack channels. Feel free to join both or either. The links are in the README.

I'll close this as I think we've done everything we can here.

**Comment by shellscape** [comment]
@keithamus you're making me 🍌 here bud

The only place "gitter" appears on the readme is within an SVG, which isn't searchable on the page, and which is buried in a litany of other badges and imagery at the top:

![Imgur](https://i.imgur.com/0ZRpCPY.png)

Additionally, the root page of the domain does not list gitter as can be seen here:

![Imgur](https://i.imgur.com/PJrHPuP.png)

Adding a support section to the readme and updating the site are two things that could be done.

**Comment by patcon** [comment]
I recommend bridging slack and gitter with github.com/42wim/matterbridge

**Comment by shellscape** [comment]
@patcon I gave up on this project and the community a long time ago. responsive is something they are not.

**Comment by patcon** [comment]
Drats! That's a bummer that you had that experience :(

But maybe things have changed or gotten better! But if responsiveness is still hard for them to maintain, then I feel that a bridge might help with that :) I imagine having chat is multiple spaces is a drain on attention resources, and a bridge might help corral that, and direct the new undivided attention into other places :)

**Comment by keithamus** [comment]
If anyone wants to tackle the messaging on the website, sending a PR to https://github.com/chaijs/chaijs.github.io is very welcome, I'll look into the bridge, thanks for pointing it out @patcon 😃

**Comment by patcon** [comment]
Sounds good. will do after I get ruby up and running on my new system
