### ISSUE TITLE
Issues with deep include and partial matches in associative array

### ISSUE THREAD

**Issue by am11** [chaijs/chai#1051]
I am trying to figure out the best way to use `.deep` and `.include`. According to https://github.com/chaijs/chai/issues/1009#issuecomment-318855321, it seems like latest version of chai.js should work with partial matches.

Here is a similar sample to what I am trying to achieve https://jsfiddle.net/whm06h05/ (setup with latest versions of chai and mocha as of today):

```javascript
'use strict';

mocha.setup("bdd");
chai.should();

describe('Include tests', () => {
  const array = [];
  array.push({a: 11.1, b: 'blah'});
  array.push({a: 12.1});

  it('should work with deep and exact object graph', () =>
    array.should.deep.include({a: 12.1})); // works
  
  it('should work without deep and exact object graph', () =>
    array.should.include({a: 12.1}));      // doesn't work
  
  it('should work with deep and partial object graph', () =>
    array.should.deep.include({a: 11.1})); // doesn't work
  
  it('should work without deep and partial object graph', () =>
    array.should.include({a: 11.1}));      // doesn't work
});

mocha.run();
```

With the latest version of chai, is there a way to test partial match; certain member of object in an array matches a value?

**Comment by keithamus** [comment]
Hey @am11 thanks for the issue.

At current there is no way to do partial matching. `deep` should check all properties exhaustively, and so what you're hoping for with that code is not yet implemented. You should subscribe to #644 which is our tracking issue for implementing some kind of partial match.

I'll close this issue, as we should keep #644 as the main tracking issue for this feature.
