### ISSUE TITLE
should always reports success when called on window

### ISSUE THREAD

**Issue by dhilgarth** [chaijs/chai#1053]
The following code does not result in a failing test:

    window.should.deep.equal("foo");
    window.should.eql("foo");

**Comment by vieiralucas** [comment]
Hello @dhilgarth, thank you for the issue
I tried to reproduce it with the following code:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
</head>
<body>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/chai/4.1.2/chai.js"></script>
  <script>
    chai.should()
    window.should.deep.equal('foo')
  </script>
</body>
</html>
```
When I open this file in a browser and look at the console I see that an `AssertionError` was threw
![image](https://user-images.githubusercontent.com/7764293/30649634-2d08a2d6-9df7-11e7-937f-18a94d714f25.png)

**Comment by dhilgarth** [comment]
I am using karma with jasmine, chai and typescript... Looks like its a problem with that combination then. I will try and see if I can create a "repro repo"

**Comment by dhilgarth** [comment]
I have been unable to repro it.
