### ISSUE TITLE
new feature request: to.be.a("funciton")`

### ISSUE THREAD

**Issue by zzzgit** [chaijs/chai#1064]
`expect(function(){}).to.be.a("funciton")`
how about add this feature to the basic API?

**Comment by keithamus** [comment]
Hey @zzzgit thanks for the issue.

Do you literally mean `funciton` or do you have a unintentional typo there? `function` should work just fine.

**Comment by meeber** [comment]
Gonna go ahead and close this issue. Seems to have been related to a typo.
