### ISSUE TITLE
How does Chai-HTTP integrate with Sinon in this situation?

### ISSUE THREAD

**Issue by MinhLu12** [chaijs/chai#1067]
Here is the route I want to test:
```
app.post('/api/user', (req, res) => {

        dbService.replaceUserOnDuplicate(req.body, function returnResponse(insertedId) {
            if (insertedId === 0 || insertedId === req.body.id) {
                return res.sendStatus(200);                            
            }
            // TODO_MINH: Send an appropriate error to handle by the front-end
            return res.send({});
        });
    });
```
I can use chai-http to do something like this (psuedo-code):
```
it('test', function (done) {
            chai.request(server)
                .post('/api/user')
                .send({ user: SomeUserObject })
                .end(function (err, res) {
                    res.should.have.status(200);
                    done();
                });

        });
```
However, the api/users route makes a Database call. How would I use sinon to stub this method (replaceUserOnDuplicate) so that it returns a dummy response (like 0, or anything)?

Is it possible? I'm looking at the Chai-HTTP syntax and I see no room to insert any Sinon stubbed methods.

Thanks for your help!

**Comment by brutalcrozt** [comment]
Thanks for your issue, But chai-http is a chai plugin, and this is core repo for chai. When you open chai-http [page](http://chaijs.com/plugins/chai-http/) on chai website, you will see 
>  View the Project on GitHub chaijs/chai-http

clicking that link will lead you to chai-http repository. 
AFAIK, it's more appropriate to submitting issue on chai-http repo, instead of submitting it here.

**Comment by keithamus** [comment]
Thanks for the issue @MinhLu12 and thanks for the great response @brutalcrozt!

@MinhLu12 The quick answer, is that this is not possible in chai-http as it is an end-to-end plugin, as a possible solution to this: you'd have to make `server` a function that takes a configuration - which could consume some kind of stubbed out databse connection - so a kind of dependency injection thing. I'll close this one for now: as @brutalcrozt says this would be better on the chai-http issue tracker, or even better on [StackOverflow](https://stackoverflow.com/) where you'll find much more success. Good luck!
