### ISSUE TITLE
Comparing JSON objects fails

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [chaijs/chai#1068]
I have two JSON objects that are semantically identical, however chai still says they are different. 

I have tested in two websites to be sure:

 - http://json-diff.com/
 - http://www.jsondiff.com/

Following is the error message, containing both objects:

> AssertionError: expected '{"requestId":"kjdhsabkdhbvashdfv","info":[{"rating":0,"numReviews":0,"id":17,"ref":4089,"city":1,"partnerId":1,"partnerName":"FriendlyRentals.com","photo":"http://images.friendlyrentals.com/FR_imgs/Property_4089/PrImg_4089_1_lg.jpg","coordinates":{"lat":38.7223,"lng":-9.1393},"bedrooms":2,"sleeps":5,"sqm":95,"mfc":150,"amenities":{"pets":true,"wifi":true,"terrace":false,"air":true,"pool":false,"heating":true},"apartmentName":{"br":"Incrível apartamento. No centro da cidade","de":"Umfangreiche Wohnung in Mitte. In Barcelona","en":"Central apartment. Simply charming!","es":"Gran apartamento en buena zona ¡Genial!","it":"Straordinario appartamento con aria condizionata, a Barcellona","fr":"Totalement imposant! Près de toutes les attractions de Barcelone","nl":"Welkom bij Barcelona! Comfortabel appartement"},"sameApartments":[630534,3136848],"ppn":30,"price":90,"cityName":{"en":"Barcelona","it":"Barcellona"}}]}' to have the same json representation as '{"requestId":"kjdhsabkdhbvashdfv","info":[{"id":17,"ref":4089,"coordinates":{"lat":38.7223,"lng":-9.1393},"apartmentName":{"br":"Incrível apartamento. No centro da cidade","de":"Umfangreiche Wohnung in Mitte. In Barcelona","en":"Central apartment. Simply charming!","es":"Gran apartamento en buena zona ¡Genial!","it":"Straordinario appartamento con aria condizionata, a Barcellona","fr":"Totalement imposant! Près de toutes les attractions de Barcelone","nl":"Welkom bij Barcelona! Comfortabel appartement"},"city":1,"cityName":{"en":"Barcelona","it":"Barcellona"},"rating":0,"numReviews":0,"partnerId":1,"partnerName":"FriendlyRentals.com","photo":"http://images.friendlyrentals.com/FR_imgs/Property_4089/PrImg_4089_1_lg.jpg","bedrooms":2,"sleeps":5,"sqm":95,"mfc":150,"amenities":{"pets":true,"wifi":true,"terrace":false,"air":true,"pool":false,"heating":true},"ppn":30,"price":90,"sameApartments":[630534,3136848]}]}'

**Comment by keithamus** [comment]
Hey @Fl4m3Ph03n1x thanks for the issue.

It sounds like your two objects are likely different based on some non-enumerable keys; perhaps `prototype`? Could you please show us the test code that failed for this?

**Comment by Fl4m3Ph03n1x** [comment]
Here is s simplified version of the test, which reproduces the same problem:

```
const chai = require("chai");
const expect = chai.expect;

describe("chai bug", () => {

    it("should be able to compare semantically identicall JSON objects", () => {
        const expected = {
            message_17: {
                name: "apartmentInfo",
                content: JSON.stringify({
                    requestId: "kjdhsabkdhbvashdfv",
                    info: [{
                        id: 17,
                        ref: 4089,
                        coordinates: {
                            lat: 38.7223,
                            lng: -9.1393
                        },
                        apartmentName: {
                            br:"Incr\u00edvel apartamento. No centro da cidade",
                            de:"Umfangreiche Wohnung in Mitte. In Barcelona",
                            en:"Central apartment. Simply charming!",
                            es:"Gran apartamento en buena zona \u00a1Genial!",
                            it:"Straordinario appartamento con aria condizionata, a Barcellona",
                            fr:"Totalement imposant! Pr\u00e8s de toutes les attractions de Barcelone",
                            nl:"Welkom bij Barcelona! Comfortabel appartement",
                        },
                        city: 1,
                        cityName: {
                            en: "Barcelona",
                            it: "Barcellona"
                        },
                        rating: 0,
                        numReviews: 0,
                        partnerId: 1,
                        partnerName: "FriendlyRentals.com",
                        photo: "http://images.friendlyrentals.com/FR_imgs/Property_4089/PrImg_4089_1_lg.jpg",
                        bedrooms: 2,
                        sleeps: 5,
                        sqm: 95,
                        mfc: 150,
                        amenities: {
                            pets: true,
                            wifi: true,
                            terrace: false,
                            air: true,
                            pool: false,
                            heating: true
                        },
                        ppn: 30,
                        price: 90,
                        sameApartments: [ 630534, 3136848 ]
                    }]
                })
            }
        };

        const json =JSON.stringify({
            "requestId":"kjdhsabkdhbvashdfv",
            "info":[
                {
                    "rating":0,
                    "numReviews":0,
                    "id":17,
                    "ref":4089,
                    "city":1,
                    "partnerId":1,
                    "partnerName":"FriendlyRentals.com",
                    "photo":"http://images.friendlyrentals.com/FR_imgs/Property_4089/PrImg_4089_1_lg.jpg",
                    "coordinates":{
                        "lat":38.7223,
                        "lng":-9.1393
                    },
                    "bedrooms":2,
                    "sleeps":5,
                    "sqm":95,
                    "mfc":150,
                    "amenities":{
                        "pets":true,
                        "wifi":true,
                        "terrace":false,
                        "air":true,
                        "pool":false,
                        "heating":true
                    },
                    "apartmentName":{
                        "br":"Incrível apartamento. No centro da cidade",
                        "de":"Umfangreiche Wohnung in Mitte. In Barcelona",
                        "en":"Central apartment. Simply charming!",
                        "es":"Gran apartamento en buena zona ¡Genial!",
                        "it":"Straordinario appartamento con aria condizionata, a Barcellona",
                        "fr":"Totalement imposant! Près de toutes les attractions de Barcelone",
                        "nl":"Welkom bij Barcelona! Comfortabel appartement"
                    },
                    "sameApartments":[
                        630534,
                        3136848
                    ],
                    "ppn":30,
                    "price":90,
                    "cityName":{
                        "en":"Barcelona",
                        "it":"Barcellona"
                    }
                }
            ]
        });

        expect(json).to.eql(expected.message_17.content);
    });
});

```

Chai will still see both objects as different, but the website I mentioned will still see them as the same.

**Comment by keithamus** [comment]
Ahh, you are comparing two strings, because of `JSON.stringify`. However the two objects are in different orders; which matters when you are comparing strings because `JSON.stringify` will append in order. You will either need to sort your objects before you stringify, or `JSON.parse` both outputs (`expect(JSON.parse(json)).to.eql(JSON.parse(expected.message_17.content)`) or you can just not `JSON.stringify` in the first place.

I'll close this issue - as this isn't a bug within chai, our messaging needs to get better - but we have a handful of issues tracking that anyway. Feel free to continue the discussion here and we can re-open this issue later.

**Comment by Fl4m3Ph03n1x** [comment]
I thought that to be the case but wanted to be sure. Couldn't you add a new method to chai that merely checks if 2 JSONs are semantically identical? 

I do have the impression this is what people actually care about when comparing them in the first place. 

Oh well, at least the suggestion gets registered :D

**Comment by keithamus** [comment]
How could we determine that a String is a JSON String, as opposed to any regular String?

**Comment by Fl4m3Ph03n1x** [comment]
There are two ways:

1 - create a new method. You have `equal` and `eql`. You could add `eqlJSON`only for JSONs. 
2 - Try to parse the string. If it fails, you know it is a normal one. Otherwise try to check for JSON equality.

I personally would prefer the first alternative, since it would make clear what you want. However it is up to you!

**Comment by keithamus** [comment]
@Fl4m3Ph03n1x I would recommend - if this is a feature you want - you should make a chai plugin! We have a [guide on writing plugins on the docs site](http://chaijs.com/guide/plugins/) which could get you started; with this you could find the right way to do this and if the plugin becomes popular enough with many requests on the chai issue tracker, we can always adopt the plugin for chai core!

**Comment by Fl4m3Ph03n1x** [comment]
Alright, will give it a look! Thanks !
