### ISSUE TITLE
Expect to throw (number) doesn't seem to work

### ISSUE THREAD

**Issue by SamStonehouse** [chaijs/chai#1070]
const failingCall = function() {
      throw 10;
    };

    expect(failingCall).to.throw(10);

Results in 'AssertionError: expected [Function: failingCall] to throw 10 but 10 was thrown'

    const failingCall = function() {
      throw 'test';
    };

    expect(failingCall).to.throw('test');

Passes as normal

And...

    const failingCall = function() {
      throw 0;
    };

    expect(failingCall).to.throw(0);

Fails with 'AssertionError: expected [Function: failingCall] to throw an error'

**Comment by keithamus** [comment]
Hey @SamStonehouse thanks for the issue.

This seems to be a problem with our type checking for that assertion. We should throw a better error message saying that `throw(instanceof Number)` is not supported. 

PRs welcome 😄

**Comment by bryanbraun** [comment]
I put together a PR for this issue over at https://github.com/chaijs/chai/pull/1071. Let me know if you have any feedback.

**Comment by keithamus** [comment]
Hey @SamStonehouse thanks for the issue.

We've added this to our Roadmap https://github.com/chaijs/chai/projects/2! We'll be releasing chai 5 soon, but for now I'll close this issue because it is tracked on our roadmap.
