### ISSUE TITLE
All AppVeyor builds are failing

### ISSUE THREAD

**Issue by meeber** [chaijs/chai#1075]
Don't have time at the moment to dig in, just creating an issue to track this, since it means all of our builds and PRs are failing CI:

> Build started
> git clone -q https://github.com/chaijs/chai.git C:\projects\chai
> git fetch -q origin +refs/pull/1074/merge:
> git checkout -qf FETCH_HEAD
> The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.

**Comment by keithamus** [comment]
They can be ignored for now; we have no appveyor yml file in this repo, it was accidentally enabled as part of https://github.com/chaijs/type-detect/pull/108 - once that PR is reviewed and merged I'll move onto other repos like chaijs/chai
