### ISSUE TITLE
Improvement build sequence (codecov)

### ISSUE THREAD

**Issue by brutalcrozt** [chaijs/chai#1077]
Well i am too excited to contribute to chai, so previous work #1073 seems have better way.
It's just 300kb , but in my point of view it save developers time to install it and save small disk space :smile: .
![image](https://user-images.githubusercontent.com/3001652/32355687-cb9be8b2-c062-11e7-8c24-93fa386277a6.png)
The better way is via [bash](https://docs.codecov.io/docs/about-the-codecov-bash-uploader#section-via-flag).

**Comment by keithamus** [comment]
Closing because:

> I feel _really_ uncomfortable downloading and executing aribtrary bash on my local machine, and on CI (where we have secret tokens like account passwords). The 300k is only downloaded for developers, so I think it's adequete to keep it. I'll close this issue, you did the right thing in the original PR, and changing to running arbitrary bash would be a bad move IMO.
