### ISSUE TITLE
Deep equal with sorted keys in an object.

### ISSUE THREAD

**Issue by pratishshr** [chaijs/chai#1080]
Is there a way to perform a deep equal to check if the keys are in a defined order?
example: 
```js
let a = {
   a: 1,
   b: {
     a: {
        a: 1,
        b: 1
      }
    }
};

let b = {
  b: {
    a: {
      b: 1
      a: 1,
    }
  },
  a: 1
};
```
Here a is equal to b as they have the same properties.
But since they are not in the given order, i would like for the test to fail.

**Comment by meeber** [comment]
@pratishshr I don't think there's currently a way to do that with a single assertion. If you only care about the ordering of the parent object's properties, you could do something like this:

```js
expect(a).to.deep.equal(b);
expect(Object.keys(a)).to.deep.equal(Object.keys(b));
```

**Comment by samarth** [comment]
@pratishshr

Is there a need to rely on the order of the keys in a JSON object? 
Are you trying to model an ordered dict behaviour here?

**Comment by pratishshr** [comment]
@samarth Yes I was writing a utility to sort the object keys in a given order.

**Comment by pratishshr** [comment]
I ended up writing this function to concatenate the keys and testing the array instead.

```js
/**
 * Traverse object to get the concatenated keys.
 * 
 * @example
 * getDeepKeys({a: {a: 1}, b: 2}) => ['a.a', 'b']
 * 
 * @param {Object} obj 
 */
function getDeepKeys(obj) {
  let keys = [];

  for (let [key, value] of Object.entries(obj)) {
    keys.push(key);

    if (isObject(value)) {
      let subkeys = getDeepKeys(obj[key]);
      keys = keys.concat(subkeys.map(subkey => key + '.' + subkey));
    }
  }

  return keys;
}
```

```
expect(getDeepKeys(input)).to.have.ordered.members(getDeepKeys(sortedOutput));
```

**Comment by ancmikesmullin** [comment]
javascript objects are NOT ordered! https://stackoverflow.com/a/9179997
if you put the key-value pairs in an array like tuples then you can use the ordered array functionality that already exists.

**Comment by keithamus** [comment]
@ancmikesmullin unfortunately this is no longer true. The ES6 and above specifies [keys are ordered by creation order](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-ordinary-object-internal-methods-and-internal-slots-ownpropertykeys).

**Comment by pratishshr** [comment]
@keithamus nice 👍 
So, will `chai` support testing for sorted keys in any of its future releases?

**Comment by lucasfcosta** [comment]
I was thinking about this earlier today and I agree about adding an assertion for it given the reasonable amount of code people would have to write in order to do that kind of test.

I'm just concerned about making the API look good and reusable. 

Do you have any suggestions on what it should look like?

I was thinking about something like:

```js
// This would test against an array or an object
expect(myObject).to.have.deep.ordered.keys(orderedKeysArrOrObj)
```

**Comment by keithamus** [comment]
I think `ordered.keys` sounds like a fantastic assertion to add!

**Comment by keithamus** [comment]
Hey @pratishshr thanks for the issue.

We've added this to our Roadmap https://github.com/chaijs/chai/projects/2! We'll be releasing chai 5 soon, but for now I'll close this issue because it is tracked on our roadmap.
