### ISSUE TITLE
Chai Stickers!

### ISSUE THREAD

**Issue by keithamus** [chaijs/chai#1082]
Hey everyone!

I just put an order in for some chai stickers, using the opencollective funds! 🎉 

![image](https://user-images.githubusercontent.com/118266/32579120-ac03d7f2-c4d7-11e7-9108-63c1dbb54ec2.png)

We've got 500 stickers coming, and to reward all of our fantastic maintainers, contributors, and backers I'll be posting them to anyone who wants to fill out this form: https://docs.google.com/forms/d/e/1FAIpQLSf70caSkPj3RRvf4oBrnUmx8r4h0zMy3E0GY9cIj_i6yzGpUw/viewform. If you fill out the form, which includes your github username, full name, and address you'll get 1 or more stickers posted to you based on your role in the community!

 - @chaijs/core members can fill out the form to receive 50 free stickers
 - Other chaijs contributors can fill out the form to receive 10 free stickers
 - Backers on opencollective (@chaijs/opencollective-backers) can fill out the form to receive 10 free stickers
 - If you've ever filed an issue before - then fill out the form and we'll send you 1 free sticker if we have any left!

#### Why do you need my home address?

We need a place to send the stickers! If you dont want to send your address, feel free to reach out to me and we can find another way send you some stickers!

#### Who gets to see my address?

I (@keithamus) will be the only person to see your details, such as your address.

#### What happens to my details after this?

Once we've sent all the stickers, the google form will be deleted and no record of your addresses will be maintained.

#### I'm not a backer, or contributor, but I want free stickers!

We always have issues that need working on! Why not check out the issue tracker, or alternatively head on over to http://opencollective.com/chaijs and become a backer today!

**Comment by brutalcrozt** [comment]
Yay stickers, i wonder how it looks like.

**Comment by keithamus** [comment]
Good point @brutalcrozt! I've added the proof image in the original comment!

**Comment by lucasfcosta** [comment]
I'll make sure to get a few with you in London in a few weeks 😄 

I can't wait to get all the visa stuff done and finally settle so that I can write some code with you again.

They look great btw!

**Comment by keithamus** [comment]
I think everyone who wanted stickers has them. ☮️ y'all!

**Comment by keithamus** [comment]
That sucks @brutalcrozt. I definitely sent some over but it was too expensive to send tracked so maybe they just got lost in transit? I can send some more over if you'd like? I deleted all of the address data we gathered though, so you'd need to resend your address over to me (can email me at chai at keithcirkel dot co dot uk)
