### ISSUE TITLE
is utils.expectTypes still used?

### ISSUE THREAD

**Issue by brutalcrozt** [chaijs/chai#1083]
I notice that expectTypes only have [23%](https://codecov.io/gh/chaijs/chai/src/master/lib/chai/utils/expectTypes.js) test coverage. Attempt to increase coverage on that file, it lead me to see the internal use of that utility function. With quick seach (ctrl + f per file), i only found on [core/assertions](https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L530) which comment-ed that indicate it not used. I can't found the usage on interface. I try to dropping the file then re-run the test, nothing seems affected so far. 

Dropping the file theoretically increase the coverage, leaving as is give no benefit.
I am open to the others opinion, let me know if i miss something or do i wrong.

Please assign me if **we** intended to do so (drop the file), i am happy to do that

**Comment by meeber** [comment]
I'm using it in #1021 :D

**Comment by keithamus** [comment]
Thanks @brutalcrozt for this! Awesome research here - it's much appreciated!

We'll be refactoring a bunch of chai very soon. Everything inside util should disappear or become its own library. We'll be sure to check small functions like `expectTypes` to make sure they are used or not.

There's nothing specifically actionable here, so we're going to close this issue now. But we'll be sure to fix this for chai 5!
