### ISSUE TITLE
Increase assert interface coverage

### ISSUE THREAD

**Issue by brutalcrozt** [chaijs/chai#1084]
List of targets:
- [changes with getter function without message](https://codecov.io/gh/chaijs/chai/src/6e9bfc1329f79fa25c7c60fc801a405e5c2ca077/lib/chai/interface/assert.js#L2497...2498) ok
- [changesBy with getter function without message](https://codecov.io/gh/chaijs/chai/src/6e9bfc1329f79fa25c7c60fc801a405e5c2ca077/lib/chai/interface/assert.js#L2525...2527) 
fail with expecting getter function to have `.value`
- [doesNotChange with getter function without message](https://codecov.io/gh/chaijs/chai/src/6e9bfc1329f79fa25c7c60fc801a405e5c2ca077/lib/chai/interface/assert.js#L2557...2558) ok
- [changesButNotBy with getter function without message](https://codecov.io/gh/chaijs/chai/src/6e9bfc1329f79fa25c7c60fc801a405e5c2ca077/lib/chai/interface/assert.js#L2586...2588)
fail with expecting getter function to have `.value`
- increases and decreases with getter function without message notOk
  > decreasesBy fail with expecting getter function to have `.value`

  > decreasesButNotBy fail with expecting getter function to have `.value`

  > so do with the increasesBy and increasesButNotBy

I seems that i need some help with explaining or pointing why it expecting getter function to have specific property.

**Comment by keithamus** [comment]
Hey @brutalcrozt thanks for this issue.

We're going to work a bunch on chai soon. We'll be looking at increasing test coverage of all of our assertions. I'll close this for now because there's nothing specifically actionable from this issue!
