### ISSUE TITLE
Can the makefile be converted to npm scripts?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [chaijs/chai#1091]
I'm developing on Windows and it would be inconvenient to set up an Ubuntu VM or install Cygwin to get `make` locally. Is there anything in `Makefile` that can't be converted to a `"scripts"` command within `package.json`?

**Comment by brutalcrozt** [comment]
I also like to hear about this, because i also have trouble when testing chai in browser. In addition who is the original author of the `Makefile` ?

@JoshuaKGoldberg I do have alternative option, [cmder](https://github.com/cmderdev/cmder). Presumably you haven't tried it.

**Comment by JoshuaKGoldberg** [comment]
I **LOVE** cmder! How does it help, though?

**Comment by keithamus** [comment]
Hey @JoshuaKGoldberg thanks for the issue.

We have plans to do this. We're working on getting the tooling right in some of the smaller projects which have more modern codebases (such as  https://github.com/chaijs/type-detect, see for example https://github.com/chaijs/type-detect/pull/108). Once we get it right there we'll be applying it to all projects under the `chaijs` org. That is to say: it'll happen, soon 😄.

**Comment by brutalcrozt** [comment]
I'd like to say sorry about it, it was clearly premature arguments.
I just saw my friend use it, it was my fault(too soon to make a conclusion).

Also GNU Make, stuck on unrecognizing `printf`.

**Comment by keithamus** [comment]
Hey @JoshuaKGoldberg thanks for the issue.

This would be awesome! We've added this to our Roadmap https://github.com/chaijs/chai/projects/2! We'll be releasing chai 5 soon, but for now I'll close this issue because it is tracked on our roadmap.
