### ISSUE TITLE
It's difficult to add chainable methods that work nicely with other chainable method plugins.

### ISSUE THREAD

**Issue by TiraO** [chaijs/chai#1097]
It's difficult to add chainable methods that work nicely with other chainable method plugins. Using `overwriteChainableMethod`  to overwrite 'friendly' plugins feels like a workaround. It means that your plugin has to know about and depend on any plugins that it should work with.

Right now the chaining framework can make behavior hard to understand or control as a plugin developer, which can result in unexpected behavior:
```javascript
describe("when the end of the chain does not include an assertion", function () {
  it('can appear to be both true and false for the same chain', function () {
    expect({ x: 700, y: 100, z: 150 }).to.jsonEqual.roughly({ x: 700, y: 100, z: 150 });
    expect({ x: 700, y: 100, z: 150 }).to.not.jsonEqual.roughly({ x: 700, y: 100, z: 150 });
  });
});

describe("when the first method in the chain includes assertions", function () {
  it('can be accidentally and silently superceded by future assertions', function () {
    expect({ x: 700 }).to.not.jsonEqual.eql({
      toJson: function () {
        return JSON.stringify({ x: 700 })
      }
    });
  });
});

```

I would like to see a clearer contract for chainable methods to communicate with each other. However, it would probably require a large overhaul of the api. Here are some features I might expect:

- allow chainable methods to wrap each other's comparators (instead of overwriting the entire assertion)
- combine assertion messages in a human-readable way
- raise an error when no assertions complete a chain 
- chained methods do not have their own assertions

Obviously this is a complex problem and deserves more thought than I've put into it so far.

**Comment by keithamus** [comment]
Hey @TiraO thanks for the issue! Getting feeback on our plugin system is super important so thankyou!

We have an discussion over in https://github.com/chaijs/chai/issues/585 on how to make plugins much more approachable, and I believe it would solve the issues you're having. I know its a long read but it'd be excellent for you to take a look and provide feedback there.

I'd like the conversation to remain centralised in https://github.com/chaijs/chai/issues/585 so I've quoted you in that issue. I'll close this one.
