### ISSUE TITLE
How to import types properly

### ISSUE THREAD

**Issue by ORESoftware** [chaijs/chai#1099]
I am trying to figure out how to import types properly from `@types/chai`

I do

```bash
npm install -D @types/chai
```

then I have this

```typescript
import * as chai from 'chai';
import AssertStatic = chai.AssertStatic;
```

but I get this message:

![screenshot 2017-12-03 15 54 36](https://user-images.githubusercontent.com/11139560/33531462-47b274a6-d842-11e7-966a-b44c0d5874e9.png)

**Comment by ORESoftware** [comment]
On the other hand, if I install chai itself

```bash
npm install -D chai
```

then do this:

```typescript
import chai = require('chai');
import AssertStatic = Chai.AssertStatic;
```

it seems to work, so is this way correct?

**Comment by lucasfcosta** [comment]
Hi @ORESoftware, thanks for your issue!

I'm not sure I fully understand what you are trying to do. If you want to state a variable is of a certain type contained within Chai's type definitions you could just do:

```ts
let myVar: AssertStatic
```

There's no need to get it from the namespace or assign it to any other variable. Just make sure you have both chai and its type definitions installed.

**Comment by ORESoftware** [comment]
yeah I finally got it working like so:

```js
import * as chai from 'chai';

export interface IHookParam extends IHookOrTestCaseParam {
  (err?: Error): void,
  ctn: Function,
  assert: typeof chai.assert           // <<<< here
}
```

what I am doing is a little out of the ordinary, attaching assert to another object, but it's actually working out nicely, here is what it looks like:

https://github.com/sumanjs/suman/blob/master/lib/test-suite-helpers/t-proto-test.ts#L66

**Comment by lucasfcosta** [comment]
Great!

I'm glad you have been able to get it working. I'll close this then.

PS: Your project looks really interesting, I hope it goes well 😄

**Comment by ORESoftware** [comment]
@lucasfcosta thanks! always can use followers on the suman repo, I am going to email everyone just once when I finally release it
