### ISSUE TITLE
"or" chain

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [chaijs/chai#1108]
I and some others think that an "or" chain would be very helpful.
https://stackoverflow.com/questions/32387293/how-to-do-an-or-in-chai-should

```javascript
total.should.equal(4).or.equal(5)
```

This would also be useful for checking if two equivalent objects are returned that do not have a comparison method defined.

```javascript
const a = new obj()
const b = new obj()

expect(func([a, b])).to.equal(a).or.equal(b)
```

Hopefully you can see the value in this!

**Comment by meeber** [comment]
I have a strong opinion that the use of "or" in testing is a bad practice. I've described my thoughts in more detail [here](https://github.com/chaijs/chai/issues/620#issuecomment-217957971).

**Comment by lucasfcosta** [comment]
Hi @BebeSparkelSparkel, thanks for your issue.

I agree with @meeber as well.

If you want to read more, I've made a blog post about this [here](lucasfcosta.com/2017/01/02/How-to-Write-Assertions-Right.html).

**Comment by BebeSparkelSparkel** [comment]
@meeber @lucasfcosta thanks for the suggestions. I'll look at the links
