### ISSUE TITLE
.lengthOf should work for sets and maps

### ISSUE THREAD

**Issue by rijnhard** [chaijs/chai#1110]
sets and maps use a different property `.size` for their length but in the context of chai it should work the same way.

```javascript
expect(new Set([1])).to.have.lengthOf(1);
// currently UncaughtException AssertionError: expected {} to have property 'length'
```

**Comment by rijnhard** [comment]
workaround is:

```javascript
expect(new Set([1])).to.have.property('size', 1);
```

**Comment by lucasfcosta** [comment]
I think this is a very valid suggestion.

If other maintainers agree, I'd love to get this into our codebase.

Btw, this is very similar to #1096.

**Comment by meeber** [comment]
Agreed. May also be worth adding `.size` as an alias to `.lengthOf`.

**Comment by keithamus** [comment]
PRs welcome for this!

**Comment by sergiorojasa** [comment]
I would like to work on this

**Comment by asbish** [comment]
@keithamus I would like to do it by this weekend. Fine with you?

**Comment by keithamus** [comment]
@asbish that would be more than fine. That would be wonderful!

**Comment by keithamus** [comment]
@asbish I have assigned this to myself, and removed the `pull-request-wanted` label - this is so that you have time to make this PR without any one thinking it is free to work on. However, there is no pressure! If you decide you dont or cant work on it any more please let me know 😄

**Comment by asbish** [comment]
@keithamus Thank you for your kinds words! :)

**Comment by keithamus** [comment]
hey @rijnhard thanks for this issue! 

We're adding this in chai 5, we've added this to our Roadmap https://github.com/chaijs/chai/projects/2! We'll be releasing chai 5 soon, but for now I'll close this issue because it is tracked on our roadmap.
