### ISSUE TITLE
Docs, BDD: include 'a'/'an' in the list of Language Chains

### ISSUE THREAD

**Issue by jeffvandyke** [chaijs/chai#1111]
The documentation by `.a` indicates that it is a valid language chain, so it should be included in the list of Language Chains so that someone (like me) looking for valid chains to use for improving readability would see that `.a` and `.an` are available.

**Comment by keithamus** [comment]
Thanks for this @jeffvandyke! We've added this to our roadmap https://github.com/chaijs/chai/projects/2 and we'll be releasing this with chai 5!
