### ISSUE TITLE
List array values when sameOrderedMembers fails

### ISSUE THREAD

**Issue by aberonni** [chaijs/chai#1123]
I think it would be handy to list the values of arrays when `assert.sameOrderedMembers` fails.

Current:
`AssertionError: expected [ Array(4) ] to have the same ordered members as [ Array(4) ]`

Expected:
`AssertionError: expected [1,2,3,4] to have the same ordered members as [1,2,3,5]`
OR
`AssertionError: expected [ Array(4) ] to have the same ordered members as [ Array(4) ]. Value at index 3 failed equality: expected 4 === 5`

This behavior could be replicated in all of the array "members" assertions.

**Comment by meeber** [comment]
@aberonni Setting [chai.config.truncateThreshold](https://github.com/chaijs/chai/blob/c94f4b64009faf1ae0a57246d6dff46aad3a6e3d/lib/chai/config.js#L33-L53) to a higher value (or `0` to disable) should produce the behavior you're looking for. Also, if you're using a test runner like `mocha`, then I'd expect the diff to be shown below the error message by default. For example, this is the output I get from your example:

> 
>       AssertionError: expected [ 1, 2, 3, 4 ] to have the same ordered members as [ 1, 2, 3, 5 ]
>       + expected - actual
> 
>        [
>          1
>          2
>          3
>       -  4
>       +  5
>        ]
>       
>       at Context.<anonymous> (test/index.js:11:10)

**Comment by aberonni** [comment]
@meeber that is exactly what I was hoping to achieve, I hadn't realise there was that option and I was comparing a very long array :)

Thank you!
