### ISSUE TITLE
Can't import assert/should/expect

### ISSUE THREAD

**Issue by josh-g3** [chaijs/chai#1133]
```js
import { assert, should, expect } from 'chai';
```

This gets the following:

`Cannot resolve symbol 'assert'|'should'|'expect'`

**Comment by meeber** [comment]
@josh-g3 Thanks for the report. This is a known issue. Gonna close it in lieu of https://github.com/chaijs/chai/pull/1061 and https://github.com/josh/selector-observer/pull/4.

**Comment by josh-g3** [comment]
Okay, thanks for the response.
