### ISSUE TITLE
import 'chai/should' does not work

### ISSUE THREAD

**Issue by LAITONEN** [chaijs/chai#1139]
According to the [documentation](http://chaijs.com/guide/styles/#should) in order to use `should()` in our apps, one need to import it using `import 'chai/should'`:  

<img width="722" alt="screen shot 2018-02-25 at 2 07 44 pm" src="https://user-images.githubusercontent.com/23742868/36641265-898d75c6-1a35-11e8-9805-9f5e4303539b.png">

However, when I did that, I got an error:
```
Error: Cannot find module 'chai/should'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
```

The solution was to use `import "chai/register-should"`, but it's not covered in the documentation.

**Comment by keithamus** [comment]
Hey @LAITONEN thanks for the issue.

Yes the documentation is mistaken. It should be `import "chai/register-should"`. The markdown file that drives this documentation can be found here: https://github.com/chaijs/chai-docs/blob/master/_guides/styles.md. If you'd like to submit a pull-request changing the docs then that'd be amazing!

**Comment by meeber** [comment]
Fixed via https://github.com/chaijs/chaijs.github.io/pull/156
