### ISSUE TITLE
How to make ChaiJS 'expect' function available in all files inside NodeJS 'test' folder?

### ISSUE THREAD

**Issue by zulhfreelancer** [chaijs/chai#1140]
I'm using Truffle which has Mocha & Chai included by default.

File tree:

```
├── test
│   ├── ManagedWallet.js
│   ├── AnotherTest.js
│   └── AndAnotherTest.js
└── truffle.js
```

This is one of my test file:

```
var expect = require('chai').expect;
var managedWallet = artifacts.require("./ManagedWallet.sol");

contract('ManagedWallet', function(accounts) {

  it("belongs to customer's account address", async function(){
    var contract         = await managedWallet.deployed();
    var customer_account = accounts[1];
    var owner            = await contract.owner.call();

    expect(owner).to.equal(customer_account);
  });

});
```

Since I have a lot of test files inside the `test` folder, I need to put that `var expect = require('chai').expect;` line in all the test files.

Is there a way for me to make that `expect` function available globally without needing me to have that `var expect = require('chai').expect;` line in all my test files?

I tried putting `var expect = require('chai').expect;` line inside truffle.js file (above `module.exports` line) but it didn't work and I got `ReferenceError: expect is not defined` error when I ran the tests.

Example of my truffle.js file (located in the root folder of the project):

```
module.exports = {

  networks: {
    development: {
      host: "127.0.0.1",
      port: 7545,
      network_id: "*" // match any network
    }
  }

};
```

**Comment by keithamus** [comment]
Hey @zulhfreelancer thanks for the issue.

Take a look at https://github.com/chaijs/chai/blob/master/register-expect.js which adds `expect` to the global object. Use it like this:

```js
require('chai/register-expect');

//... rest of code
expect(...)
```

Hope this is helpful. I'll close this issue for now but if that doesn't solve your issue feel free to let us know and I'll re-open it.

**Comment by zulhfreelancer** [comment]
It works. Thanks @keithamus!
