### ISSUE TITLE
API reference broken (no content)

### ISSUE THREAD

**Issue by mathieu-anderson** [chaijs/chai#1147]
The following URLs return broken pages without any content at the moment : 

http://www.chaijs.com/api/bdd/
http://www.chaijs.com/api/assert/
http://www.chaijs.com/api/plugins/

Browser tested : 
Google Chrome Version 64.0.3282.186 (Official Build) (64-bit)
Firefox Version 58.0.2

[Example of what the assert API reference looks like.](https://i.imgur.com/AJ9PgPK.png)

[With devtools showing markup.](https://i.imgur.com/ojGCY1t.png)

**Comment by keithamus** [comment]
Thanks for this. Looking into it.

**Comment by tzkmx** [comment]
Probably related to this: chaijs/chaijs.github.io/issues/159

**Comment by dholtzmann** [comment]
Here is a Google cache for the moment. https://webcache.googleusercontent.com/search?q=cache:www.chaijs.com/api/

**Comment by keithamus** [comment]
I don't believe it is related to chaijs/chaijs.github.io#159. That is a different issue. It looks like the docs are somehow not being generated from the JSON.

**Comment by 0vidiu** [comment]
Seems to be working now!
