### ISSUE TITLE
When Assert fails chai.config.includeStack = true doesn't work but try-catch does

### ISSUE THREAD

**Issue by ugenlik** [chaijs/chai#1149]
I am testing an API and I have many fields that I test with assert.

However if an assertion fails I don't get any info at all at which line it is failed. It is really frustrating.

All I get is 

**Unhandled promise rejection (rejection id: 1): AssertionError: expected null to not equal null**

my original assert looks like this 
```
var config = require('../config');
var singleton = require('./utilities/Singleton');

var chai = require('chai');  
var assert = chai.assert;    
var expect = chai.expect;    
var should = chai.should();
chai.config.includeStack = true;

var supertest = require('supertest');
var api = supertest(config.base_url);

describe('Firestore', function () {
    before(function (done) {
        if (singleton.getPortalId() == null)
        {
            //"Should login"
            var attemptLogin = require('./utilities/Login');
            attemptLogin.login(function(err, result){
                assert.isTrue(result, 'Login failed');
                done();
            })
        }
        else
        {
            done();
        }
    });

    it('firestore get token request should return a 200 response', function (done) {
        var portal_id = singleton.getPortalId();
        var path = 'portal/'+portal_id+'/firestore/jwt'
        var bearer = singleton.getAccessToken();
        var headers = {"Authorization":bearer};
        
        api.get(path)
        .set(headers)
        .send()
        .expect('Content-Type', 'application/json; charset=utf-8')
        .expect(200)
        .then((res) => {
            //check if firestore token is returned
            expect(res.body).to.be.an('object');
            expect(res.body).to.have.property("token");
            expect(res.body.token).to.not.equal(null);
            done();
          });
    });
```

but then if I change it to try and catch it works. 

```
        .then((res) => {
            //check if firestore token is returned
            try {
                expect(res.body).to.be.an('object');
                expect(res.body).to.have.property("token");
                expect(res.body.token).to.not.equal(null);
                done();
            } catch (e) {
              return done(e);
            }
```

why `chai.config.includeStack = true;` doesn't do anything?

**Comment by meeber** [comment]
@ugenlik This is just how Promises work. Errors thrown inside of a Promise are silently swallowed by the Promise and never reach your test runner to notify it that an assertion failed inside of the Promise. One workaround is the one you demonstrated above, by catching the error before it's swallowed by the Promise, and then passing that error to your test runner via `done`.

Another workaround is to add `.catch(done)` to the end of your Promise chain, which has the same effect with fewer lines of code.

Another workaround is to remove `done` from everywhere (including the argument list of the `it` function), and instead return the Promise to your test runner (e.g., `return api.get(path)`).
