### ISSUE TITLE
Is chaijs suitable for production use?

### ISSUE THREAD

**Issue by tigermarques** [chaijs/chai#1150]
Hi,

This is a question that may be a little outside the primary scope of chaijs. I am currently building an engine whose primary goal is to evaluate conditions and make decisions based on those conditions. Given chaijs friendly interface for assertions, one of the options I am considering is evaluating these conditions using chaijs. However, since the library is built mainly for unit testing, I am concerned that I may run into a performance problem somewhere along the way.

Therefore, I wanted to ask whether you guys consider chaijs to be suitable for running in non development environments, with a goal other than making assertions for unit testing.

Thank you!

**Comment by keithamus** [comment]
Hey @tigermarques thanks for the issue.

We've been asked this before, I can't remember the issue number though. I would say chai is not suitable for server or client side production code: speed and size are currently not big concerns, and it's fairly trivial to get chai to end up taking lots of CPU - especially when trying to inspect recursive items or large buffers. So very likely you will run into performance issues.

I'd recommend following #585 though - as this will enable many future optimisations including: being able to extract out chai's assertion behaviors into things like validation frameworks, as well as easier to manage performance.

I'll close this as it's not a thing we're especially concerned with for now. Thanks for raising the issue though 😄
