### ISSUE TITLE
Question: how to get wrapper value?

### ISSUE THREAD

**Issue by alexey-baranov** [chaijs/chai#1161]
Hello! 

We need to get value from some property or error wrapper. Is it possible?

```js
let err= expect(method).throw(err).someGetWrapperValueMethod()
// do some staff with err
...
```

**Comment by meeber** [comment]
If I understand your question correctly, there are two ways to go about it, although the second one is a bit hacky, and might not be future-proof:

```js
const {expect} = require("chai");

const fn = function () { throw Error("myErr") };

describe("test the error object", function () {
  it("via chaining", function () {
    expect(fn).to.throw().with.property("message", "myErr");
  });
  it("via accessing wrapped object", function () {
    const err = expect(fn).to.throw()._obj;
    expect(err).to.have.property("message", "myErr");
  });
});
```

Alternatively, you could invoke the function in a `try`/`catch`, and catch the error to perform assertions on.

**Comment by lucasfcosta** [comment]
Thanks for your issue @alexey-baranov!

As @meeber has answered that and there hasn’t been any other activity in this issue I’m gonna close this for now.

Please let us know if you need any further help and we might reopen it if we need to.
