### ISSUE TITLE
"Should" syntax malfunctioning when used with Jest.

### ISSUE THREAD

**Issue by phyllisstein** [chaijs/chai#1165]
I recently tried to implement Chai's gorgeous `should` assertions in a repo that was running its tests through [Jest](https://facebook.github.io/jest/), and ran into a little trouble. For reasons that still aren't totally clear to me, a number of tests involving JSDOM objects (individual `HTMLElement`s) and native Node.js objects (notably `URL`) started throwing errors indicating that `should` was undefined at various points in its chain; e.g.:

```
● IFrame › #initialize › is ignored by screen readers

  TypeError: Cannot read property 'have' of undefined

    45 |
    46 |     it('is ignored by screen readers', () => {
  > 47 |       document.body.querySelector('iframe')
       |       ^
    48 |         .should.have.attribute('aria-hidden')
    49 |         .that.equals('true')
    50 |     })

    at Object.it (spec/client/dom/iframe-spec.ts:47:7)
```

```
● ProsceniumClient › initialization › creates a URL object for the server URL

  TypeError: Cannot read property 'be' of undefined

    13 |   describe('initialization', () => {
    14 |     it('creates a URL object for the server URL', () => {
  > 15 |       pc.serverURL.should.be.an.instanceof(URL)
       |                           ^
    16 |     })
    17 |
    18 |     it('creates a new IFrame', () => {

    at Object.it (spec/client/proscenium-client-spec.ts:15:27)
```

Notably, making similar assertions in a Node REPL works, and similar tests run fine with the Mocha runner.

My guess is that Jest's unusually heavy-handed environment management is doing something to screw with the way Chai screws with `Object.prototype`, but I can't for the life of me figure out what it is. I _did_ manage to put together a repo reproducing the issue, though. In case it'd be helpful, you can find it at <https://github.com/phyllisstein/expect-should-repro-repo>.

If you all have any thoughts or insights, I'd be glad to hear them! In the meantime I'll probably just cut over to Mocha while the cutting's good.

**Comment by keithamus** [comment]
Hey @phyllisstein thanks for the issue!

This _could_ be an issue with jsdom creating objects that don't extend from `Object.prototype`. Currently there's no proper way for chai to apply `should` to other prototypes, but you can monkey patch it if you have references to those jsdom objects:

```js
should() // Here's where you set up the `should` interface
HTMLElement.prototype.should = Object.prototype.should // here's where you can apply the `should` object to other objects
```

I have a hunch that this is the issue - I don't think it'll be a problem specifically with Jest. Let me know how you get on with this, I'll close this issue for now but we can re-open if the above doesn't fix the problem.

**Comment by phyllisstein** [comment]
Thanks so much for responding so quickly! I agree that it _feels_ unlikely that Jest specifically would trip up `should`; that said, in the repo that I posted above, an identical set of `should`-syntax tests passes in Mocha and fails in Jest. What's more, the issue isn't limited to JSDOM---it's also affecting native objects like `URL`...

```
● ProsceniumClient › initialization › creates a URL object for the server URL

  TypeError: Cannot read property 'be' of undefined

    13 |   describe('initialization', () => {
    14 |     it('creates a URL object for the server URL', () => {
  > 15 |       pc.serverURL.should.be.an.instanceof(URL)
       |                           ^
    16 |     })
    17 |
    18 |     it('creates a new IFrame', () => {

    at Object.it (spec/client/proscenium-client-spec.ts:15:27)
```

...as well as custom constructors...

```
● RPCDispatcher › initialization › stores a reference to the client

  TypeError: Cannot read property 'be' of undefined

    14 |   describe('initialization', () => {
    15 |     it('stores a reference to the client', () => {
  > 16 |       rpc.client.should.be.an.instanceof(ProsceniumClient)
       |                         ^
    17 |     })
    18 |   })
    19 |

    at Object.it (spec/client/rpc/rpc-dispatcher-spec.ts:16:25)
```

...and the `should.throw` extra:

```
● RPCListener › #receiveMessage › throws when message › includes an invalid message ID

  TypeError: Cannot read property 'an' of undefined

    80 |         }
    81 |
  > 82 |         should.throw(() => rpc.receiveMessage(mockMessage))
       |         ^
    83 |           .an('error')
    84 |           .with.property('messageID', '-1')
    85 |       })

    at Object.it (spec/client/rpc/rpc-listener-spec.ts:82:9)
```

But not through Mocha. Without wanting to belabor the point or insist that it's Jest specifically, I _do_ think the issue extends beyond the JSDOM prototypes.

**Comment by phyllisstein** [comment]
Just for kicks, I switched the Jest runner from its internal Jasminey implementation to [`jest-runner-mocha`](https://github.com/rogeliog/jest-runner-mocha) and got my `should`s back. (Except for `should.throw`, which it seems I may be using incorrectly.) Not sure what that portends, but I _think_ it implies there's a Jest issue.

**Comment by keithamus** [comment]
Ah that's interesting! Thanks for the report! It may be that Jest uses some kind of new vm context per file or every describe call or something, so you might need `should()` every place where Jest opens a new vm context. I'm not familiar enough with Jest to know what's going on here - but it seems like an issue report on the jest issue tracker might be the right way to report this 😄
