### ISSUE TITLE
Add something along the line of junit5 Assertions.assertAll()

### ISSUE THREAD

**Issue by silkentrance** [chaijs/chai#1166]
Considering junit5's Assertions.assertAll() which takes an array of lamdas/callbacks, I would prefer something like

```
chai.all(
  () => { chai.assert.equals(...) }.
  ... multiple assertions follow
);

or, considering standard javascript

chai.all(
 [
   function () { chai.assert...; },
   myAsserts(params...), /* returns array of callbacks */
   ...
 ],
 function () { chai.assert...; }
);
```

``all`` should accept arbitrary combinations of arrays of functions and functions, which in turn will allow the user to use factories for creating such assertions and passing these to ``all``.

The rationale behind this is that when using multiple assertions, the first assertion that fails will cause the whole test to fail and any following assertions will never be executed, e.g.

```
it('first assertion that fails wins', function () {
  assert.isTrue(false);
  assert.isFalse(false);
});
```

I am currently working on a PR for this.

**Comment by keithamus** [comment]
Hey @silkentrance thanks for the issue.

We currently have `.and` which lets you easily chain multiple assertions together:

```js
expect(3).to.be.a('number').and.be.lt(5).and.gt(0)
```

We also have the `.satisfy` assertion:

```js
expect(3).to.satisfy((expected) => {
  return typeof expected === 'number' && expected > 0 && < 5
})
```

You can use both of these today in Chai 4. Hopefully these address your request.

--- 

Having said that, I like the idea of making satisfy take multiple assertions though. I think it would likely take the shape of something with the matcher API planned in chai 5; so you could do something like:

```js
expect(3).to.satisfy(expect.to.be.a('number'), expect.to.be.lt(5), expect.to.be.gt(5))
```

Of course if `satisfy` worked that way and was also a matcher you could do stuff like:

```js
const numberBetween0and5 = expect.to.satisfy(expect.to.be.a('number'), expect.to.be.lt(5), expect.to.be.gt(0))

expect(3).to.satisfy(numberBetween0and5)
```

Of course, these are all just different flavours of the same thing. Regardless, I've added this to our Roadmap https://github.com/chaijs/chai/projects/2 and so it is something we'll think about with a later release of chai. For now you can use the first 2 methods though. I'll close this issue as we've now got it in our roadmap.

**Comment by silkentrance** [comment]
@keithamus thanks for the valuable input. this sounds very good and I can't wait to have it in Chai 5.
