### ISSUE TITLE
Is there any way to get 2 collections: default chai properties and methods?

### ISSUE THREAD

**Issue by max-xk** [chaijs/chai#1171]
Hello everyone! 

It is "question" type of issue.

I'm writing some kind of wrapper for chai.js to use assertion text chains in cucumber.js .feature files.
I wonder is there any way to get 2 collections: one with all default chai properties, other one with all default methods.

As I can see they are added here: https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js
The result I want to achieve: distinguish default methods from default properties, when passing an assertion text chain. For example, passing 'to.be.true' does not require any actual value and on contrary 'to.equal' requires it.

**Comment by keithamus** [comment]
Hey @max-xk I dont think the architecture currently allows for this. You could try iterating over every key and checking the function arity (`func.length`) which might give you a good idea - most of the "property assertions" have a `.length` of `0`.

It is likely that in Chai 5 we'll do away altogether with property assertions, and assertions like `.to.be.true` will need to be changed to `.to.be.true()`. 

I'll close this for now - as it isn't an actionable issue we need to address, but please feel free to continue the conversation. Just closing for housekeeping.

**Comment by max-xk** [comment]
Got it! Thank you for quick response!
