### ISSUE TITLE
Cannot use .to.throw with proxied constructor

### ISSUE THREAD

**Issue by alekitto** [chaijs/chai#1173]
Hi,
I have an issue using .to.throw assertion with a constructor that is being proxied: calling it will throw a `TypeError` in node < 10.
This is caused by the `toString` method being called into the `assertThrows` function on the error constructor passed for matching.

Ex:

```js

const myError = new Proxy(class extends Error {}, {});

...

/*
 * will throw TypeError in node < 10 with message
 * Function.prototype.toString requires that 'this' be a Function
 */
expect(fn).to.throw(myError);

```

Since the Function.prototype.toString revision has been implemented on v8 shipping with node 10, this code does not throw a TypeError any more, but it is still a problem in older releases.

Thank you so much for your work.

**Comment by keithamus** [comment]
Hey @alekitto thanks for the issue.

We'll be sure to get this fixed soon. I've added this to our Roadmap https://github.com/chaijs/chai/projects/2! We'll be releasing chai 5 soon, but for now I'll close this issue because it is tracked on our roadmap.
