### ISSUE TITLE
"deep include" do "deep equal", not include

### ISSUE THREAD

**Issue by slimee** [chaijs/chai#1177]
Hi,

I think this should be true, but it's false. Is that normal?

```
expect(
   { _id: 1, items: [ { _id: 2, color: '#222FB7', name: 'B' }, { _id: 3, color: '#DA6137',name: 'P' } ] }
).to.deep.include(
   { _id: 1, items: [ { _id: 2, name: 'B' }, { _id: 3, name: 'P' } ] }
)
```

**Comment by meeber** [comment]
@slimee The assertion is currently behaving as documented [here](https://github.com/chaijs/chai/blob/058ddadb8422238b418d0c3e8f92e4f757289abd/lib/chai/core/assertions.js#L328-L329) and [here](https://github.com/chaijs/chai/blob/058ddadb8422238b418d0c3e8f92e4f757289abd/lib/chai/core/assertions.js#L349-L351). Whether or not that's the best algorithm for `.deep.include` is certainly up for debate!

**Comment by slimee** [comment]
Thanks you @meeber for your answer.

Chai is victim of its powerfull: I am surprised it do not do what I think about an assertion chain :)

With you doc underline I understand better I think:

Include : all of the direct members in actual should be in expected
Deep : the actual members will be compared deeply and stricly with the ones in expected

I was thinking deep will be not strict, to.

Can chai cover this: 
All terminal json paths in actual and in expected are stricly equals.
By terminal I mean the ones containing raw values.

Thanks you

**Comment by keithamus** [comment]
@slimee thanks for this issue.

We'll definitely take this feedback on board. While this is documented behavior for now, as @meeber says it's up for debate. We're reinvestigating every assertion for Chai 5, and so we'll come across this one soon enough and see what we can do.

I'm going to close this for now, because there is nothing for us to do right now, but rest assured this has been noted, and we'll be making sure to keep this in mind in the future.

**Comment by meeber** [comment]
@slimee One imperfect workaround, which may suffice for you if you're not dealing with huge objects, is to use the `nested` flag:

```js
it('test', function () {
  expect(
    { _id: 1, items: [ { _id: 2, color: '#222FB7', name: 'B' }, { _id: 3, color: '#DA6137',name: 'P' } ] }
  ).to.deep.nested.include(
    { _id: 1, 'items[0]._id': 2, 'items[0].name': 'B', 'items[1]._id': 3, 'items[1].name': 'P' }
  )
});
```
