### ISSUE TITLE
Impossible to "overwrite chainable method" for `include`

### ISSUE THREAD

**Issue by fgeorges** [chaijs/chai#1178]
Hi.  I am trying to overwrite the chainable method `include` (AKA `contain`, AKA `contains`.)  But it seems there is a problem with that (not definitively sure whether it is on my side, on the doc's, or on Chai's.)

I could reduce the problem down to this minimal, one-file example (of course, the method should guard the overwritten usage, defer to super, etc., but that is irrelevant to this ticket):

    const chai = require('chai');
    
    chai.use(function(_) {
        _.Assertion.overwriteChainableMethod(
        'include',
        function(s) {
            return function(name) {
                new _.Assertion(this._obj).to.equal(name);
            };
        },
        function(s) {
            return s.call(this);
        });
    });

    chai.expect('foo').to.include('foo');

When executed, the first anonymous function is not even called (the one that only returns the implementation of the overwriting method.)  Instead, I get the following stacktrace (indeed, before even hitting "user code"):

    fgeorges:/tmp$ node bug-include.js
    /tmp/node_modules/chai/lib/chai/utils/overwriteChainableMethod.js:48
        var result = chainingBehavior(_chainingBehavior).call(this);

    TypeError: Cannot read property 'call' of undefined
        at Assertion.overwritingChainableMethodGetter (/tmp/node_modules/chai/lib/chai/utils/overwriteChainableMethod.js:48:53)
        at Assertion.chainableMethodGetter (/tmp/node_modules/chai/lib/chai/utils/addChainableMethod.js:91:44)
        at Object.get (<anonymous>)
        at Object.proxyGetter [as get] (/tmp/node_modules/chai/lib/chai/utils/proxify.js:86:22)
        at Object.<anonymous> (/tmp/bug-include.js:44:22)
        at Module._compile (module.js:652:30)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
        at Function.Module._load (module.js:497:3)
    fgeorges:/tmp$ 

I used `npm i chai` yesterday to install Chai for this test.

Any idea?

**Comment by meeber** [comment]
@fgeorges Based on [this](https://github.com/chaijs/chai/blob/058ddadb8422238b418d0c3e8f92e4f757289abd/lib/chai/utils/overwriteChainableMethod.js#L37), I think what you need is this:

```js
const chai = require('chai');

chai.use(function(_) {
    _.Assertion.overwriteChainableMethod(
    'include',

    function(s) {
        return function(name) {
            new _.Assertion(this._obj).to.equal(name);
        };
    },
    function(s) {
        return function() {
          s.call(this);
        }
    });
});

chai.expect('foo').to.include('foo');
```

**Comment by keithamus** [comment]
Hopefully the above solves your issue @fgeorges. 

I think what I'll do is close this - we're redoing the plugin system for Chai 5 which will likely cater for this kind of code pattern. The chai 5 Roadmap is here https://github.com/chaijs/chai/projects/2. We'll be releasing chai 5 soon, but for now I'll close this issue because it is definitely something we'll be looking at for the next release.

**Comment by fgeorges** [comment]
Thank you, @meeber!  My bad, I got lost somewhere.

Yes it does, @keithamus.  Looking forward to Chai 5 then :-)  If I can submit a suggestion, it might be useful to add this use case to the excellent "Building a Helper" guide (probably in the Chai 5 adaptation of that guide, indeed.)

On a side note, what's the best way to ask a question?  Here?  On a mailing list? (just in order to send me to the right place, the question is "*when to use addMethod() instead of overwriteMethod(), as we can never be sure it does not already exist?*")

**Comment by keithamus** [comment]
@fgeorges We have a [slack channel](https://chai-slack.herokuapp.com/) on which I am usually available for short questions. StackOverflow is another good place to look, or of course you can ask here.

To answer your question - I would suggest always using `overwriteMethod` and just check the method exists before calling it in the super call. This is not ideal but then again neither is the need for `add/overwriteMethod` - Chai 5 will address this so you don't need to make the decision.
