### ISSUE TITLE
Expect map and set not working

### ISSUE THREAD

**Issue by OlegK96** [chaijs/chai#1180]
Hi.
The following code does not work : 
expect(new Map([['a', 1], ['b', 2]])).to.have.all.keys('a', 'b');
expect(new Set(['a', 'b'])).to.have.all.keys('a', 'b');

**Comment by meeber** [comment]
What error are you getting? This works for me with Node v10.8.0, Chai v4.1.2, Mocha v5.2.0:

```js
const { expect } = require("chai");

it("testing", function () {
  expect(new Map([['a', 1], ['b', 2]])).to.have.all.keys('a', 'b');
  expect(new Set(['a', 'b'])).to.have.all.keys('a', 'b');
});
```

**Comment by OlegK96** [comment]
AssertionError: expected {} to have keys 'a', and 'b'

**Comment by OlegK96** [comment]
Running Mocha 3.5.3 Chai 3.5.0 Node 8.9.3

**Comment by meeber** [comment]
I don't think the Map and Set logic was added until Chai 4.x

**Comment by keithamus** [comment]
Indeed `Map` and `Set` were not introduced until Chai 4.

I'll close this issue, as we won't be backporting that functionality to Chai 3. @OlegK96 I'd recommend upgrading to Chai 4 if you want Maps and Sets to work.
