### ISSUE TITLE
Finding property with minimal string distance is slow

### ISSUE THREAD

**Issue by schuay** [chaijs/chai#1183]
Found while investigating the web-tooling-benchmark:

We spend almost 1/3 of all time in the chai web-tooling-benchmark on sorting properties. The custom compare function is excessively expensive:

https://github.com/chaijs/chai/blob/7db5214a5ff2c1984672cc71e35d333284aa60d6/chai.js#L9098

For this use-case, sorting isn't necessary at all since we're only interested in the property with minimal string distance. Instead, it could be determined in linear time in a single iteration.

**Comment by meeber** [comment]
@schuay Looks related to the discussion in https://github.com/chaijs/chai/pull/1098. We always welcome performance improvements, but it's worth stressing that this isn't a critical codepath; it's only hit when someone writes a test with invalid Chai syntax (e.g., misspelling "true" in `expect(myVar).to.be.ture`).

**Comment by schuay** [comment]
Thanks for the pointer, indeed #1098 looks relevant. I think we can close this as a duplicate.

> it's worth stressing that this isn't a critical codepath

Right, that's what it looked like. I wonder why the test suite / the web-tooling-benchmark stresses this path so much. As it stands, web-tooling-benchmark/chai is basically an Array-sort-with-a-crazy-expensive-comparison-function benchmark. cc @bmeurer
