### ISSUE TITLE
DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated

### ISSUE THREAD

**Issue by RezaOwliaei** [chaijs/chai#1185]
Using chai@4.1.2 and node v10.9.0, I'm receiving the warning on the following assertion:

`result.should.be.an('object').that.have.all.keys('a','b');`

**Comment by keithamus** [comment]
Hey @RezaOwliaei thanks for the issue.

We'll have this fixed for Chai 5, which we'll be releasing soon. We have an in-progress version which already fixes this issue. You can follow the progress of Chai 5 here: https://github.com/chaijs/chai/projects/2! I'll close this issue for now as we'll definitely have this fixed for Chai 5.
