### ISSUE TITLE
chai-sorted on cypress

### ISSUE THREAD

**Issue by mandriao84** [chaijs/chai#1189]
Hello,
Can you tell me how I can install chai-sorted on cypress.

I don't know what to wirte on the index.js files of cypress.
I write this, but it's not working

```
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
require("chai-sorted")
}
```

thank you

**Comment by meeber** [comment]
I haven't used cypress before, but in general Chai plugins are loaded via `Chai.use()`. Looks like Cypress provides some guidance on using Chai plugins [here](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/extending-cypress__chai-assertions).
