### ISSUE TITLE
.to.deep.include does not work as expected

### ISSUE THREAD

**Issue by croraf** [chaijs/chai#1192]
I checked this issue but it is not the same: https://github.com/chaijs/chai/issues/1177.

I have the following expect:
`expect({a: 5, b: {c: 1}}).to.deep.include({b: {c: 1}});`

This should pass without assertion error, but it obviously compares by reference and not deeply and assertion fails.

chai version: 3.5.0

**Comment by croraf** [comment]
I upgraded chai to the version 4.1.2 and it seems it is now working as expected. If someone can confirm this has been fixed in between 3.5.0 and 4.1.2

**Comment by meeber** [comment]
Confirmed. `.deep.include` wasn't added until Chai v4.
