### ISSUE TITLE
BigInts are not properly supported by assertions

### ISSUE THREAD

**Issue by no2chem** [chaijs/chai#1195]
Although BigInts are a stage 3 proposal, they are supported in Node 10 and V8 6.3. One of the quirks of BigInt is that it's not JSON serializable. When attempting to compare two BigInts, chai uses the JSON, which produces the wrong result.

Here's a minimum example, which works on Node 10 and Chai 4.1.2
```javascript
> let chai = require('chai')

> chai.should()

> 1n.should.equal(1n)
// ↪AssertionError: expected {} to equal {}

> 1234n.should.equal(123n)
// ↪AssertionError: expected {} to equal {}
```

I think Chai should check if typeof returns 'bigint'
```javascript
> typeof 123n
// ↪'bigint'
```
And use equality to make the comparison in that case (and toString()) instead of JSON serialization.

I'm happy to take a look at this if this is something that others think Chai should support.

**Comment by keithamus** [comment]
Hey @no2chem thanks for the issue.

We'll definitely make sure to tackle bigints in the next version of chai! We've added this to our Roadmap https://github.com/chaijs/chai/projects/2! We'll be releasing chai 5 soon, but for now I'll close this issue because it is tracked on our roadmap.

**Comment by MicahZoltu** [comment]
I'm still experiencing this with the latest version of Chai.  I believe `bigint` is now stage 4 or final, would really like to see it get supported.

**Comment by mattbishop** [comment]
FYI, Mocha just merged support for bigint into their stringify() function: https://github.com/mochajs/mocha/pull/4112
