### ISSUE TITLE
chaijs.com assets are broken :(

### ISSUE THREAD

**Issue by c24w** [chaijs/chai#1197]
For example:
>`Mixed Content: The page at 'https://www.chaijs.com/api/assert/' was loaded over HTTPS, but requested an insecure script 'http://www.chaijs.com/js/main.js'. This request has been blocked; the content must be served over HTTPS.`

**Comment by vincentkwok** [comment]
+1

**Comment by lucasfcosta** [comment]
@chaijs/chai shall we migrate our docs over to another place?

**Comment by keithamus** [comment]
Hey y'all! Thanks for raising this.

This is a dupe of https://github.com/chaijs/chaijs.github.io/pull/177 which is the PR that should solve this. I'll close this as we can track it in https://github.com/chaijs/chaijs.github.io/pull/177

**Comment by keithamus** [comment]
FYI this should now be fixed
