### ISSUE TITLE
[Feature Request] Convert to ES Modules

### ISSUE THREAD

**Issue by pdesjardins90** [chaijs/chai#1211]
With all major browsers now supporting ES modules and node support on its way, I think it would be a great time to migrate this popular lib and help the community move forward.

To be clear, the goal would be to be able to do:

In node: 

```javascript
import { expect } from 'chai'
```

In browsers:
```javascript 
import { expect } from '/node_modules/chai/chai.js'
```

**Comment by keithamus** [comment]
Thanks for your work on this @pdesjardins90! Your changes look awesome!

We've actually got a new version of chai (version 5) in the works right now. It's a complete rewrite from the ground up and we make extrensive use of ES6 modules. 

You can follow the progress of Chai 5 on the Roadmap https://github.com/chaijs/chai/projects/2! We'll be releasing chai 5 soon. 

I understand you put a lot of work into your PR - and I don't really want to turn you away for making such a cool contribution, so if you're interested to work on new parts of Chai 5 perhaps we could find some more interesting things for you to contribute to?

I'll close this issue for now - and the PR. Please let me know if you're interested in contributing more though!
