### ISSUE TITLE
Expect doesn't work with style

### ISSUE THREAD

**Issue by filipenatanael** [chaijs/chai#1218]
Hey there!

I'm getting the below error message when trying to run the tests.

`expect(wrapper).to.have.style('background-color').equal('#ccc');`

**Returns:** 
 _TypeError: (0 , _chai.expect)(...).to.have.style is not a function"_

But when I write the code as below, everything works correctly.

`expect(wrapper.props().style.backgroundColor).to.be.equal('#ccc');`

But this is correct? is there another way?

#### API

- [x] shallow

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.0.0
| react               | 16.3.2
| react-dom           | 16.3.2
| react-test-renderer | 16.0.0
| chai     | 3.5.0
| adapter (below)     | 1.0.0

#### Adapter

- [x] enzyme-adapter-react-16

**Comment by meeber** [comment]
Hi @filipenatanael. The `style` assertion isn't built into Chai core. Looks like the [chai-enzyme](https://github.com/producthunt/chai-enzyme) plugin might provide what you're looking for.
