### ISSUE TITLE
expect to.be not throwing

### ISSUE THREAD

**Issue by dnalborczyk** [chaijs/chai#1219]
Is this intended behavior, or is this a bug?

chai `v4.2`, although tried `v3.x` and `v2.x` as well.

```javascript
expect(1).to.be.true;  // works
expect(true).to.be.false;  // works
expect(true).to.be.anything;  // works
expect(true).to.be;  // works
expect(true).to;  // works

expect(true).to.equal(false);  // throws correctly
```

**Comment by meeber** [comment]
If it helps, the contents of my `package.json` are:

```js
{
  "name": "meep",
  "version": "1.0.0",
  "scripts": {
    "test": "mocha"
  },
  "license": "ISC",
  "dependencies": {
    "chai": "^4.2.0",
    "mocha": "^5.2.0"
  }
}
```

The test file is `test/index.js`.

And I ran the tests via `npm test`.

**Comment by dnalborczyk** [comment]
found the culprit:

```javascript
const chai = require("chai");
const expect = chai.expect

const dirtyChai = require('dirty-chai');
chai.use(dirtyChai);
```

just contributing to another open source project and I haven't used chai myself before.

thanks again @meeber for looking into this.

**Comment by dnalborczyk** [comment]
btw, one of the reasons I didn't see this is because it modified the _original_ chai module in another test file, and therefor was loaded that way in every test [following the modification I suppose].

**Comment by meeber** [comment]
Makes sense. If I recall correctly, the `dirty-chai` package converts all property-based assertions (e.g., `to.be.true`) into method-based assertions (e.g., `to.be.true()`).

**Comment by dnalborczyk** [comment]
aaaah, I see. you're right! thank you!
