### ISSUE TITLE
Plugin autodetection not working

### ISSUE THREAD

**Issue by kwirke** [chaijs/chai#1223]
Hi guys,

I released a chai plugin some days ago (https://www.npmjs.com/package/maybe-chai) and I would love it to appear on the official list (https://www.chaijs.com/plugins/).

According to the docs it's enough to set the proper keywords in package.json, however this does not seem to be working for me. Am I missing something or did something wrong?

Thanks for your support and your amazing library!

**Comment by keithamus** [comment]
Hey @kwirke thanks for letting us know about this! 

There was an error in the nightly job, which has now been fixed. Your plugin is now on the website! https://www.chaijs.com/plugins/maybe-chai/

Thanks for writing a cool plugin!
