### ISSUE TITLE
Assertion error does not state problematic parts for Maps

### ISSUE THREAD

**Issue by pcorpet** [chaijs/chai#1228]
```js
chai.expect(new Map([['a','a']])).to.deep.equal(new Map([['a','b']]))
// AssertionError: expected {} to deeply equal {}
```
As you can see it is not clear why it fails from the error message.

**Comment by keithamus** [comment]
Thanks for this @pcorpet but we're very close to releasing a new version of the inspection engine: https://github.com/chaijs/loupe/pull/14. 

Once we get `loupe@2` out we'll be updating Chai to use it, and it will replace all `inspect` code.

We really appreciate the work you've done here! I hope in closing this PR we don't dissuade you from making further contributions!

**Comment by pcorpet** [comment]
Hi @keithamus thanks for the update. As the bug is still there, can you keep the issue open, and close the PR instead?

**Comment by keithamus** [comment]
Oops I thought I did that, sorry!

**Comment by Hocdoc** [comment]
Will there be a solution for this issue in the next months?

**Comment by pcorpet** [comment]
It seems that [Loupe v2](https://github.com/chaijs/loupe/releases) is out, what's the next step @keithamus ?

**Comment by keithamus** [comment]
The next step would be to somehow integrate it into the 4.x branch. It might be worth first adding it to the main branch - which will allow for breaking changes - then we can assess what breakages need to be smoothed over for 4.x

**Comment by flaambe** [comment]
I tried to integrate the loup into chai, but unfortunately now I do not have enough time for this

**Comment by pcorpet** [comment]
I've created a PR, please help me there to understand which changes are OK, and which ones are not

**Comment by pcorpet** [comment]
This is not way better now, if I introduce only one change in one value:
```
AssertionError: expected Map{ …(17) } to deeply equal Map{ …(17) }
```

Any idea how to fix?
