### ISSUE TITLE
[!] Error: 'assert' is not exported by node_modules/chai/index.js

### ISSUE THREAD

**Issue by vedtam** [chaijs/chai#1231]
Hi,

When running my test trough rollup to prepare it for karma and the browser I get:

`Error: 'assert' is not exported by node_modules/chai/index.js`

I use the import statement from the docs:

`import { assert } from 'chai';`

I saw that the module uses common js exports, so I'm confused why the above import statement exists at all?

test:

```
import { assert } from 'chai';

suite('simple test addition');

test('testing if 1 is equal to 1', async () => {
  assert.equal(1 === 1, true);
});
```
rollup config:

```
module.exports = {
    input: 'dist/test/index.js',
    output: {
      file: 'dist/test/bundle.js',
      format: 'iife'
    },
    plugins: [
        nodeResolve({
        jsnext: true,
        main: true,
        browser: true,
      }),
      commonjs()
    ]
  };
```

I would really appreciate if someone could light me up.
Thanks!

**Comment by meeber** [comment]
I suspect that was written 2-3 years ago and had some applicability to whatever transpiling was popular at the time. As I mentioned in #1232, I've fallen behind a bit on recent JavaScript and ES6 module changes. We definitely don't the docs to be confusing or outright wrong; @keithamus may have better insight at this point.

**Comment by vedtam** [comment]
Thanks @meeber for the details, I'm wondering why nobody complained so far? 😅

**Comment by vedtam** [comment]
@keithamus thanks for the hint, it work using the mentioned option, however I get circular dependencies warning in rollup:

`Circular dependency: node_modules/chai/lib/chai.js -> node_modules/chai/lib/chai/utils/index.js -> node_modules/chai/lib/chai/utils/addProperty.js -> node_modules/chai/lib/chai.js`

While waiting for chai5 will use `karma-chai`.
Thanks!

**Comment by lazka** [comment]
fyi, the last release of @rollup/plugin-commonjs no longer needs the namedExports workaround and figures things out automatically.
