### ISSUE TITLE
Security 

### ISSUE THREAD

**Issue by jolanda1** [chaijs/chai#1239]
Hi, 

Is there any information on security? e.g. what are the security risks involved, how are these mitigated? 

Thanks! 

Jolanda

**Comment by lucasfcosta** [comment]
Hi @jolanda1,

Can you please be more specific on what you mean by security or give us a more in-depth description of your question?

I'll keep this open for a while but will close as stale in a few weeks.

**Comment by lucasfcosta** [comment]
Closing as stale.
