### ISSUE TITLE
Document supported browsers

### ISSUE THREAD

**Issue by eastridge** [chaijs/chai#124]
We're running into some trouble running our test suite for [Thorax](http://walmartlabs.github.com/thorax) with chai. IE9 is fine, but we get this error on IE8:

" Object doesn't support property or method 'create' "

In addition we had to replace `to.be.true` with `to.be['true']` etc.

It would be a nice addition to the website to know which versions of what browsers chai officially supports.

**Comment by keithamus** [comment]
It's come up a few times recently, so I'm going to try to push this issue a little more forward.

Here are my 2c about the whole browser support thing:

I think, given we're a testing framework, we need to support a broad range of versions. But also, given our limited person power, we need to be relatively conservative. I think supporting every engine that is officially supported by their respective vendors is a happy and relatively non-arbitrary point to fix to ([Node](https://github.com/nodejs/LTS), [Firefox](https://en.wikipedia.org/wiki/Firefox_release_history), [Chrome](https://en.wikipedia.org/wiki/Google_Chrome_release_history), [Opera](https://en.wikipedia.org/wiki/History_of_the_Opera_web_browser), [Safari](https://en.wikipedia.org/wiki/Safari_version_history), [Edge](https://en.wikipedia.org/wiki/Microsoft_Edge#Release_history), [IE](https://support.microsoft.com/en-us/help/17454/lifecycle-support-policy-faq-internet-explorer))

This means supporting Node 0.10 until October 1st or thereabouts, and 0.12 until the end of this year. IE wise, this means supporting IE9 until April 2017 (when Vista's extended support ends), IE10 and above for longer. For Firefox we'll support whatever the ESR version is, plus latest. Chrome, Opera and Safari only officially support their latest versions, so we'll do the same. All of these versions should run through CI so we know we're not breaking them.

I think in addition to all of that, we should provide what I'll call "soft" support for other versions. By soft support I mean if someone files an issue, we'll attempt to fix it - but sweeping architectural changes or large fixes will not be considered. This means users are welcome to try to use Chai in unsupported browsers, and if they encounter breakages, feel free to report them - however, also acknowledge that we might close issues saying we don't have manpower to provide the support you're after.
