### ISSUE TITLE
not strict compare assertion is missing

### ISSUE THREAD

**Issue by lightbringer1991** [chaijs/chai#1250]
So I have the following scenario to test
```javascript
const expected = { x: '1' };
const actual = { x: 1 };
```

just wondering if there is a deep compare that allows comparing value and not type.
```javascript
// e.g.
expect(actual).to.deep.value.eql(expected);
```

**Comment by keithamus** [comment]
Hey @lightbringer1991 thanks for the issue.

This is a great idea! We've added this to our Roadmap https://github.com/chaijs/chai/projects/2! We'll be releasing chai 5 soon, but for now I'll close this issue because it is tracked on our roadmap.

**Comment by lightbringer1991** [comment]
@keithamus sounds great, please let me know if a contribution is needed.
