### ISSUE TITLE
expect to throw not catching error

### ISSUE THREAD

**Issue by tcurdt** [chaijs/chai#1254]
The following code works as expected:

    try {
      await Request.new(0)
      assert(false, "should have thrown")
    } catch (error) {
      assert( /invalid address/.test(error),
        "unexpected error: " + error )
    }

I thought the chai equivalent would be

    expect(async () => {
      await Request.new(0)
    }).to.throw(Error, /invalid address/)

but instead the test is failing with

       "after each" hook: after test:
     Uncaught Error: invalid address (arg="_project", coderType="address", value=0)
      at Object.throwError (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/~/ethers/utils/errors.js:68:1)

seemingly not catching the error at all.

This is with `Truffle v5.0.14 (core: 5.0.14)` which seems to use `chai@4.2.0`

User error? Any pointers?

**Comment by zachlysobey** [comment]
I don't think you can test `async` code with `.throw()`. That is, it needs to take a function that throws synchronously, not return a `Promise` that *rejects*.

see: https://github.com/chaijs/chai/issues/415

the `chai-as-promised` library might be worth looking at:
https://github.com/domenic/chai-as-promised

**Comment by keithamus** [comment]
Thanks for the issue @tcurdt! 

@zachlysobey is right, an `async` function - when executed - will not throw, instead only returns a rejecting Promise.

I'll close this. We will adding Promise support in Chai 5, and its on the roadmap, but I'll close this issue as we're tracking Promise support separately!
