### ISSUE TITLE
Remove require cycles

### ISSUE THREAD

**Issue by 3rd-Eden** [chaijs/chai#1256]
With the release of [ekke](https://github.com/godaddy/ekke) it's now possible to run test suites inside of React-Native. This also means that assertion frameworks such as `chai` can be used to assert within those tests.

Chai works out of the box for this new project without any required changes, which is pretty cool. Unfortunately, there are some warnings that show up when `chai` is being required using `metroRequire`, which is the `require` system that React-Native uses.

These warnings are shown because of certain files that trigger a require cycle where files are pointing back to the file that is currently being required. So I wonder if those require cycles could be removed so `chai` doesn't trigger these warnings every time it's required.

The following warnings will be shown when the library is required:

```
Require cycle: node_modules/chai/lib/chai.js -> node_modules/chai/lib/chai/utils/index.js -> node_modules/chai/lib/chai/utils/addProperty.js -> node_modules/chai/lib/chai.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
Require cycle: node_modules/chai/lib/chai.js -> node_modules/chai/lib/chai/utils/index.js -> node_modules/chai/lib/chai/utils/addMethod.js -> node_modules/chai/lib/chai.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
Require cycle: node_modules/chai/lib/chai.js -> node_modules/chai/lib/chai/utils/index.js -> node_modules/chai/lib/chai/utils/overwriteProperty.js -> node_modules/chai/lib/chai.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
Require cycle: node_modules/chai/lib/chai.js -> node_modules/chai/lib/chai/utils/index.js -> node_modules/chai/lib/chai/utils/overwriteMethod.js -> node_modules/chai/lib/chai.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
Require cycle: node_modules/chai/lib/chai.js -> node_modules/chai/lib/chai/utils/index.js -> node_modules/chai/lib/chai/utils/addChainableMethod.js -> node_modules/chai/lib/chai.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
Require cycle: node_modules/chai/lib/chai.js -> node_modules/chai/lib/chai/utils/index.js -> node_modules/chai/lib/chai/utils/overwriteChainableMethod.js -> node_modules/chai/lib/chai.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
```

**Comment by keithamus** [comment]
Thanks for the issue @3rd-Eden!

There's good news and bad news: the bad news is without a big re-architecture things like circular dependencies are not going away. The good news is we're doing a big re-architecture! You can follow along on our roadmap here: https://github.com/chaijs/chai/projects/2! We'll be releasing chai 5 soon, but for now I'll close this issue because it'll happen intrinsically as part of the new chai 5 developments.

**Comment by akauppi** [comment]
I also got this, importing `chai` (4.2.0) as ES6 module with Rollup. (just saying, I know the ticket is closed)
