### ISSUE TITLE
The assertion error for 'incude(object, propName)' is cryptic when 'propName' is a string

### ISSUE THREAD

**Issue by AndreyBelym** [chaijs/chai#1263]
When you make a mistake and use `assert.include` instead of `assert.property` to assert that an object has a specific property (e.g. `assert.include({ foo: 'bar' }, 'foo');`), the error message is very unclear:
```
> chai.assert.include({ foo: 'bar' }, 'foo')

AssertionError: object tested must be an array, a map, an object, a set, a string, or a weakset, but object given
```

Can we do something to indicate clearly that this combination of arguments (an object + a string) is not possible for `assert.include`?

**Comment by keithamus** [comment]
Hey @AndreyBelym thanks for the issue!

This sounds like a good idea, PRs are welcome 😄. Should you need any guidance on making a PR for this, please feel free to ask 🙂

**Comment by rpgeeganage** [comment]
@AndreyBelym ,
if you prefer, I can look into this.

**Comment by lucasfcosta** [comment]
Hi @rpgeeganage I think that given there's a few days since this has been first posted and it's not currently active it would be great if you are willing to look into it. Feel free to send open a PR if you wish 😄

**Comment by AndreyBelym** [comment]
@rpgeeganage it would be awesome, thank you. I'm afraid I can't find enough time to implement it on my own.

**Comment by rpgeeganage** [comment]
@lucasfcosta , @AndreyBelym ,
Thanks. I'll look into this.
