### ISSUE TITLE
How I can test 2 object has a array without order

### ISSUE THREAD

**Issue by HayTran94** [chaijs/chai#1265]
Object 1:
```
const obj1 = {
    arr: [{
      a: 'a11',
      b: 'b11',
    },
    {
      a: 'a12',
      b: 'b12',
    }],
  };
```
Object 2:

 ```
const obj2 = {
    arr: [{
        a: 'a12',
        b: 'b12',
      },
      {
        a: 'a11',
        b: 'b11',
      }],
  };
```

I hope two test case will be success. But only the first test success, the second always fail.

 ```
 it('test1', () => {
    expect(obj1).to.deep.equal(obj1);
  });
  it('test2', () => {
    expect(obj1).to.deep.equal(obj2);
  });
```

I searched on google and I found that they will compare 2 arrays in object instead of 2 objects. But my use case need to test 2 objects rather than 2 arrays. So which assertion method I must to use?
Thank you in advance.

**Comment by lucasfcosta** [comment]
Hello @HayTran94 😊 

If you wanna check what an array contains I'd recommend that you use

**Comment by HayTran94** [comment]
Hello @lucasfcosta,

Thank for your response. But my use case is comparing between 2 objects, not 2 arrays. The object has array, number and string like the following object:

```
const obj1 = {
   number: 15,
   string: 'ok',
    arr: [{
      a: 'a11',
      b: 'b11',
    },
    {
      a: 'a12',
      b: 'b12',
    }],
  };
```
So Have Chai supported that feature? Thank you

**Comment by lucasfcosta** [comment]
Ah I see now what you're trying to do.

Chai does not support that specifically.

The best alternative would probably be to use [`satisfy`](https://www.chaijs.com/api/bdd/#method_satisfy) to write a custom matcher or to use [this plugin](https://www.chaijs.com/plugins/deep-equal-in-any-order/).

**Comment by HayTran94** [comment]
@lucasfcosta  

Thank for your response. I will implement that like your recommend.
