### ISSUE TITLE
How to expect `foo` is a "class"?

### ISSUE THREAD

**Issue by eridal** [chaijs/chai#1279]
Hi all, so here's what I'd like to do:

```js
class Foo { } 
expect(Foo).to.be.a('class')
```

Which fails with `AssertionError: expected [Function: Foo] to be a class` due to *type-detect* returning `function` instead of `class`

Is there a workaround?

**Comment by is2ei** [comment]
@eridal 

How about this one?

```
const { expect } = require('chai');

class Foo {
  constructor() {
  }
}

function Bar() {
}

expect(isClass(Foo)).to.be.true;
expect(isClass(Bar)).to.be.false;

function isClass(func) {
  return typeof func === 'function' 
    && /^class\s/.test(Function.prototype.toString.call(func));
}
```

FYI: https://stackoverflow.com/a/29094209/10731676

**Comment by keithamus** [comment]
Hey @eridal thanks for the issue.

There's currently no way to assert that an object is a class. We've added this to our Roadmap https://github.com/chaijs/chai/projects/2 for Chai 5! We'll be releasing chai 5 soon, but for now I'll close this issue because it is tracked on our roadmap.
