### ISSUE TITLE
The online test suite has 12 failing tests

### ISSUE THREAD

**Issue by fizker** [chaijs/chai#1280]
https://www.chaijs.com/api/test/ has the following results:

- Safari 12.1.1: 369 passed, 12 failed
- Firefox 68.0.1: 369 passed, 12 failed
- Chrome 76.0.3809: 417 passed, 12 failed

I don't know why Chrome is running more tests that the other two browsers, but they all agree on the failure count.

**Comment by keithamus** [comment]
Hey @fizker thanks for raising this issue.

Chrome is likely running more tests because we have some tests only run with feature detection. 

I'll close this for now as we're aware of the issue and we'll look into why the tests are failing as part of the 4.3.0 release.
