### ISSUE TITLE
make a release?

### ISSUE THREAD

**Issue by rhenwood-arm** [chaijs/chai#1303]
@meeber: I would like to pick up the phantomjs removal in a release. Can a release be made please?

**Comment by lucasfcosta** [comment]
I think it's about time, let me CC @keithamus as I'd also like a release for the changes on the operator prop on the thrown error.

**Comment by keithamus** [comment]
We've got a PR in the works; https://github.com/chaijs/chai/pull/1266. There are some test failures happening though, these will need to be addressed - I'm afraid I don't have time to look into them but if we can get the PR green I can merge and release.

I'll close this issue, as the actionable stuff is in https://github.com/chaijs/chai/pull/1266
