### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by w3bdesign** [chaijs/chai#1325]
Is this project dead?

If yes, what would be the best replacement for it? Mocha?

**Comment by keithamus** [comment]
Hey @w3bdesign thanks for the issue.

The project is very much alive. Chai 4 is usable, you can install it and it works. We're working on a releasing new versions, but we have few maintainers with limited time. Most of the work at the moment has been focussed on our inspection engine, https://github.com/chaijs/loupe/, which will make error messages much more helpful for subsequent releases.

I'll close this - as I think the above should answer your question. Feel free to continue the discussion though.
