### ISSUE TITLE
assert.deepEqual / expect().to.deep.equal incorrect with Symbols as keys

### ISSUE THREAD

**Issue by derMart** [chaijs/chai#1358]
consider this:
```
var sym = Symbol('foo');
expect({[sym] : 1}).to.deep.equal({[sym] : 0});
assert.deepEqual({[sym] : 1}, {[sym] : 0});
```
I would expect both variants to fail, but they pass and do not throw an Error.
Using chai 4.2.0

The [documentation](https://www.chaijs.com/api/assert/#method_deepequal) does not state anything about this behaviour.
Is this working as intended or a bug?

**Comment by wertlex** [comment]
Well, the problem could be resolved by updating `deep-eql` version.
[`eql`](https://www.chaijs.com/api/bdd/#method_eql) underneath uses `deep-eql` which already supports Symbol comparing. However, it could be a breaking change

**Comment by snewcomer** [comment]
This PR has been merged - https://github.com/chaijs/deep-eql/pull/83

Awaiting a bump on deep-eql!
