### ISSUE TITLE
support native named import

### ISSUE THREAD

**Issue by luxferresum** [chaijs/chai#1359]
with modules being implemented native in `node` it would be nice to be able to do `import { expect } from 'chai';`. Currently this is not supported. Only `import chai from 'chai'` works.

**Comment by sebamarynissen** [comment]
@luxferresum This is functionality was added in #1340, but unfortunately no new version on npm has been published yet. You can circumvent this by requiring chai as
```npm install https://github.com/chaijs/chai#master

**Comment by keithamus** [comment]
4.3.0 has been released.
