### ISSUE TITLE
Publish new version on npm

### ISSUE THREAD

**Issue by sebamarynissen** [chaijs/chai#1369]
I was wondering whether it would be possible to publish a new version on npm. As the Node world is slowly shifting towards native esm, it would be nice to have
```js
import { expect } from 'chai';
```
but the [last version on npm](https://www.npmjs.com/package/chai) is from 2 years ago.

The functionality has already been added and merged into master (#1340), so unless I'm mistaken, I don't think there's anything holding it back. The feature has been implemented in a fully backwards compatible way, so I suggest it be a semver minor to `4.3.0`.

Currently this is the only thing holding me back to migrate an entire codebase to native esm as the tests are the first thing I'm planning to migrate. You can get around this by using `npm install https://github.com/chaijs/chai#master` if you really want, but it's not the neatest solution.

/cc @giltayar

**Comment by giltayar** [comment]
I saw that it was merged, and was wondering why it wasn't yet in the released. I am working on a new (large) codebase that is totally on the ESM, and having to write

```js
import chai from 'chai'
const {expect} = chai
``` 

is definitely a thorn in my side. I would love a new release based on my ESM entry points.

**Comment by sebamarynissen** [comment]
In another project that is also completely esm I got around it with
```js
import { expect } from './chai.js';
```
and then write the functionality manually in that `chai.js` file. It's only really viable though if all your tests are in a single folder. In my other project this is not the case and would result in creating this `chai.js` file in every test directory.

**Comment by keithamus** [comment]
4.3.0 has been released.

**Comment by sebamarynissen** [comment]
Thanks a lot!
