### ISSUE TITLE
Does this project use SemVer?

### ISSUE THREAD

**Issue by kellyselden** [chaijs/chai#1373]
I just noticed the new release was not v4.0.0, even though multiple node versions were dropped from support. Was this a mistake, or should users be warned in the README to not use carats when using chai (ex. `"chai": "^4.2.0"` will cause problems for people)? Apologies if this was answered before.

**Comment by keithamus** [comment]
They were dropped from CI as it’s too difficult to run them in CI. We’ll still answer and resolve bug reports for them if we get them.

**Comment by kellyselden** [comment]
Thanks for clearing that up. Perhaps https://github.com/chaijs/chai/blob/de12e401bc39534ae4f1ff07fd33320a391dca08/package.json#L40 should be changed to signify which node versions are still supported?

**Comment by keithamus** [comment]
Yes you're right, it should! PRs welcome!
