### ISSUE TITLE
chai.Assertion is no longer exported

### ISSUE THREAD

**Issue by rbruckheimer** [chaijs/chai#1375]
index.mjs is not exporting Assertion.  It needs a line:
`export const Assertion = chai.Assertion;`
I discovered this when attempting to upgrade from 4.2.0 to 4.3.0.

I also noticed that the code in the 4.3.0 tag here on GitHub does not match what's on npm.  npm seems to be more like the master branch.  Can you check it out please?

**Comment by keithamus** [comment]
Can you please confirm if this problem still exists in the 4.3.1 release? Thanks

**Comment by rbruckheimer** [comment]
The code now matches between the commit 8a246661566227db3d37019bb0bab3bbcdf45841 (4.3.1 tag) and npm.
However, the export issue still exists.

**Comment by keithamus** [comment]
Would you like to submit a PR for the `4.x.x` branch please?

**Comment by rbruckheimer** [comment]
https://github.com/chaijs/chai/pull/1378

**Comment by keithamus** [comment]
Fixed in `4.3.3`

**Comment by rbruckheimer** [comment]
Keith, the 4.3.3 release note says `AssertionError` is reintroduced, but it's really `Assertion` being reintroduced.  If you can fix it it will help others find the fixed version.

**Comment by keithamus** [comment]
Oops fixed!
