### ISSUE TITLE
Expect fails while comparing BigNumber

### ISSUE THREAD

**Issue by AbdulRafaySiddiqui** [chaijs/chai#1382]
Can anyone tell, why both of the following expects are failing
```
const hre = require("hardhat");
const { ethers } = hre;
const { BigNumber, utils } = ethers;

describe("Deploy YDF token and check balance", function () {
    it("Deployer balance should be equal to 30K", async function () {
        
        expect(utils.parseEther("1.0")).to.equals(utils.parseEther("1.0"));
        expect(BigNumber.from("30000000000000000000000")).to.equals(BigNumber.from("30000000000000000000000"));
    });
});
```

![](https://user-images.githubusercontent.com/46793902/110556829-1fc8db80-8161-11eb-814d-ff382eb4ff18.png)

**Comment by vapier** [comment]
i think #1365 fixed it but there isn't interest in fixing the problem in chai for some reason

**Comment by AbdulRafaySiddiqui** [comment]
It's been 5 months since you posted the PR, but still no fix, sad :(
It is better to at least fix the problem now, rather than wait to integrate loupe at some later time.

**Comment by vapier** [comment]
i'd understand if the overhaul was coming soon and no new release were being made, but dev/fixes have continued in the branch, and new releases cut.  so it seems odd that @keithamus prefers to leave chai broken.

**Comment by AbdulRafaySiddiqui** [comment]
yeah, the latest release was 8 days ago, could have added your PR, even it wasn't that long, just a couple lines of code.

**Comment by keithamus** [comment]
If you want to re-raise it on the `4.x.x` branch I'll release it.

**Comment by vapier** [comment]
@AbdulRafaySiddiqui can you give #1383 a try and see if it fixes your problems ?

**Comment by keithamus** [comment]
On second glance this is using a custom `BigNumber` constructor.

@AbdulRafaySiddiqui you should consider using `.deep.equal` instead of `equals`. `BigNumber` is not a primitive so referential equality will not work on it two instances of `BigNumber`

**Comment by AbdulRafaySiddiqui** [comment]
Thanks, @keithamus , I checked, using `.deep.equal` it works, but not just equal.
I was following waffle's [docs](https://ethereum-waffle.readthedocs.io/en/latest/matchers.html#bignumbers) , so it's wrong there I guess.

**Comment by keithamus** [comment]
Looks like it overrides the matchers. Do you have the following added:

```
import { solidity } from "ethereum-waffle";
chai.use(solidity);
```

If you don't it won't work

**Comment by AbdulRafaySiddiqui** [comment]
No, I don't have that, I was following [https://hardhat.org/getting-started/#testing-your-contracts](hardhat docs)

**Comment by AbdulRafaySiddiqui** [comment]
> Can anyone tell, why both of the following expects are failing
> 
> ```
> const hre = require("hardhat");
> const { ethers } = hre;
> const { BigNumber, utils } = ethers;
> 
> describe("Deploy YDF token and check balance", function () {
>     it("Deployer balance should be equal to 30K", async function () {
>         
>         expect(utils.parseEther("1.0")).to.equals(utils.parseEther("1.0"));
>         expect(BigNumber.from("30000000000000000000000")).to.equals(BigNumber.from("30000000000000000000000"));
>     });
> });
> ```
> 
> ![](https://user-images.githubusercontent.com/46793902/110556829-1fc8db80-8161-11eb-814d-ff382eb4ff18.png)

This is my exact code.

**Comment by keithamus** [comment]
I'm not familiar with any of these APIs so I can't tell you what you need to do but the _default_ behaviour of Chai's `.equals` operator is the same as `===`.

**Comment by AbdulRafaySiddiqui** [comment]
Hmm, that's the reason, Anyways thanks for your help, I can just use the `.deep.equal` it's fine.

**Comment by JangoCCC** [comment]
.deep.equal works, but still no fix?

**Comment by JangoCCC** [comment]
Does this issue fixed? I just encoutered the same issue.
