### ISSUE TITLE
[NODE 16] deprecation warning on exports field

### ISSUE THREAD

**Issue by Manish3323** [chaijs/chai#1387]
Error : 
<img width="1252" alt="Screenshot 2021-04-22 at 9 09 40 PM" src="https://user-images.githubusercontent.com/16453816/115743231-19a85a80-a3af-11eb-83c1-6962c9fd30be.png">

To reproduce : 
Update Node to version 16

The particular entry of package.json `exports` field 
```
   "./": "./"
```
needs to be replaced with 
```
   "./": "./*"
```

**Comment by Alhadis** [comment]
I think you mean

~~~json
	"./*": "./*.js"
~~~
