### ISSUE TITLE
expect(new Error).to.be.an('error') does not work

### ISSUE THREAD

**Issue by egebircan** [chaijs/chai#1389]
`it('test case', () => {
  expect(new Error).to.be.an('error');
})`

When the code above is executed, "AssertionError: expected [Error] to be an error" is thrown. 

According to the [docs](https://www.chaijs.com/api/bdd/) this behavior is not natural.

**Comment by martineizayaga** [comment]
The code you wrote @egebircan works for me.

**Comment by egebircan** [comment]
You are right @martineizayaga. I tested it again and it works. I guess there was some kind of an environment issue on my local machine at that moment. Thanks for pointing out.
