### ISSUE TITLE
consuming chai as ES6 module in browser

### ISSUE THREAD

**Issue by gullerya** [chaijs/chai#1391]
I'm trying to use `chai` as ES6 module in browser environment directly (no babel and no bundler) and it doesn't work, I must be missing something.

What I've tried:
The only syntax that doesn't throw is this:
```js
import * as chai from 'node_modules/chai/chai.js`;
```
BUT the `chai` object is absolutely empty.

The `index.mjs` looked promising too, but it in itself does imports from `index.js` which is already non-ES6 module compliant (`module.exports =  ...`).

What am I missing?

**Comment by gullerya** [comment]
Okay, I got the point, the intended usage seemingly is to perform 'side-effect' import and then just consume `chai` from the global scope.

Personally, it looks a bit non-standard to me, in context of ES6 modules, and seemingly you've also envision it to work more importish like, at least looking onto the `index.mjs`.

Do you plan to expose a non-global-scope approach for a browsers?

Right now I'm achieving this with importer like this:
```js
import 'node_modules/chai/chai.js';

export default globalThis.chai;
```

And then consuming it from another module in a more ES6 modules familiar way:
```js
import chai from 'chai-importer.js';

chai.assert...
```

**Comment by gullerya** [comment]
I'd actually like to reopen this since encountered this issue again and this re-exporting solution is not something intuitive that should done each and every next package.
So again - any plan to provide ES6 modules compatible distribution?

**Comment by koddsson** [comment]
> I'd like to have it like this:
> 
> ```
> import { assert } from 'chai';
> ```

This is working for me with `chai@5`:

```
 ~/temp/ node index.js
function
 ~/temp/ cat index.js
import { assert } from "chai";

console.log(typeof assert)
```

Feel to re-open if this isn't working still :)
