### ISSUE TITLE
isObject(global.console) in Node 14.17.0 is equal to FALSE

### ISSUE THREAD

**Issue by Adrosar** [chaijs/chai#1393]
**Case:**
```
isObject(global.console, '...'); // Node 14.17.0 => FALSE
isObject(global.console, '...'); // Node 12.19.0 => TRUE
```

**Cause:**
```
global.console.toString(); // Node 14.17.0 => '[object console]'
global.console.toString(); // Node 12.19.0 => '[object Object]'
```

**Comment by koddsson** [comment]
I think this is actually the correct behaviour. I'm assuming that the `console` variable is indeed not a object but a class and `node` has been updated to reflect that.

Feel free to re-open if you'd like to discuss this further.
