### ISSUE TITLE
Documentation website is down

### ISSUE THREAD

**Issue by sidwebworks** [chaijs/chai#1430]
https://chaijs.com/

Visiting this page shows something like a domain expiry issue.

**Comment by sidwebworks** [comment]
![image](https://user-images.githubusercontent.com/58144379/146369943-8c6e9d2c-1f60-47b3-bf00-fbafad1a60a5.png)

**Comment by keithamus** [comment]
Thanks for pointing this out @sidwebworks. We're already tracking this in https://github.com/chaijs/chaijs.github.io/issues/200 so I'll close this one out.
