### ISSUE TITLE
website seems to be down

### ISSUE THREAD

**Issue by lamrisr** [chaijs/chai#1431]
Hi,

I'm trying to view the documentation through the website http://chaijs.com/ but it seems that the domain name has expired this morning.

Did the documentation move somewhere else ?

Thanks for your help.

**Comment by keithamus** [comment]
Thanks for pointing this out @lamrisr. We're already tracking this in https://github.com/chaijs/chaijs.github.io/issues/200 so I'll close this one out.

(See also https://github.com/chaijs/chai/issues/1430)
