### ISSUE TITLE
Domain Expired

### ISSUE THREAD

**Issue by Maxattax97** [chaijs/chai#1432]
Here is a backup for those trying to get back home: https://web.archive.org/web/20211209012933/https://www.chaijs.com/

**Comment by bhubr** [comment]
Oops, just stumbled upon the same issue! Thanks.

**Comment by bhubr** [comment]
There's also a backup of the docs on GItHub Pages: <https://chaijs.github.io/>

**Comment by keithamus** [comment]
Thanks for notifying us @Maxattax97 & @bhubr. We're already tracking this in https://github.com/chaijs/chaijs.github.io/issues/200 so I'll close this one out.

(See also https://github.com/chaijs/chai/issues/1430, #1431)
