### ISSUE TITLE
chaijs.com expired

### ISSUE THREAD

**Issue by brittberwanger** [chaijs/chai#1433]
Thought you'd want to know

**Comment by nguyenmanhtri** [comment]
Can't believe nobody have looked into this.

**Comment by keithamus** [comment]
Thanks for notifying us @brittberwanger and @nguyenmanhtri. We're already tracking this in https://github.com/chaijs/chaijs.github.io/issues/200 so I'll close this one out.

(See also #1430, #1431, #1432)
