### ISSUE TITLE
Can't compare arrays with more than 70 elements

### ISSUE THREAD

**Issue by paolocattani** [chaijs/chai#1435]
I'm trying to compare deep two array with 75 elements and I found that if lenght > 70 except function return the below error.

```javascript
  it('should return all alerts ', async () => {
    sandbox.on(dataSources.clientNotificationAPI, 'listNotification', () => mockedCMNotification);
    const res = await graphql.executeOperation({ query, variables: { id: '123456' } });
    const n = 71;
    expect(res.data.getAlerts.slice(0, n)).to.eql(mockedCMResult.slice(0, n));
  });
```

Is there a know upper limit for comparing elements in array ? 

![image](https://user-images.githubusercontent.com/30072995/146416897-7c7021f9-d75f-431a-96e8-24daa2eb7cf0.png)

Using n = 70 it work just fine.

**Comment by keithamus** [comment]
Hey @paolocattani thanks for the issue.

The arrays are likely different. There is no bounds to equality pairing, but the threshold for displaying them is cut off at 75 characters (including the `[` and `]`). 

If you set `chai.config.truncateThreshold = 1000` it'll display more of them.

I'll close this as there isn't a bug with Chai here. If you disagree let me know and we can re-open and discuss further,
