### ISSUE TITLE
Domain Name Expired

### ISSUE THREAD

**Issue by shellscape** [chaijs/chai#1437]
Someone in the org forgot to renew chaijs.com https://news.ycombinator.com/item?id=29592529

**Comment by smbkr** [comment]
https://github.com/chaijs/chaijs.github.io/issues/200

**Comment by keithamus** [comment]
Thanks for notifying us @shellscape and @smbkr. We're already tracking this in https://github.com/chaijs/chaijs.github.io/issues/200 so I'll close this one out.

(See also #1430, #1431, #1432, #1433, #1434, #1436)
