### ISSUE TITLE
Fail on npm install because of the older node version

### ISSUE THREAD

**Issue by m-nonna** [chaijs/chai#1448]
4.x.x version of chai package has a dependency from ["deep-eql": "^3.0.1"](https://github.com/chaijs/chai/blob/v4.3.6/package.json#L45) which requires the following node versions, which is deprecated: `node: '0.10 || 0.12 || 4 || 5'`. Please see the full error below:
```
lerna ERR! execute Error: Command failed: npm install
lerna ERR! execute npm WARN EBADENGINE Unsupported engine {
lerna ERR! execute npm WARN EBADENGINE   package: 'karma@0.13.22',
lerna ERR! execute npm WARN EBADENGINE   required: { node: '0.10 || 0.12 || 4 || 5' },
lerna ERR! execute npm WARN EBADENGINE   current: { node: 'v16.13.1', npm: '8.1.2' }
lerna ERR! execute npm WARN EBADENGINE }
```
_I am reporting the bug in this repo because the newer version of `deep-eql` requires `"node": ">=6"`._
_Maybe upgrading `deep-eql` to a newer version would solve the problem._

**Comment by keithamus** [comment]
Hey @m-nonna thanks for the issue.

[deep-equal@3.0.1 requires Node >= 0.12 or greater](https://github.com/chaijs/deep-eql/blob/v3.0.1/package.json#L87). The full error you have pasted shows the warning is coming from the Karma package:

```
lerna ERR! execute npm WARN EBADENGINE   package: 'karma@0.13.22',
```

Also as this is a warning it should not fail the install. Perhaps there are more logs?

I'll close this for now as this isn't an error from chai from the logs you've given, and so there's nothing actionable for us here. If you feel like this is incorrect please provide logs indicating a failure with Chai, and/or a reduced test repository so we can confirm the issue.
