### ISSUE TITLE
npm install chai --save-dev failed

### ISSUE THREAD

**Issue by yjluo96** [chaijs/chai#1463]
npm install chai --save-dev failed with following message. Any thought?

ERR!  FetchError: request to http://npm-repo.devops.mhealth.tech/zip-stream/-/zip-stream-1.2.0.tgz failed, reason: connect ECONNREFUSED 10.250.3.46:80

**Comment by sukrosono** [comment]
maybe it is one of chai dep, but it is because of net problem, perhaps you have an unstable internet connection.
please try again a few times, and see what happens.

**Comment by keithamus** [comment]
>  http://npm-repo.devops.mhealth.tech/zip-stream/-/zip-stream-1.2.0.tgz 

This is not a URL in our package-lock, nor our dependency tree from what I can see. Perhaps this is an internal npm registry you're using? 

There's nothing actionable here for us to do. I'm going to close this one.
