### ISSUE TITLE
chai 4.3.5 does not build on skypack

### ISSUE THREAD

**Issue by tnguyen14** [chaijs/chai#1466]
Starting with version `4.3.5`, chai does not work with skypack https://cdn.skypack.dev/error/build:chai@v4.3.5-cdXlwD9j8XSpMk0e1GrE

I think this has to do with the change in esm exports, though I don't know enough about esm to figure out why. I'm sorry that I'm not able to articulate more intelligently why this issue is important, I don't know if others are using skypack. I just wonder if this is indicative of a deeper issue with ESM support.

**Comment by RebeccaStevens** [comment]
#1450

**Comment by jonkoops** [comment]
This [has been fixed](https://github.com/chaijs/chai/releases/tag/v5.0.0) in v5.

**Comment by 43081j** [comment]
indeed seems to work now as of 5.x, closing this
