### ISSUE TITLE
Release npm package with https://www.chaijs.com/chai.js ?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [chaijs/chai#1476]
https://www.chaijs.com/chai.js works perfectly in-browser with RequireJS. But, it doesn't seem to be provided as part of the npm package. If including it in https://www.npmjs.com/package/chai would be too much extra filesize bloat for most users, could we instead have it in its own package on npm? Say, a name similar to `chai-browser` but not already taken?

A couple of common workarounds exist today that have some inconvenient drawbacks:

* Using a `<script src="https://www.chaijs.com/chai.js"></script>` tag in the HTML file: does not work if the computer is effectively offline (e.g. on an airplane, in the subway, in shoddy rural networks)
* Downloading the file in a package setup script: nonstandard, and these setup scripts get difficult to manage the more there are

Having a specific npm package would make this situation much easier, please! ❤️ 

<details>
<summary>Fun fact: the file in node_modules logs an error in-browser</summary>

The version packaged in npm as `node_modules/chai/chai.js`, however, includes a `var nodeUtil = require('util');` that results in the following error in browsers:

```js
requirejs error: Error: Module name "util" has not been loaded yet for context: _. Use require([])
https://requirejs.org/docs/errors.html#notloaded
    at makeError (require.js:168:17)
    at Object.localRequire [as require] (require.js:1436:44)
    at requirejs (require.js:1797:24)
    at o (chai.js:1:489)
    at chai.js:1:680
    at chai.js:10595:20
    at chai.js:9923:66
    at 37.util (chai.js:9926:2)
    at o (chai.js:1:629)
    at chai.js:1:680
```

You can find a minimum reproduction here: https://github.com/JoshuaKGoldberg/repros/tree/chai-requirejs.

</details>

**Comment by atjn** [comment]
Chai 5.x should soon be released. It is an ES module, so it should work in any environment, allowing you to import the NPM package in a browser with no issues.

I chave previously used [`@esm-bundle/chai`](https://www.npmjs.com/package/@esm-bundle/chai) to achieve the same goal, but I believe you can just install the alpha version of Chai 5 now, and it should work.

**Comment by JoshuaKGoldberg** [comment]
Swell, thanks! I'll just close this out then.
