### ISSUE TITLE
Add "that" chain

### ISSUE THREAD

**Issue by dev-ardi** [chaijs/chai#1482]
This will allow `expect.that(foo).equals(bar);`
`equals` is kind of clunky without `that`, the only way to do the example while being proper english is `expect.(foo).to.equal(bar)`, which renders `equals` kind of useless for most purposes.

**Comment by BadIdeaException** [comment]
According to the [docs](https://www.chaijs.com/api/bdd/#method_equal), `equals` is just an alias for `equal`. So what's wrong with `expect(foo).to.equal(bar)`?

**Comment by dev-ardi** [comment]
I can't think of a case where I would use equals instead of to.equal
