### ISSUE TITLE
Test Promise without putting expect() in then() callback.

### ISSUE THREAD

**Issue by AlirezaEthDev** [chaijs/chai#1501]
As I read [Chai Http](https://www.chaijs.com/plugins/chai-http/), Whenever we need to test a promise by Chai Http, we should try ```expect()``` in a ```then()``` callback function, like this:

```
chai.request(app)
  .put('/user/me')
  .send({ password: '123', confirmPassword: '123' })
  .then(function (res) {
     expect(res).to.have.status(200);
  })
```

My questiona are:
1) Is it possible to try ```expect()``` for a promise in out of ```then()```, For example in another js file that requires this file?
2) How can I do that?

**Comment by keithamus** [comment]
Hey @AlirezaEthDev thanks for the issue. 

The best way to do this is with async/await:

```js
test('the thing', async () => {
  expect(
    await chai.request(app)
//  ^ note the "await"
      .send({ password: '123', confirmPassword: '123' })
  ).to.have.status(200)
})
```

If you can't use async await you could try chai-as-promised:

```js
chai.use(require('chai-as-promised'))
test('the thing', () => {
  return expect(
    chai.request(app)
    .send({ password: '123', confirmPassword: '123' })
  ).to.eventually.have.status(200)
  //   ^ note the "eventually" from chai-as-promised
})
```
