### ISSUE TITLE
[5.x.x] choose a test harness setup

### ISSUE THREAD

**Issue by 43081j** [chaijs/chai#1504]
Once we move away from just shipping a bundle, we need something capable of resolving bare specifiers in tests.

karma by itself can't do that, so we would have a few options:

### Option 1

Continue shipping a bundle.

If we do this, we can use karma still and consumers can use our bundle in a browser without themselves needing to deal with bare specifiers.

### Option 2

Use something like [karma-esm](https://github.com/blikblum/open-wc/blob/master/packages/karma-esm/README.md).

In theory, karma would then understand the bare specifiers and could run tests against the source rather than a bundle.

Consumers would need their own solution to the same problem (usually a bundler, or an import map).

### Option 3

Move to another test runner like [web-test-runner](https://github.com/modernweb-dev/web/tree/master/packages/test-runner) or, once they have a browser runner, vitest.

Importantly, whatever test runner we choose should _not_ use jsdom. it should launch a real browser.

Consumers would need their own solution to bare specifiers, just like in option 2.

**Comment by keithamus** [comment]
My vote is for us to move to `web-test-runner`, it's a great test runner and provides a minimal wrapper which allows us to test very close to "the metal" in browsers. I also think it would be useful to test _twice_ - once with esm and once with the `chai.js` bundle.

**Comment by 43081j** [comment]
i agree

and yes, if we intend on keeping the bundle even once we move to typescript, we'd have two test runs.

its possible one day you could drop the bundle entirely, but it does mean the consumer would have to handle the bare specifiers (via a bundler or import maps).

**Comment by keithamus** [comment]
> its possible one day you could drop the bundle entirely, but it does mean the consumer would have to handle the bare specifiers (via a bundler or import maps).

I won't say never :wink: but that does indeed seem unlikely for the foreseeable. By which I mean to say it won't harm us to invest in ensuring the bundled version is robust while import map usage is very low.

**Comment by jonkoops** [comment]
Just to add to this discussion, Karma is now [officially deprecated](https://github.com/karma-runner/karma#karma-is-deprecated-and-is-not-accepting-new-features-or-general-bug-fixes) making option number two less appealing.

**Comment by koddsson** [comment]
We moved to Web Test Runner in #1546!
