### ISSUE TITLE
`fail(message)` creates misleading test output

### ISSUE THREAD

**Issue by UlrichEckhardt** [chaijs/chai#1517]
When I call the `fail()` function with just a message:

    assert.fail('pre-dependency not fulfilled');

I get a misleading error message:

      pre-dependency not fulfilled
      + expected - actual

The second line, with the expected and actual, is what I find misleading here.

BTW: I've been using this with Mocha and have since migrated the code to use

     if (some condition) {
         this.skip('pre-dependency not fulfilled');
    }

which gives nicer output. In some cases, you really do want to call `fail()` though.

**Comment by koddsson** [comment]
I'm having trouble reproduce this. Can you create a minimal reproduction for this?

Here's what I did:

```js
 ~/temp/ cat index.js
import { assert } from "chai";

it("fail", function () {
  assert.fail("foo");
});
 ~/temp/ ./node_modules/.bin/mocha index.js


  1) fail

  0 passing (1ms)
  1 failing

  1) fail:
     AssertionError: foo
      at Context.<anonymous> (file:///Users/cr91ew/temp/index.js:4:10)
      at process.processImmediate (node:internal/timers:478:21)



 ~/temp/
```
