### ISSUE TITLE
chai.version field is incorrect

### ISSUE THREAD

**Issue by burnall** [chaijs/chai#1525]
The runtime Chai version is set to '4.3.3', though the current version is 4.3.7.
Please see https://github.com/chaijs/chai/blob/4.x.x/chai.js#L17C18-L17C18
It seems it should be updated with every release.

**Comment by voxpelli** [comment]
Same goes for the `5.x.x` branch, it also references `4.3.3`: https://github.com/chaijs/chai/blob/ad82f6229ee1073a9534cf0d8d9d39418ee9de12/lib/chai.js#L22

**Comment by keithamus** [comment]
PRs welcome 😄

**Comment by voxpelli** [comment]
@keithamus How is it meant to work? Normally when it’s needed I read it from the package.json rather than hard code it, would that work?

**Comment by keithamus** [comment]
We need to support browser environments which cannot read from the disk. Frankly I think we can just drop it from v5 as it serves little value.

**Comment by peanutenthusiast** [comment]
Hi @keithamus! Is this issue still open to PR's?

**Comment by keithamus** [comment]
Yes, please go right ahead.

**Comment by peanutenthusiast** [comment]
Great. Would you mind clarifying the expected change? Just to update to '4.3.7'? Or drop given the previous comment.

**Comment by koddsson** [comment]
We've removed chai version in #1550.
