### ISSUE TITLE
5.0.0-alpha.1 was published as "latest" npm dist-tag

### ISSUE THREAD

**Issue by AviVahl** [chaijs/chai#1531]
I think there was a mistake during publish, and the alpha version got the "latest" tag instead of "next".
See: https://www.npmjs.com/package/chai?activeTab=versions

FYI @koddsson

**Comment by keithamus** [comment]
Thanks for pointing this out! Fixed.

**Comment by koddsson** [comment]
Oh, shit. I'm not even sure how I did that. Thanks for the quick fix @keithamus <3
