### ISSUE TITLE
Fix get-func-name

### ISSUE THREAD

**Issue by Ep1s0de** [chaijs/chai#1538]
Hello
fix please get-func-name version
"get-func-name": "^2.0.0" to "get-func-name": "2.0.0" 

Thank you

**Comment by eladonline** [comment]
I think I have the same problem

![image](https://github.com/chaijs/chai/assets/20336964/77438b58-b118-48c0-9d35-05a2faf2818a)

**Comment by bugwelle** [comment]
get-func-name v2.0.2 was published to NPM, which should fix the issue. See https://github.com/chaijs/get-func-name/issues/41#issuecomment-1735248934

**Comment by keithamus** [comment]
This should now be fixed by `2.0.2`. Thanks.
