### ISSUE TITLE
Update dependency on `get-func-name` to at least 2.0.1 to fix CVE

### ISSUE THREAD

**Issue by jsynacek** [chaijs/chai#1539]
The current version string should be bumped to 2.0.1 to explicitly skip 2.0.0, which is susceptible to https://github.com/advisories/GHSA-4q6p-r6v2-jvc5.

**Comment by keithamus** [comment]
It uses the semver `^` which means unless your upstream project is pinning it to the susceptible version, 2.0.2 will be installed.

But feel free to make a PR changing the version in the package.json.

**Comment by keithamus** [comment]
fixed in https://github.com/chaijs/chai/commit/0ccd823cb3ee6a433156c4e23cc67de79d4f368d

**Comment by BreakBB** [comment]
Can you give an estimate when you want to release this change @keithamus ?

**Comment by keithamus** [comment]
@BreakBB https://github.com/chaijs/chai/releases/tag/v4.3.10

**Comment by BreakBB** [comment]
Absolutely awesome @keithamus 💪🏻 Insane response time 🥳
