### ISSUE TITLE
Add support for string interface over fluent interface

### ISSUE THREAD

**Issue by twolfson** [chaijs/chai#154]
This is an odd thought that I would like to discuss.

In theory, any of the chaining methods that normally occur after an `expect` or `should` can be encapsulated as a string and declared as an additional parameter to `expect`.

This would lead to instant cross-browser support down to IE6 (and beyond). I am not sure it is worth while to follow through with it. However, I think this is a good discussion to have.

```js
// Normal syntax
expect(hello).to.have.a.property('world');

// String syntax
expect(hello, 'to.have.a.property', 'world');
expect(hello, 'to have a property', 'world');

// Normal syntax
hello.should.have.a.property('world');

// String syntax
hello.should('have.a.property', 'world');
hello.should('have a property', 'world');
```

**Comment by meeber** [comment]
Closing this due to lack of traction.
