### ISSUE TITLE
Buffer is not recognized as an object

### ISSUE THREAD

**Issue by mirayashi** [chaijs/chai#1541]
Let the following test:

```js
const buf = Buffer.alloc(0)
expect(buf).to.be.an('object')
```

Expected result: the test should pass because `expect(typeof buf).to.equal('object')` does

Actual result: it fails

chai version 4.3.9

**Comment by keithamus** [comment]
`.to.be.an` effectively checks the `Symbol.toStringTag` of the object. If you want to assert on the `typeof`, then you should use `expect(typeof buf).to.equal('object')`.

I'll close this as it's not a bug within chai, it's working as intended.
