### ISSUE TITLE
[v5] `assert.isFunction()` fails with async function

### ISSUE THREAD

**Issue by ReDemoNBR** [chaijs/chai#1564]
The function `assert.isFunction` is failing on AsyncFunction on v5.0.0, while on v4.3.10 it was working

A simple scenario is the one below:
```javascript
describe("Scenario", ()=>{
    it("Should be a function", ()=>{
        async function foo() {
            console.log("Hello World");
        }
        assert.isFunction(foo); // fails on v5.0.0
    });
});
```

For now I changed my tests to use the JS builtin `typeof`, like:
```javascript
assert.strictEqual(typeof foo, "function");`
```

**Comment by koddsson** [comment]
Wow! Weird that we haven't hit this before. I don't even see a test for this so it makes sense we didn't catch this in the upgrade. I've created a failing test on a local branch and I'll see if I can make a fix today. I'll keep you posted.

**Comment by 43081j** [comment]
@koddsson its most likely because an async function's tag is `AsyncFunction`, not `Function`

presumably the library we used to use just treated them as one

**Comment by koddsson** [comment]
> @koddsson its most likely because an async function's tag is `AsyncFunction`, not `Function`
> 
> presumably the library we used to use just treated them as one

Yup! We refactored `type-detect` as part of v5. Now the question is if this functionality is actually correct and we should introduce `isAsyncFunction` to be more granular in assertions.

I put together a draft PR here and wrote down some thoughts: https://github.com/chaijs/chai/pull/1566

**Comment by asamuzaK** [comment]
There is a similar issue with `assert.typeOf(async ()=> {}, 'function')`.
