### ISSUE TITLE
SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by prashbattu** [chaijs/chai#1572]
we are using "chai": "^4.2.0" . Since last couple of days we are seeing following errors. Looks like old version has been updated with the breaking change.

13:26:11  SyntaxError: Invalid or unexpected token
13:26:11      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
13:26:12  npm ERR! Test failed.  See above for more details.

**Comment by 43081j** [comment]
i suspect this is the same problem as #1573 

i know this issue was made first but let's track it in the other since i happen to have replied there already

i'll see if i can fix it meanwhile
