### ISSUE TITLE
Documentation about loading chai in browser is wrong

### ISSUE THREAD

**Issue by cpcallen** [chaijs/chai#1624]
The documentation [on the chai website says](https://www.chaijs.com/guide/installation/):

> Include the chai browser build in your testing suite.
> 
>     <script src="chai.js" type="text/javascript"></script>
> 
> This will provide chai as a global object, or define it if you are using AMD.

and the documentation in [this repository's README says](https://github.com/chaijs/chai?tab=readme-ov-file#browsers):

> ### Browsers
> You can also use it within the browser; install via npm and use the `chai.js` file found within the download. For example:
> 
>     <script src="./node_modules/chai/chai.js"></script>

… but in both cases following this instruction will not set the `chai` global variable but instead will cause the browser to issue the following error message:

> SyntaxError: Unexpected token 'export' (at chai.js:3768:1)

It is unclear what the correct instructions for v5.0.0 and later should be.

One viable workaround is:

```JS
<script type="module">
  import * as chai from './node_modules/chai/chai.js';
  globalThis.chai = chai;
</script>
```

**Comment by 43081j** [comment]
good catch!

it should probably be something like this (depending on which interface):

```html
<script src="./node_modules/chai/register-should.js" type="module"></script>
```

if you want expect/assert, i'd recommend importing it rather than making it global

**Comment by programmersRuleTheWorld** [comment]
This repo is broken at ^5.0.
I'm trying to do tests on a Chrome extension and the incorrect documentation leaves me with an annoyed feeling about Chai.
I am making a product people will be paying for and I need to make sure it works correctly.
If I make a library for others to use for free, I will make sure it works and is updated or else what's the point?
Please fix this.

**Comment by 43081j** [comment]
Can you be clear about what exactly is broken? 

Did you try what I mentioned in my last comment? If that works for you, it is just a miss in docs and we can update

We could have done better with updating the docs when we released 5.x, given it is a fairly big breaking change (esm only). We are doing what we can to update but could do with clearer issues than telling us the repo is broken - so we can help out

**Comment by xdan** [comment]
> good catch!
> 
> it should probably be something like this (depending on which interface):
> 
> ```
> <script src="./node_modules/chai/register-should.js" type="module"></script>
> ```
> 
> if you want expect/assert, i'd recommend importing it rather than making it global

Hi, I tried it but another error appears in the browser.

```
Uncaught TypeError: Failed to resolve module specifier "assertion-error". Relative references must start with either "/", "./", or "../".
```
