### ISSUE TITLE
v4.5.0 was published to npm as latest verison

### ISSUE THREAD

**Issue by nwalters512** [chaijs/chai#1632]
I ran `yarn upgrade-interactive` just now and was surprised to see that v4.5.0 was published to npm as the `latest` version. I would have expected 5.1.1 to be the latest. Was this a mistake?

**Comment by 43081j** [comment]
you're right, seems to be a mistake!

will chase up the other maintainers on it and get it sorted

**Comment by koddsson** [comment]
My bad! It should be fixed now.
