### ISSUE TITLE
There is no release not nor change log for 5.0 version

### ISSUE THREAD

**Issue by SmashingQuasar** [chaijs/chai#1640]
# Description

Hello, I tried to find what changed between Chai 4.x and Chai 5.0 and I cannot find any change log for the 5.0 version. The first available change log for any 5.x version does not appear to list any breaking change, which makes me wonder if there is a missing change log or if semantic versioning is simply not being followed? I am a bit confused.

**Comment by 43081j** [comment]
This should cover it: 
https://github.com/chaijs/chai/releases/tag/v5.0.0

It's also on the website but is in an unusual order since we still released some fixes to 4.x

**Comment by SmashingQuasar** [comment]
Thanks, I couldn't find it on the website, sorry for the unnecessary issue! Also, thanks a lot for the work on 5.0, I really appreciate the changes and effort.
