### ISSUE TITLE
Docs issues galore with ESM vs CommonJS use

### ISSUE THREAD

**Issue by delfuego** [chaijs/chai#1654]
The primary docs site is replete with issues related to the use of Chai, specifically in terms of the differences between Chai 4 and Chai 5.

For example, there are still plenty of places that read that one should use:

```
import chai from 'chai';
```

when the Chai 5 ESM-only version doesn't have a default exported object, so that fails. It took me a while to figure out that everything is now a named export, so if I want to use a plugin, I have to use:

```
import { use, expect } from 'chai';
```

and then change all my `chai.use()` calls to just use that newly-exported `use` method.

Is there a Chai 5/ESM-only doc page that helps folks make these changes?

**Comment by boly38** [comment]
related file example [guides/using-chai-with-esm-and-plugins](https://github.com/chaijs/chaijs.github.io/blob/5764f2aefcf71fc44e548262db0453345ef9b7f6/_guides/using-chai-with-esm-and-plugins.md?plain=1#L4)
