### ISSUE TITLE
Chai fails when testing an Error

### ISSUE THREAD

**Issue by simonrenoult** [chaijs/chai#207]
I am currently testing my app with `chai`. I would like to test an error thrown by one of my method. To do that, I've written this test : 

```
expect ( place.updateAddress ( [] ) ).to.throw ( TypeError );
```

And here is the method :

```
Place.prototype.updateAddress = function ( address ) {
    var self = this;

    if ( ! utils.type.isObject ( address ) ) {
        throw new TypeError (
            'Expect the parameter to be a JSON Object, ' +
            $.type ( address ) + ' provided.'
        );
    }

    for ( var key in address ) if ( address.hasOwnProperty ( key ) ) {
        self.attributes.address[key] = address[key];
    }

    return self;
};
```

The problem is that `chai` fails on the test because the method throws a... `TypeError`. Which should not fail because it is the expected behavior in this test. Here is the statement :

![Chai statement](http://i.stack.imgur.com/hA7A1.png)

I have bypassed the problem with the following test :

```
    try {
        place.updateAddress ( [] );
    } catch ( err ) {
        expect ( err ).to.be.an.instanceof ( TypeError );
    }
```

But I'd prefer avoiding `try... catch` statements in my tests as `chai` provides built-in methods like `throw`.

Any idea/suggestion ?

**Comment by DotHide** [comment]
Awesome! Also resolved my question~
