### ISSUE TITLE
Provide friendly error message when deep equality check fails because of types

### ISSUE THREAD

**Issue by OliverJAsh** [chaijs/chai#246]
``` js
function Foo() {}
var foo = new Foo();
expect(foo).to.eql({});
```

This fails because the objects are not the same type, but the error message doesn’t tell me this:

``` js
+ expected - actual
```

**Comment by blimmer** [comment]
`chai.config.truncateThreshold` is very helpful! So nice to see what's different in a `deep.equals` visually instead of debugging in the browser.

**Comment by machineghost** [comment]
It's very easy to miss `chai.config.truncateThreshold` (I had to come here to find out it even existed), but now that I do know about it it feels like the most important thing about Chai that no one ever told me.

Is there any way `chai.config.truncateThreshold` could default to 0?  I would imagine (based on tests I've seen) that 99% of cases don't involve output that needs truncation.

If that's not possible, could you maybe consider trying to surface information about this oh-so-wonderful property?  For instance ...

* when test output gets truncated the output could say something like "output truncated per chai.config.truncateThreshold"
* in the documentation for `eql`/`deep.equal` you could mention that output will be truncated based on `chai.config.truncateThreshold`
* add some sort of "Chai Gotchas" to the documentation and mention `chai.config.truncateThreshold`

**Comment by keithamus** [comment]
Ideally truncatethreshold should be deprecated in favour of doing the sensible thing instead. I'd like to not bring it more to the forefront, and instead fix underlying issues

**Comment by keithamus** [comment]
Thank you for your time in reporting this. We're going to put a lot of work into error messaging for chai 5, so I'm going to close this, because there is nothing for us to do right now, but rest assured this has been noted, and we'll be making sure to keep this in mind in the future.
