### ISSUE TITLE
Allow multiple expect() calls within one test

### ISSUE THREAD

**Issue by leifhanack** [chaijs/chai#259]
Hi there, 

are there any plans to support multiple expects in one test (similar to what jasmine offers)? 

When:

```
    it('foo', function () {
      expect(3==2).to.be.true;
      expect(4==3).to.be.true;
      expect(4==2).to.be.true;
    });
```

Then:
The test run should results in s.th. like:

```
AssertionError: expected false to be true
   ...
AssertionError: expected false to be true
   ...
AssertionError: expected false to be true
   ...
```

instead of just one AssertionError.

Regards, Leif

**Comment by djom20** [comment]
Usually I use the & (and) to concatenate the expects that is only one.

expect(3==2).to.be.true &&
      expect(4==3).to.be.true &&
      expect(4==2).to.be.true;

Also you can use the || (or) too. I hope this help you.

**Comment by tobirohrer** [comment]
@djom20 When I run the following Test in Jest 24.8, the test **passes**
```
expect(3==2).toBe(false) &&
expect(4==3).toBe (true) &&
expect(4==2).toBe (true);
```
it seems, that only the first expect is taken into account... In my case, I just use multiple expects, like:
```
 expect(3==2).toBe(false)
expect(4==3).toBe (true)
expect(4==2).toBe (true);
```

**Comment by dakotacookenmaster** [comment]
> 
> 
> Usually I use the & (and) to concatenate the expects that is only one.
> 
> expect(3==2).to.be.true &&
> expect(4==3).to.be.true &&
> expect(4==2).to.be.true;
> 
> Also you can use the || (or) too. I hope this help you.

This was very helpful! I can't believe I didn't think of something so simple. Thank you so much!
