### ISSUE TITLE
Allowing .keys() to accept Object

### ISSUE THREAD

**Issue by thejameskyle** [chaijs/chai#265]
```js
describe('myFunction', function() {
  beforeEach(function() {
    this.bar = { baz: stubFn, tah: stubFn };
    this.foo = myFunction(this.bar);
    // >> { baz: [{ callback: stubFn, context: this.bar }], tah: [{ callback: stubFn, context: this.bar }] }
  });

  it('should work with an array', function() {
    expect(this.foo).to.have.keys(Object.keys(this.bar));
  });

  // vs.

  it('should work with an object', function() {
    expect(this.foo).to.have.keys(this.bar);
  });
});
```

**Comment by gregglind** [comment]
+1 on allowing/extending `.keys (object)`, using Object.keys ().

**Comment by keithamus** [comment]
Yeah, after taking the time to re-read this I am kind of in favour of `.keys()` being able to detect objects and extract the `Object.keys()` out from them; so the new syntax would just be `.contain.keys(object);`. 

If anyone wants to take a stab at a PR; the keys assertion is [L1004-L1074 of assertions.js](https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L1004-L1074), but the logic around extracting keys from the argument set is [L1009-1011](https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L1009-L1011) - it should be a simple case of checking to make sure its only one argument, and that argument is an object - then calling `Object.keys()` on it. Probably the majority of the work is adding extra tests, [(L571-669 of test/expect.js)](https://github.com/chaijs/chai/blob/master/test/expect.js#L571-L669) and also extending the documentation appropriately [(L970-1002 of assertions.js)](https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L970-L1002)

**Comment by gregglind** [comment]
Notes:
- testing was a lot of "cut and paste*.   For the future with 'alias' like tests... maybe easier to test that the return / do the same assertion?  (Unless that is too 'internal')
- Thinking about this feature, I wonder if we are giving people a footgun here.  "Normal" objects will work fine, in as much that on simple POJO's `Object.keys(pojo)` does the right thing.  Are people going to try to pass in constructed objects, or one with non-enumerable properties?
- "object, but not array" testing in JS continues to be stupid.

**Comment by keithamus** [comment]
- I think keeping the tests as simple as possible is a good idea. While they may be repetitive, they are easy to read and don't involve "dynamic logic" (for want of a better phrase)
 - I think this is as much of a footgun as passing objects to any assertion. We could add in detection to ensure a POJO is being passed in - but I think leaving it down to the dev is fine. Note that if `keys({})` would throw because it does a [check for `keys.length`](https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L1013)
 - See comments in PR about this.
