### ISSUE TITLE
Allow notStrictEqual for BDD style tests (expect)

### ISSUE THREAD

**Issue by mansona** [chaijs/chai#280]
From the documentation it doesn't seem like the following behaviour: 

```
assert.notStrictEqual(3, '3', 'no coercion for strict equality');
```

is available for bdd style tests. 

The only equality tests in the "expect" part of the library is this: 

```
expect(3).to.equal('3');
```

but that will fail because it uses `===` for the comparison. 

Is there any way to get the same behaviour as `notStrictEqual` for expect?

**Comment by wearhere** [comment]
The absence of this API also prevents comparing strings created using the `new` operator:

```js
expect('hi').to.equal(new String('hi')) // will fail
```

(our use case for using the `new` operator with Strings is that we're actually comparing instances of a string subclass).

Also, if Chai wants to claim that loose equality checking is bad practice, that makes sense to me—though I would find it disappointing, as Chai is very flexible in most other respects—but it doesn't make sense to me that it's exposed by one of Chai's APIs and not another.

**Comment by shvaikalesh** [comment]
Hey @wearhere.

If you want to avoid casting string subclass to primitive on every assertion, I believe may want to write a plugin that adds a getter like `.loose` that sets a flag on an assertion, and overwrite `equal` to respect that flag.

**Comment by mansona** [comment]
@shvaikalesh I particularly like that idea of adding a `.loose` differentiator API 👍 that would be exactly what would have solved my problem.

**Comment by wearhere** [comment]
@shvaikalesh I like that idea, though as far as it becoming a plugin I'll say that it not being built into core is a hindrance coming from Jasmine, which offers `toBe` (strict) vs. `toEqual` (loose) out of the box.

**Comment by nadrane** [comment]
I made my own plugin that supports loose equality for my use cases. At the moment it always deeply compares the inputs, and it only supports arrays and other non-object primitives. I can make it more robust and put it on NPM if anyone feels it would be useful to them

**Comment by mansona** [comment]
@nadrane why not contribute it as a PR to chai?
