### ISSUE TITLE
Change assertion subject when using ownProperty

### ISSUE THREAD

**Issue by lo1tuma** [chaijs/chai#281]
It would be nice if `ownProperty` changes the assertion subject in the same way as `property` does.

So you can do the following expectation:
```js
expect(obj).to.have.ownProperty('foo')
  .that.is.a('string');
```

**Comment by rhbecker** [comment]
+1 ... and while on the topic, why not also support an optional second `value` argument?

**Comment by keithamus** [comment]
Yup. You are all right.  We should:

[ ] - Alter `flag('object')` to allow chaining, as per @lo1tuma's suggestion
[ ] - Allow a second `value` argument, as per @rhbecker's suggestion
[ ] - PR these both against the `3.x.x` branch, as it will be a breaking change.

**Comment by lucasfcosta** [comment]
I'm planning on sending a PR for this today.
If someone was already working on this please let me know :smiley:

**Comment by brutalcrozt** [comment]
am i correct that this should be close since 641 have been merged?

**Comment by keithamus** [comment]
#641 was merged into the `4.x.x` branch so this one wouldn't be closed by that. I'll close it manually as there is nothing more that needs doing for this issue - we just need to cut a `4.0.0` release soon to release it.

**Comment by Noitidart** [comment]
Is it possible to make `.property` not change the target subject?
