### ISSUE TITLE
Can I refactor chai messages?

### ISSUE THREAD

**Issue by svallory** [chaijs/chai#286]
As of now Chai error messages are embedded into code and don't follow a strict rule. Take, for example, the [`assertAbove`](https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L463) method...

when flag `doLength` is true, Chai uses

     'expected #{this} to have a length above #{exp} but got #{act}'

otherwise it uses 

    'expected #{this} to be above ' + n

This makes it harder to improve messages by overwriting the `getMessages` method, which was my approach to modify the message before it was sent away.

My idea is to extract *all* messages to a module which would return a hash so messages would be referenced by a string id. Something like...

_lib/chai/core/messages.js_

```js
module.exports = {
    above: "expected #{this} to be above #{exp}",
    aboveLength: "expected #{this} to have a length above #{exp} but got #{act}"
}
```

This would allow plugins to translate, improve, add color or even replace all messages to the liking of the author.

I'm volunteering to code it and make a pull request. Should I proceed?

**Comment by keithamus** [comment]
Hey @svallory, just checking in to see if you made any progress with this?

**Comment by svallory** [comment]
@keithamus and guys sorry for The reeeeealy huge delay on this. But I come bearing good news! I've got some time to work on it this week. I'll make a PR as soon as I get it to pass all the tests (hopefully today!). I have 18 to go.

**Comment by keithamus** [comment]
@svallory really looking forward to this. Can't wait :smile:

**Comment by keithamus** [comment]
Closing this alongside #393:

> Hey @svallory thanks for all of your hard work on this, it has really helped us with where we're headed with chai and your work was amazing. I think I'm going to close this for now though, as it hasn't had much activity recently, and if we go in the direction that #585 is generally pointing in, we may have interesting ways to auto generate messages from assertions.

> We may come back to this at some point in the future, if and when we do I'll re-open this and let you know @svallory 😄.
