### ISSUE TITLE
 The online test suite does not pass in Firefox

### ISSUE THREAD

**Issue by julienw** [chaijs/chai#301]
* configuration > includeStack is true
```
AssertionError: should have internal stack trace in error message: expected '' to include 'assertEqual'
```

Actually I think Firefox changed things in how the error stack is handled.
For example https://bugzilla.mozilla.org/show_bug.cgi?id=355430 has been fixed (but it's in Firefox 31, whereas the issue seems to happen since Firefox 28 like you said in https://github.com/chaijs/chai/issues/299#issuecomment-61968360)

**Comment by dmose** [comment]
So on master, if I type "make test-firefox", it seems to pass all the tests.  @julienw, are you still seeing this, or am I misunderstanding how to reproduce this...

**Comment by julienw** [comment]
The STR was opening http://chaijs.com/api/test/ in Firefox. But right now the test suite is not even starting :/

**Comment by keithamus** [comment]
Yes - the test suite got forgotten in the migration to the gh-pages website. If you're familiar with Jekyll, and the Chai tests, please feel free to make a PR. 

I'm going to close this in favour of continuing the conversation at https://github.com/chaijs/chai-docs/issues/122

**Comment by julienw** [comment]
I'm not familiar with Jekyll at all, sorry :(

**Comment by keithamus** [comment]
Don't worry, we have the issue at chaijs/chai-docs#122 now, which anyone can pick up and send a PR. If you fancy trying, the docs for Jekyll are available at https://jekyllrb.com/. To run the Chai-Docs site, just clone it and run `make install` and then `make docs-server`.
