### ISSUE TITLE
Current doc and changelog no longer correspond to actual behaviour (noop functions)

### ISSUE THREAD

**Issue by abenhamdine** [chaijs/chai#329]
Hello guys and kudos for the excellent work done here.

Since the revert (unfortunately, but necessary...) of commit c448e1de7c2e3a5af21bc9b203536f3e1db81786, docs and changelog are no longer correct.

E.g., doc for .ok still mention : 

Can also be used as a function, which prevents some linter errors.

    expect('everthing').to.be.ok();

It can be confusing especially for a newcomer to chai.

I think you should revert also commits bbd3aafbe59e78415f3782f3f810d4bf83c3c8c4 and also correct the changelog of 1.10 until a working solution is found in future.

**Comment by keithamus** [comment]
Closing this as we have a tracking issue for v2.0.0 (https://github.com/chaijs/chai/pull/364). If you disagree with closing this feel free to comment and I'll open it back up.
