### ISSUE TITLE
Add an assertion that checks how much a value has changed.

### ISSUE THREAD

**Issue by oveddan** [chaijs/chai#330]
This would be used to check if, when something is invoked, something else is changed by x.

For example:

```javascript
var someArray = [1, 2, 3];

expect(function(){
  someArray.pop();
}).to.change(someArray, 'length').by(-1);
```

I'd be glad to take a stab at this.

**Comment by lucasfcosta** [comment]
This one is done.
Implemented at #333 and #621.

More discussion about this was done at #339 too.
