### ISSUE TITLE
Add an assertion that makes sure all items in an array satisfy a condition

### ISSUE THREAD

**Issue by oveddan** [chaijs/chai#331]
For example:

``` javascript
   var objects = [{a: '5', b: 'c'}, new Object(), {}] 
   expect(objects).all.to.be.an('object');
```

**Comment by HoldYourWaffle** [comment]
Is there a proper solution for this yet?
It looks like `chai-things` isn't maintained anymore (https://github.com/chaijs/chai-things/issues/44, https://github.com/chaijs/chai-things/issues/58), although it was pulled into the chaijs org.
