### ISSUE TITLE
Publish release strategy

### ISSUE THREAD

**Issue by keithamus** [chaijs/chai#337]
We should publicise the steps to release a version of chai, so that other maintainers can easily release new versions. This issue is mostly a todo item for @logicalparadox :smile:

**Comment by joshperry** [comment]
Is @logicalparadox the only person that knows how to do this? Can we just start hashing out the steps that is involved in a release?

**Comment by keithamus** [comment]
We can indeed start piecing it together ourselves. It is mostly assigned to @logicalparadox as he has the canon procedure in his head. I've mostly sussed it out: do a `make`, bump the version number, add notes in History.md and release notes, update the contributors in the readme, commit it all including the recompiled `./chai.js`, run npm publish. When I next get a good block of time to sit down and hash it through I plan to get something together, unless @logicalparadox beats me to it.

**Comment by logicalparadox** [comment]
Sorry this took so long... I got tied up on... life. Anyway, this should also permit anyone with push repo rights the ability to tag releases on npm via travis hooks.

@keithamus You have been a fantastic force for progress in recent months and I am extremely grateful for all the time and effort you have put forth. Please make sure you list yourself as a core contributor where ever applicable. And, of course, publish releases whenever you see fit.

**Comment by keithamus** [comment]
Closing this as @logicalparadox has completed the work needed.

Thanks for the kind works @logicalparadox!

**Comment by logicalparadox** [comment]
:)
