### ISSUE TITLE
Assert an increase/decrease by an amount (delta)

### ISSUE THREAD

**Issue by keithamus** [chaijs/chai#339]
As per #333 and #330, we should be able to assert on the delta of a `.changed`/`.increased`/`.decreased`.

So far (in #333) the proposed syntaxes are:

```js
foo.should.change('bar').by(5);
foo.should.increase('bar').by(5);
foo.should.decrease('bar').by(5);
```
or
```js
foo.should.change('bar', 5);
foo.should.increase('bar', 5);
foo.should.decrease('bar', 5);
```

/cc @oveddan @cmpolis @logicalparadox

**Comment by cjqed** [comment]
The former is closer to the rest of the syntax in chai. In my opinion we should always aim for tests to be human readable, and the 5 in the second set just seem like magic numbers.

**Comment by timruffles** [comment]
both @matthijsgroen's [chai-changes](https://github.com/matthijsgroen/chai-changes) and  [chai-change](https://github.com/timruffles/chai-change) (disclaimer: mine) plugins support this, along with async assertions (promises in Matthijs' and callbacks in mine).

I guess the change of maintainer explains why the changes feature didn't land in 2013 in #218, I'm not bitter ;)

**Comment by keithamus** [comment]
Hey @timruffles, sorry about the overlap - wasn't aware of either of these plugins at the time of merging the original PR. As you ant @matthijsgroen both have plugins which cater for this - do you have any input on this issue? Even if that input is "don't do it" :smile:.

**Comment by timruffles** [comment]
I really like the `by` feature! It's in both the linked plugins.

If I was to make a suggestion, it's that the current implementation in core doesn't support async use-cases, or functional style:

e.g the below - which is bread and butter node webdev - isn't possible in the current implementation:

```javascript
it('creates a version', function(done) {

	assert.change(function(cb) {
		create({
			type: "plan",
			name: "v2",
		}, cb)
	}, function(cb) {
			Version.count({}, cb);
	}, { 
		callback: done, by: 1,
	});
		
});

```

**Comment by matthijsgroen** [comment]
https://github.com/matthijsgroen/chai-changes#changebydelta

The change library supports async, automatically if the return value of the `when(function() { })` is a promise.

**Comment by lucasfcosta** [comment]
+1 for the `by` feature.
I really think having `by` improves readability, which is one of the main things that makes Chai awesome.

Also, I can't think of a better way to implement it other than having an assertion just for it.
Even if we have it just because of `changes`, `increases` and `decreases` I still think this is a price worth paying.

**Comment by keithamus** [comment]
Well, as I've said a few times before - I'm here as a steward, not a dictator. So if people want `by` then I can't argue.

PRs welcome :smile:

**Comment by lucasfcosta** [comment]
Hi, @keithamus, how are you?
Well, I think #607 is done and ready to be merged.
I will be pleased to work on this as soon as the `change` related changes are ready for a merge. Can I?

**Comment by keithamus** [comment]
Feel free to make a PR for this @lucasfcosta. You're not bothering me, its amazing to have such a good contributor eager to contribute more!

**Comment by lucasfcosta** [comment]
I think we can close this one, @keithamus !
And thanks for the feedback you gave me on the PR #621
