### ISSUE TITLE
expect does not wait for a promise to resolve

### ISSUE THREAD

**Issue by gajus** [chaijs/chai#340]
This is not documented anywhere in Chai, though it feels intuitive that if `expect` function returns a promise, it should wait until that promise is resolved.

```js
expect(function () {
    return new Promise(function () {
        setTimeout(function () {
            throw new Error('Foo.');
        });
    });
}).to.throw(Error);
```

**Comment by logicalparadox** [comment]
You should look into [chai-as-promised](https://github.com/domenic/chai-as-promised/). I think you will find it has what you need.

**Comment by gajus** [comment]
No, I have no use case for chai-as-promised. I am very happy with writing my test cases in this way:

```js
it('it attempts to load information about YourAccount', function () {
    let youtAccount = nock('https://www.netflix.com/')
        .get('/YourAccount')
        .reply(200, '<p></p>');

    return netflix
        .user()
        .then(function () {
            expect(youtAccount.isDone()).to.be.true();
        });
});
it('returns false if it cannot retrieve user\'s account details', function () {
    nock('https://www.netflix.com/')
        .get('/YourAccount')
        .reply(200, '<p></p>');

    return netflix
        .user()
        .then(function (user) {
            expect(user).to.be.false();
        });
});
```

chai-as-promised affects behaviour of the entire chai library, e.g. `expect(true).to.be.true()` is not going to work, because chai-as-promised expects it to be a property `expect(true).to.be.true` (, which is incredibly stupid because you end up with a bunch of undefined typos and false positive tests, such as `expect(true).to.be.trua`)

**Comment by logicalparadox** [comment]
Chai's core library is synchronous only; chai-as-promised adds support for Promises. We have no plans to include that functionality in core.

There is also [dirty-chai](https://www.npmjs.com/package/dirty-chai) which assists in your gripes about property based assertions.

**Comment by keithamus** [comment]
@gajus `.to.be.true()` is getting ripped out of the next chai release because it causes problems with the old style `.to.be.true`. In the future you may either use `.to.equal(true)` or, as @logicalparadox suggests, dirty-chai will opt you back into the function style. dirty-chai will work on top of chai as promised too, so you can have the best of both worlds :smile:
