### ISSUE TITLE
`.and` like syntax for Assert interface

### ISSUE THREAD

**Issue by SystemParadox** [chaijs/chai#342]
When using assert.throws, it is only possible to check the type and message of the error.

It would be nice if it was also possible to use this to make assertions about custom properties on the error - ideally by returning the error object.

For example, we use a ValidationError object with a `validation` property to return errors for multiple fields. I would like to be able to do something like this:

```js
var e = assert.throws(function () {
    validateFoo(data);
}, 'Validation Failed');
assert.deepEqual(e.validation, ...);
```

Otherwise, it seems that the only way to achieve this is to do the following:

```js
try {
    validateFoo(data);
    assert(false, 'Expected exception');
} catch (e) {
    assert.equal(e.message, 'Validation Failed');
    assert.deepEqual(e.validation, ...);
}
```

I really don't like having to assert(false) to say that an exception was expected. It feels very wrong to me.

Any other thoughts on this would be much appreciated :)

Thanks!

**Comment by keithamus** [comment]
Hey @SystemParadox. Good news is that we already do something like this in the `expect` and `should` syntaxes, so you can do something like the following:

```js
expect(function () {
    validateFoo(data);
}).to.throw('Validation Failed').and.deepEqual(e.validation, ...);
function () {
    validateFoo(data)
}.should.throw('Validation Failed').and.deepEqual(e.validation, ...);
```

The bad news is there is currently no way to do the same using the `assert` api.

We could return `flag(this, 'obj')` after each assertion, which would allow you to use the exact syntax you're suggesting. Effectively we'd need to go through every assert method inside [lib/chai/interface/assert.js](https://github.com/chaijs/chai/blob/master/lib/chai/interface/assert.js) and make it return the object - a bit laborious but not unachievable. A PR is welcome.

**Comment by SystemParadox** [comment]
I must have been doing something wrong earlier because this appears to work already!

```
var e = assert.throws(function () {
    validateFoo(data);
}, 'Validation Failed');
assert.deepEqual(e.validation, ...);
```

**Comment by keithamus** [comment]
@SystemParadox I'm quite sure this doesn't work - are you sure `e` isn't set to a value from earlier?

**Comment by keithamus** [comment]
Yes! You're quite right! I don't know how I missed that :blush:

**Comment by keithamus** [comment]
Just for posterity - it only works for `.throws` - the line is here: https://github.com/chaijs/chai/blob/master/lib/chai/interface/assert.js#L960
