### ISSUE TITLE
Local helpers

### ISSUE THREAD

**Issue by KidkArolis** [chaijs/chai#343]
Is there any way to addMethod or addProperty and then remove it in `after()`?
I want to add some helpers that are relevant to some specific test (creating a dsl basically), but I don't want to pollute the global chai assertion registry.

**Comment by keithamus** [comment]
Interesting idea @KidkArolis. Sorry I didn't see this issue earlier. 

You'd have to manually remove the property in the `after()` by using something like:

```js
delete chai.Assertion.prototype.myObjName
```

You can see in the [`addProperty` definition](https://github.com/chaijs/chai/blob/master/lib/chai/utils/addProperty.js#L32-L40) all that happens is we add the property to the assertion prototype (`chai.Assertion.prototype`), so simply deleting it should work :smile:
