### ISSUE TITLE
Suggestion: Add a "which" chaining word to be interchangeable with "that"

### ISSUE THREAD

**Issue by thomaspaulin** [chaijs/chai#347]
I find the "that" chaining word can be somewhat unintuitive at times and find myself trying to use "which" instead of "that".

An example being: `...with.property('length').which.equals(10)` seems more intuitive to me than `...with.property('length').that.equals(10)`

Obviously both make sense but I thought I'd mention this given the aim of chaining words, and because there might be others who feel the same.

**Comment by keithamus** [comment]
Good idea @thomaspaulin! I agree that `which` could sometimes be more readable than `that. Luckily the chains are all found it one place, and so it should be really easy to update. If you'd like to send a PR that'd be swell, plus you'd get the credit for it in our [Hall Of Fame](https://github.com/chaijs/chai/graphs/contributors).

You'd just need to add `'which'` to the [array of chains (L40-42 of assertions.js)](https://github.com/chaijs/chai/blob/5fc486b5733d67a02ead53de6557741d4c57c276/lib/chai/core/assertions.js#L40-L43) and also update the [docs to include it (L21-34 of assertions.js)](https://github.com/chaijs/chai/blob/5fc486b5733d67a02ead53de6557741d4c57c276/lib/chai/core/assertions.js#L21-L34). Then if you're feeling thorough, just chuck in a simple [test that uses it (L671-684 tests some chains)](https://github.com/chaijs/chai/blob/5fc486b5733d67a02ead53de6557741d4c57c276/test/expect.js#L671-L684).

**Comment by keithamus** [comment]
Hey @thomaspaulin - @toastynerd made the fix which has been merged. A release will happen soon so this will be in the next version of chai :smile:
