### ISSUE TITLE
Add should.fail() to all styles

### ISSUE THREAD

**Issue by Soviut** [chaijs/chai#350]
There's already an `assert.fail('message')` for forcing a test to fail and the ShouldJS library has a `.fail()` method as well. It would seem like adding a `.fail(message)` to all styles would be useful to avoid additional references being needed for this feature.

**Comment by keithamus** [comment]
Sounds like a great idea @Soviut!

The `assert.fail` function appears in [assert.js L44-64](https://github.com/chaijs/chai/blob/master/lib/chai/interface/assert.js#L44-L64), it'd effectively need duplicating somewhere around [should.js L41-73](https://github.com/chaijs/chai/blob/master/lib/chai/interface/should.js#L41-L73) and maybe chucking it [expect.js](https://github.com/chaijs/chai/blob/master/lib/chai/interface/expect.js) for good measure wouldn't hurt.

PR's welcome, as always you get a sweet place on our [hall of fame](https://github.com/chaijs/chai/graphs/contributors) and an internet high five :hand:

**Comment by Soviut** [comment]
Thanks, yeah, I've also found where `fail()` is tested however I couldn't find any contribution documentation and can't get the test suite to run. Does any exist yet?

**Comment by keithamus** [comment]
Sorry @Soviut - not just yet. If you're running on Linux or Mac and have `make` installed (you probably do), you can run `make test` and it'll run the tests for you. Otherwise - we use Mocha (for Node tests) and Karma (for browser tests). Here are the respective lines to run tests:

```bash
mocha --require ./test/bootstrap # node tests
karma start --single-run --browsers PhantomJS # browser tests
```

**Comment by Soviut** [comment]
Thanks. This would be good to add to package.json so that `npm test` will issue those same commands. I'll create a separate ticket for this and probably just add it myself as a separate PR.

**Comment by keithamus** [comment]
Sounds like a swell idea @Soviut! I'm really looking forward to seeing your PRs :smile:

**Comment by Soviut** [comment]
Cross linked https://github.com/chaijs/chai/issues/352

**Comment by Soviut** [comment]
@keithamus I'm trying to decide what arguments are necessary for the `.fail()` method on other interfaces. Assert is `(actual, expected, message, operator)` do we want to bother replicating this or simply accept a failure message?

**Comment by Soviut** [comment]
My PR was accepted https://github.com/chaijs/chai/pull/356
