### ISSUE TITLE
site seems to be down

### ISSUE THREAD

**Issue by oriSomething** [chaijs/chai#351]
![chaijs](https://cloud.githubusercontent.com/assets/2685242/5917815/1ee5a842-a62a-11e4-9b11-3f3bcac41916.png)

**Comment by keithamus** [comment]
The website did seem like it was down for a while. It's back up now though :smile:. Let me know if you run into more issues @oriSomething

**Comment by Anonyfox** [comment]
Seems down again.

**Comment by logicalparadox** [comment]
Back up!

**Comment by bryansray** [comment]
Seems down again?
