### ISSUE TITLE
npm test doesn't work

### ISSUE THREAD

**Issue by Soviut** [chaijs/chai#352]
`make test` is needed to run the test suite. Without make, on Windows, for example, the following is required to manually test.
```bash
mocha --require ./test/bootstrap
karma start --single-run --browsers PhantomJS
```
Since we already have a package.json these commands should be added to the "scripts/test" section.
```json
  "scripts": {
    "test": "mocha --require ./test/bootstrap"
  },
```
So that `npm test` will run the tests on any platform using npm.

**Comment by keithamus** [comment]
Just to mention - mocha and karma tests (and actually saucelabs tests) are all part of the full test suite and should be runnable as part of `npm test`, so I'd recommend the package.json be expanded to include all; perhaps something like:

```json
  "scripts": {
    "test": "make test",
    "test-node": "make test-node",
    "test-phantom": "make test-phantom",
    "test-sauce": "make test-sauce"
  },
```

**Comment by Soviut** [comment]
@keithamus Sounds good. I'll have to familiarize myself with saucelabs though.

**Comment by Soviut** [comment]
I ran into an issue with Karma expecting a build.js file that it couldn't find.

**Comment by keithamus** [comment]
Hmm. Looks as though perhaps the Karma tests perhaps haven't survived refactoring. Don't worry about them for now, just get what you can working :smile:

**Comment by qbolec** [comment]
When running `npm install` followed by `npm test` on Windows against a fresh clone of the repo, I've got an error that phantomjs module is missing.
By running `npm install phantomjs` the problem was resolved and now `npm test` passes.
My question is then:
Should the "phatnomjs" be listed as devDependency of chai?
I see that there is "karma-phantomjs-launcher" listed in devDepencencies, but apparently this does not result in phantomjs being installed.

**Comment by lucasfcosta** [comment]
I've just installed chai on Windows yesterday and it worked out fine (I just needed to install GNU Make for cygwin).

`make` was the real problem for me

**Comment by meeber** [comment]
Is this something we still want to pursue?

**Comment by keithamus** [comment]
Perhaps we'll just close this one, as I think big picture - makefiles will probably be phased out for npm scripts as our build tools are simple enough to be bundled into the package.json, and are being done so for the modules we have.
