### ISSUE TITLE
JSDoc coverage for Should and Expect

### ISSUE THREAD

**Issue by Soviut** [chaijs/chai#354]
The Assert interface has JSDoc coverage but Should and Expect don't. In order to keep documentation in sync, this would be good to propagate.

**Comment by keithamus** [comment]
@Soviut thanks for the issue - sorry I seemed to have missed this one before. Please feel free to make a PR, and we can merge it in and get the documentation in sync!

**Comment by reggi** [comment]
@Soviut What do you mean Asset has JSDoc coverage? Where is this documented?

**Comment by Soviut** [comment]
@reggi The Assert library has JSDoc comments, Should and Expect don't. Here's an example https://github.com/chaijs/chai/blob/master/lib/chai/assertion.js#L24

**Comment by reggi** [comment]
Gotcha @Soviut thanks for the explication!
