### ISSUE TITLE
Self Named Module is not good

### ISSUE THREAD

**Issue by juuxstar** [chaijs/chai#362]
First off, let me say that you guys are doing a great job with this project.  I find it really invaluable.

I just went to upgrade to the latest version (1.10) and things broke.  I eventually traced the problem to [here](https://github.com/chaijs/chai/blob/1.10.0/chai.js#L4796) in that the define names the module.

I'm not sure why the change happened but it breaks projects that include a paths configuration in their requireJS (or equivalent) config.

The guys at MomentJS ran into the exact same [issue](https://github.com/moment/moment/issues/1095) last year.  James Burke himself chimed in to say that this was not a good thing for lib modules to do and explains why.  In the end, they ended taking it out and going back to defining an anonymous module.

Please have a look at the thread of comments for their issue and considering doing the same for the same reasons already discussed.  Thanks.

**Comment by keithamus** [comment]
Thanks for the issue @juuxstar, that's unfortunate. The change seems simple enough but I don't know enough about RequireJS to know whether or not the change will break existing users' codebases. I'd like more discussion from anyone else who uses RequireJS to chime in - perhaps @jrburke could make comment.

**Comment by juuxstar** [comment]
It already brakes existing code bases (eg: mine) because up until this last 1.10 release it was defined without the name.  It's the 1.10 release that's causing the issue hence why I suggest it gets changed back to anonymous.

James Burke has already commented on this exact issue in the MomentJS thread that I linked.  His statement is that modules should not name themselves, rather leaving it up to the package manager (ie. RequireJS) to compose the name.  This makes it more flexible and allows better use in larger projects.

**Comment by jrburke** [comment]
Here is a link discussion anonymous vs named modules: https://github.com/jrburke/requirejs/wiki/Updating-existing-libraries#anon

**Comment by keithamus** [comment]
@juuxstar @jrburke I appreciate that we shouldnt be naming the module export. My concern is that by having it as a named export, does removing the name break compatibility for existing users? How would one require in a named vs non-named export?

**Comment by juuxstar** [comment]
With unnamed modules, RequireJS composes the name based upon a combination of parameters usually in some config section.  So for example, the `chai` module in my project is canonically named `lib/vendor/chai` because that's the partial URL that the file can be found on the server.  I use the config section to map the string `chai` to that so that I can just do `require('chai')` if I'm feeling lazy or use the full `require('lib/vendor/chai')` when I want to be explicit.  Relative paths work as well (ie. `require('../vendor/chai')` or `require('./chai')` and they all map correctly to the same module)  None of this works if the module names itself.

This also allows for multiple modules named `chai` as long as they have two different URLs (so that for example I could have an older and newer version used by different tests).  This is not possible if the module picks it's own name.

Anyone using RequireJS can easily map `require('chai')` to wherever the module actually lives on the server using the config.paths section in RequireJS so I don't think it's a big deal if this brakes a few people's projects.  Most other libraries use unnamed modules so people should be pretty used to this by now.

As was stated in that MomentJS thread I referenced earlier, "it may make it easier for those that don't know how to properly use their tools, but at the same time, makes it a PITA for those who know what they're doing."

**Comment by jrburke** [comment]
If they are loading chai via an AMD loader require call, then there is no extra hazard of named vs unnamed, but named modules do prevent more advanced uses as @juuxstar mentions. 

The only hazard of an anonymous module would be if they load chai via a manual script tag after the AMD loader script, or some other way besides using an AMD loader call to do it. So, this would be a problem:

```html
<script src="require.js"></script>
<script src="chai.js"></script>
```

In that case, the AMD loader does not have context for what that anonymous define() call is for. The fix for that situation though, if the user wants to use a script tag for chai, is to place it before the script loader tag:

```html
<script src="chai.js"></script>
<script src="require.js"></script>
```

**Comment by keithamus** [comment]
Ok. It seems like we can change it to be anonymous without breaking it for existing users - in which case I'm for this change.

A PR is welcome from anyone who wants to do it. Right now we use [component](https://github.com/componentjs/component) to build out Chai.js - this created the UMD shim wrapper for us. The dependency is set to `'*'` in the package.json which is probably not a great idea. I imagine a recent update of this changed how Chai.js gets compiled. To fix this one would need to investigate how to get Component JS to rebuild without the name.

Alternatively, we could make the switch to using Browserify, which I'd personally like to do. Browserify will compile Chai.js to have a UMD definition - the wrapper includes `if ("function" == typeof define && define.amd) define([], e);` which seems to be to fit the requirement of an unnamed export. The benefit of switching to browserify would be wider support and better familiarity with developers, as well as being able to provide first class browserify support to boot. I'd like to hear opinions from others about this though.

I'm marking this as pr-wanted, to fix the issue of named exports. Whichever way someone does this - either by tweaking existing component build or switching to browserify would be acceptable in my eyes.

**Comment by juuxstar** [comment]
I'll try to take a stab at this on a weekend but I don't have experience with Browserify nor ComponentJS.  From some cursory reading it would seem that Browserify is a better fit for Chai because it's seems simpler and ComponentJS is more opinionated and focuses on bundling JS/HTML/CSS for browser-side UI components which likely introduces extra complexity that Chai doesn't need at this time.
