### ISSUE TITLE
Unexpected / Insufficient diff output when comparing nested dates

### ISSUE THREAD

**Issue by noducks** [chaijs/chai#363]
This may be more of a feature request than a bug report. 

     var expect = require('chai').expect;

     it ('should compare two dates that are equal', function(){
         var a = {id: 1, date: new Date('10/10/2015')};
         var b = {id: 1, date: new Date('10/10/2015')};
         expect(a).to.eql(b);
     });

     it ('should compare two dates that are not equal', function(){
         var a = {id: 1, date: new Date('10/10/2015')};
         var b = {id: 1, date: new Date('11/10/2015')};
         expect(a).to.eql(b);
     });

I get the following output

       1 passing (1ms)
       1 failing
     
       1)  should compare two nested dates that are not equal:

           AssertionError: expected { Object (id, date) } to deeply equal { Object (id, date) }
           + expected - actual

     at Context.<anonymous> 

These are smaller examples of much larger 'date rich' objects that I am trying to compare. I think it would useful to get some feedback as to which of the properties is not equal, and better still, a getTime() or toString() diff between the two. Have had a look at the date time plugin, and the fuzzy plugin, but they won't do this properly with nested objects.

i.e something like this: 

     + expected - actual
          {
           +  "date": "2015-11-10T00:00:00.000Z"
           -  "date": "2015-10-10T00:00:00.000Z"
          }

**Comment by keithamus** [comment]
Thanks for the issue @noducks. This may sound odd, but the diff algorithm actually has nothing to do with Chai. Chai throws an AssertionError, with the `showDiff` property set to `true`, as well as `expected` and `actual` properties. When a test-runner (such as [Mocha](https://github.com/mochajs/mocha)) sees an error with those flags, it runs the diff engine<sup>[[Citation]](https://github.com/mochajs/mocha/blob/e5663c959c5a238d601e27e472a121d0efef1e62/test/reporters/base.js#L5)</sup>.

Of course, it isn't always the responsibility of the test-runner either; I'm going to go ahead and make the assumption you're using Mocha. If this is the case, then they use an upstream project for _their_ diff algorithm<sup>[[Citation]](https://github.com/mochajs/mocha/blob/e130e3138768ec9844e4c531b214f17abcf43f83/lib/reporters/base.js#L388)</sup>, and so if there is an issue it most likely needs to be reported with [JSDiff](https://github.com/kpdecker/jsdiff). 

Having said that, I copy/pasted your example, and ran it through my mocha, and got this result:


I'm using the latest versions of both:

```bash
$ npm list --depth=0
test@0.0.0 /<snip>
├── chai@1.10.0
├── mocha@2.1.0
└── nopt@2.1.2
```
```js

  ✓ should compare two dates that are equal
  1) should compare two dates that are not equal

  1 passing (8ms)
  1 failing

  1)  should compare two dates that are not equal:

      AssertionError: expected { Object (id, date) } to deeply equal { Object (id, date) }
      + expected - actual

       {
      +  "date": "[Date: 2015-11-10T00:00:00.000Z]"
      -  "date": "[Date: 2015-10-09T23:00:00.000Z]"
         "id": 1
       }
```

It looks like this could be an issue with your test runner. What test runner and version are you using?

**Comment by noducks** [comment]
@keithamus Thanks for taking the time to look into this. 

Turns out I had an older version of Mocha installed. All fixed now. Thanks again.
