### ISSUE TITLE
Confused about version numbering: 1.10.0 vs 2.0.0

### ISSUE THREAD

**Issue by jmm** [chaijs/chai#373]
I'm confused about the version numbering here. It started with trying to figure out why there are failing tests in the [online test suite](http://chaijs.com/api/test/) in Chrome Win. The home page says v2.0.0 is available for download. When I download the browser file I get a file that contains:

```js
/*!
 * Chai version
 */

exports.version = '1.10.0';
```

If I `npm install chai` I get a `package.json` that says its version 2.0.0, but a `node_modules/chai/chai.js` file that contains the same as above:

```js
exports.version = '1.10.0';
```

Same thing if I try building it myself. Are the `exports.version` and `package.json` version numbers referring to different things? What does the `exports.version` value indicate?

**Comment by keithamus** [comment]
Ah. That is a problem! That was missed from the release process. @jmm if you'd like to make a PR to change the version to 2.0.1 and we'll release a 2.0.1 version with the change reflected.

**Comment by jmm** [comment]
@keithamus Ok, thanks. Where exactly do you mean to change it -- is it `lib/chai.js`?

**Comment by keithamus** [comment]
Yes, sorry [lib/chai.js#L14](https://github.com/chaijs/chai/blob/master/lib/chai.js#L14), [package.json#L20](https://github.com/chaijs/chai/blob/master/package.json#L20), [bower.json#L3](https://github.com/chaijs/chai/blob/master/bower.json#L3) and [component.json#L4](https://github.com/chaijs/chai/blob/master/component.json#L4) all need to change to `'2.0.1'`.

**Comment by jmm** [comment]
Thanks. See #374.

So I think the issue with the online test suite failing is that somehow the `chai.js` in the website repo didn't correctly get updated to 2.0.0 and therefore is missing the `fail()` methods. When this repo is all set I could probably do a PR over there to straighten that out.
