### ISSUE TITLE
Unexpected behavior: `keys()` mutates the inputted array

### ISSUE THREAD

**Issue by jwngr** [chaijs/chai#376]
I ran into an unexpected behavior with chai that I think should be considered a bug. Here is a reduced repro of the issue which currently fails:

```
it('keys() should not mutate inputted array', function() {
  var expectedKeys = ['b', 'a'];
  expect({a: true, b: true}).to.have.keys(expectedKeys);
  expect(expectedKeys[0]).to.equal('b');
});
```

Calling `keys()` should be able to do the comparison without mutating the inputted array since that array could be used in later assertions.

**Comment by keithamus** [comment]
Hey @jwngr thanks for the issue!

#359 addressed a very similar bug, except it was with the array given as the `expect` param. It was quite a simple fix - in this case, we just need to change [assertions.jsL1084](https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L1084) from `actual.sort()` to `actual.slice(0).sort()`. Of course then you'll also need to write some tests to back it up (you can copy the existing tests from #359 [here](https://github.com/chaijs/chai/blob/master/test/expect.js#L742-L749) and [here](https://github.com/chaijs/chai/blob/master/test/should.js#L602-L609) and just tweak them to assert on the `keys()` param instead).

If you'd like to write up a PR for this, then please do so, and I'll happily merge it in.

**Comment by jwngr** [comment]
It looks like this is actually just a dupe of #359. Upgrading to chai 2.x.x confirms as much. Glad it's already fixed!

Updating [the line you suggested](https://github.com/chaijs/chai/blob/09e17b9e090c02d38cd5ee441881dd2691635124/lib/chai/core/assertions.js#L1084) won't have any effect since `actual` is created from an `Object.keys()` call. So the `sort()` there isn't necessary.

Thanks for the quick turnaround!
