### ISSUE TITLE
deep flag makes tests fail

### ISSUE THREAD

**Issue by lazutkin** [chaijs/chai#387]
`deep` flag makes tests fail under `iojs`

```javascript
expect({a: 1}).to.have.deep.property('a') // AssertionError: expected { a: 1 } to have a deep property 'a'
```

**Comment by keithamus** [comment]
Thanks for the issue @lazutkin. I have a feeling this might be fixed by #385 - which hasn't been released yet as a version (it's available in `master` though).

Could you try checking out the `master` copy of Chai.js and see if this is still an issue?

**Comment by lazutkin** [comment]
Yep! No problem with `master`-version

**Comment by keithamus** [comment]
@lazutkin if thats the case then I'm sure you'll enjoy the new `2.1.1` release, which incorporates the fix :smile:
