### ISSUE TITLE
`(x).should.be.true` support

### ISSUE THREAD

**Issue by dasilvacontin** [chaijs/chai#406]
It doesn't support this syntax, does it?

**Comment by dasilvacontin** [comment]
Having to do `(x).should.equal(true)` is quite ugly in comparison.

**Comment by keithamus** [comment]
Hey @dasilvacontin. That syntax works fine for me:

```js
 true.should.be.true
{ __flags: { ssfi: [Function: shouldGetter], object: true, message: null } }
> false.should.be.false
{ __flags: { ssfi: [Function: shouldGetter], object: false, message: null } }
> false.should.be.true
AssertionError: expected false to be true
```

If you're having any more difficulties, feel free to add a comment with more info and I'll re-open this issue.

**Comment by dasilvacontin** [comment]
Oh, I see, I have to manually call `chai.should()`. Isn't there a way to automatically do this? I'd like to use it via `mocha --require chai` and avoid adding a line of code to each test file.

**Comment by keithamus** [comment]
Simply use the `mocha --require` option to include your own intermediary file called something like `test/common.js` and in it include the following:

```js
global.chai = require('chai');
global.should = chai.should();
```

Then simply call `mocha --require test/common.js`. This is what I do for all of the projects where I use chai - its also helpful for adding other plugins such as sinon or webdriver.

**Comment by dasilvacontin** [comment]
Okay, thanks for the tip @keithamus!
