### ISSUE TITLE
npm install failed peer dependencies 

### ISSUE THREAD

**Issue by coleGillespie** [chaijs/chai#409]
```
[vagrant@vagrant-fedora20 web]$ npm install chai
npm http GET https://registry.npmjs.org/chai
npm http 304 https://registry.npmjs.org/chai
npm http GET https://registry.npmjs.org/deep-eql/0.1.3
npm http GET https://registry.npmjs.org/assertion-error/1.0.0
npm http 304 https://registry.npmjs.org/assertion-error/1.0.0
npm http 304 https://registry.npmjs.org/deep-eql/0.1.3
npm http GET https://registry.npmjs.org/type-detect/0.1.1
npm http 304 https://registry.npmjs.org/type-detect/0.1.1
npm ERR! peerinvalid The package chai does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer chai-as-promised@4.3.2 wants chai@>= 2.1.2 < 3
npm ERR! peerinvalid Peer sinon-chai@2.7.0 wants chai@>=1.9.2 <3

npm ERR! System Linux 3.12.6-300.fc20.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "chai"
npm ERR! cwd /var/www/socrates/web
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.3.6
npm ERR! code EPEERINVALID
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/socrates/web/npm-debug.log
npm ERR! not ok code 0
```

**Comment by keithamus** [comment]
Hey @coleGillespie, thanks for the issue and welcome to the chai community!

Can you show us your package.json? I'm pretty sure it'll contain a version of chai that conflicts with [chai-as-promised](https://github.com/domenic/chai-as-promised/) and [sinon-chai](https://github.com/domenic/sinon-chai) peerDependency versions. You'll need to install a version of chai which is at-least v1.9.2

**Comment by coleGillespie** [comment]
So it looks like its yaml-config that is failing.

https://github.com/rjyo/yaml-config-node/blob/master/package.json

maybe the best thing to do would be to get them to update their package.json?

**Comment by keithamus** [comment]
Tough one. To be frank peerDependencies are, IMO, massively broken, and are what is causing the issue here. Unless chai-as-promised/sinon-chai are relying on features from those versions (they certainly could be but I don't know), they should have less strict dependency requirements. Having said that maybe the most productive way forward is just getting yaml-config to update their chai dependency to a newer version.

Maybe @domenic might want to weigh in here.

**Comment by domenic** [comment]
They 100% do rely on features from those versions, that's the only reason they have those requirements.

**Comment by keithamus** [comment]
So there we have it - best place to raise this is, as you originally suggested @coleGillespie, yaml-config.

**Comment by keithamus** [comment]
I'm going to close this now, as it's definitely not our issue. If you have any further problems @coleGillespie - feel free to comment here or raise a new issue.
