### ISSUE TITLE
Comparing Typed Arrays with closeTo.

### ISSUE THREAD

**Issue by Twelve-60** [chaijs/chai#412]
Not sure if I'm missing something, but is it possible to compare two arrays with closeTo? This is essential when comparing arrays of type Float32Array, since with floating point errors the arrays are not exactly equal. Such is always the case in a WebGL matrix library.

Something like the following, which supports both usual arrays and typed arrays:

    // typed
    new Float32Array([1.001, 1.999, 3.001]).should.be.closeTo(new Float32Array([1, 2, 3]), 1);
    // normal
    [1.001, 1.999, 3.001].should.be.closeTo([1,2,3], 1)

**Comment by keithamus** [comment]
Hey @Twelve-60 thanks for the issue!

Interesting idea, but I think it's outside of the scope of `closeTo` and perhaps out of scope for chai. My main concerns about introducing this within chai core:

 - Passing in multiple types to a method increases complexity of the method.
 - Very little of the chai code currently does type overloading, if a method takes multiple types it usually just checks them generically, e.g. `.instanceOf()` or `.typeOf()`
   - the main exception is `.throw()` which takes Error, String or RegExp - but given the nature of errors this works well here.
   - other exceptions are where an assertion takes "array-likes" e.g. `.includes()` which takes strings or arrays. This is very little (or no) extra logic though.
 - I wonder if the use-case is strong enough. chai core is /meant/ to cover the lowest common denominator, and encourage filling extra functionality through plugins. In fact, to me, this feels very much like [Chai-things](https://github.com/RubenVerborgh/Chai-Things) territory, but @RubenVerborgh may disagree.

If you feel like I'm wrong, please feel free to argue the case. I'm just here to guide, not mandate :smile:

**Comment by RubenVerborgh** [comment]
It's not really chai-things, which is for assertions on items of arrays. It would, in my opinion, be great to have an approximate equality library.

**Comment by keithamus** [comment]
Hey @RubenVerborgh. [We already have `.closeTo()`](http://chaijs.com/api/bdd/#-closeto-expected-delta-) - the proposal is to extend `.closeTo` to support an array as the first arg, which compares against the same-index values in the given array, which is why I suggested it may be a candidate for chai-things. 

However it could also be a candidate to fold into its own plugin as well.

**Comment by Twelve-60** [comment]
Maybe something along the lines of:

    [1,2,3].should.pairwise.be.closeTo([1,2,3]

Where pairwise runs any old regular assertion against each element in a pairwise fashion? The real power here is that new assertions or plugins wouldn't have to specifically code for arrays, but automatically be mapped to support it by Chai itself.

Thoughts?

**Comment by keithamus** [comment]
@Twelve-60 it sounds like a good idea. It also sounds like it would be perfectly suited to a plugin. All of the capabilities are available for plugin authors to implement such a thing. To get you started:

You'd need to define a property that sets a flag:
```js
Assertion.addProperty('pairwise', function () {
    flag(this, 'pairwise', true);
});
```

Then you'd need to rewrite each method dynamically and monkey patch them with the "pairwise" handling. Chai-Things [does exactly this (chai-things.jsL82-92)](https://github.com/RubenVerborgh/Chai-Things/blob/1acc6dcdc24dc7e64bb7973924978e1672b38c72/lib/chai-things.js#L82-L92).

I genuinely look forward to seeing this - so if you do end up making it please let me know. If you need any more guidance please feel free to comment here; and I'll happily point you in the right direction. For now though, I'm going to close this - for the reason that I feel like this should be a plugin, and is out of scope for chai.
