### ISSUE TITLE
Error: Cannot find module './chai/utils'

### ISSUE THREAD

**Issue by sabapk** [chaijs/chai#414]
I am trying to run a grunt task using mochacli. I have been getting this error which is not related to the task I have written because it throws error earlier. When I go to node_modules to look for the folder, it doesn't exist.

Running "mochacli:all" (mochacli) task
module.js:340
    throw err;
          ^
Error: Cannot find module './chai/utils'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

**Comment by keithamus** [comment]
Hey @sabapk thanks for the issue. 

What version of chai are you running? Can you show me your grunt file please? Also what environment is this running in, I guess node? What version?

**Comment by sabapk** [comment]
The version is chai@2.1.0. I am running grunt task through cli. The task is as, http://pastebin.com/RGy5MvMK
And the unit tests are as follows, http://pastebin.com/hDvvAgb7

**Comment by sabapk** [comment]
The complete trace of error can be found in this bin, http://pastebin.com/tinTjUCv

**Comment by keithamus** [comment]
I have a hunch you may be using the node version of chai in browserland. How did you install chain? With npm?

**Comment by sabapk** [comment]
Yes I installed using npm.

**Comment by sabapk** [comment]
I solved this issue. I had earlier copied the mocha.css, mocha.js and chai.js files out of node_modules folder to support mocha in browser for ease. Now I deleted the folder and its working fine. Thanks for the hint.
