### ISSUE TITLE
Message of a CustomError-Class not correctly checked if thrown without arguments

### ISSUE THREAD

**Issue by Charminbear** [chaijs/chai#416]
If you define a custom error class and then throw it without arguments, `.throws()` will not check the message property.

See the following, passing test:
```JavaScript
it('Custom Error Message is not checked if called without arguments', function () {
    // CREATE A CUSTOM ERROR CLASS
    var myCustomError = function (message) {
        this.name = 'myError';
        this.message = message;
    };
    require('util').inherits(myCustomError, Error);
    expect(require('util').isError(new myCustomError())).to.be.true; // PASSES

    var throwing = function () {
	// THROW ERROR WITHOUT ARGUMENTS
        throw new myCustomError();
    };
    expect(throwing).to.throw(myCustomError, 'MyMessage'); // UNEXPECTEDLY PASSES
});
```

It only seems to behave like this as long as the message property is `null` or `undefined`. If I change the constructor to `this.message = message || ''` or throw the Error with an empty String (`throw new myError('')`, it fails as expected.

Is this a bug or am I doing something wrong?

**Comment by keithamus** [comment]
@Charminbear do you think it is reasonable to close this given your 3.x.x PR is merged? I aim to release 3.x at some point this month, as I don't want to keep it hanging around too long.

**Comment by Charminbear** [comment]
@keithamus yes of course. No sense in putting work in fix thats obsolete in 3 weeks. :D

Im excited for 3.x.x :+1:
