### ISSUE TITLE
Have "match" perform matching of array elements

### ISSUE THREAD

**Issue by spemmons** [chaijs/chai#426]
I have found the following function useful for myself and it would be cool if it -- or something similar -- could be incorporated into the "match" function when an array is involved...

```javascript
function matchArrays(actual,expected){
    actual.length.should.equal(expected.length);
    for(var index = 0; index < actual.length; index++) {
        if (typeof expected[index] === 'string')
            actual[index].should.eql(expected[index]);
        else
            actual[index].should.match(expected[index]);
    }
};
```

**Comment by keithamus** [comment]
Hey @spemmons thanks for the issue.

To me, it very much looks like you want to look at [chai-things](https://github.com/RubenVerborgh/Chai-Things/) which allows assertions such as `arrayOfStrings.should.all.match(/foo/)`.

I'll close this issue for now - if you're not happy with the above answer, feel free to reply and I'll re-open it, or file a new issue.
