### ISSUE TITLE
Length() should be removed from documentation

### ISSUE THREAD

**Issue by matthijsgroen** [chaijs/chai#427]
`expect('something').to.have.length(9)`

and

`expect('something').to.have.lengthOf(9)`

are the same... on paper

but consider this test:

```
describe 'overriding properties', ->
  beforeEach ->
    global.expect = require("chai").expect
    global.when = require("when")

  it 'works without overrides', ->
    expect('something').to.have.length(9)

  it 'breaks for each property', ->
    chai = require "chai"
    chai.Assertion.addChainableMethod 'have', ->
    expect('something').to.have.length(9) # Fails with: TypeError: Property 'length' of object [object Function] is not a function

  it 'breaks the length method', ->
    chai = require "chai"
    chai.Assertion.addChainableMethod 'to', ->
    expect('something').to.have.length(9) # Fails with: TypeError: Property 'length' of object [object Function] is not a function

  it 'does not break the lengthOf method', ->
    chai = require "chai"
    chai.Assertion.addChainableMethod 'to', ->
    expect('something').to.have.lengthOf(9)
```

The breaking change is in: https://github.com/chaijs/chai/blob/master/lib/chai/utils/addChainableMethod.js#L79

A function object is constructed, and the object has a `length` property of its own, and thus overriding the length method the original asserter had.

`console.log (->).length # ==> 0`

`lengthOf` is not a magical javascript property and is left alone. We should encourage people to use `lengthOf` instead of `length` in the syntax of their tests.

**Comment by valscion** [comment]
:+1: For removing `length` — this is some really funky behaviour.

**Comment by keithamus** [comment]
I concur. We'll need to keep it around for backwards compatibility. Maybe we'll do this:

 - v.next: Remove docs
 - v.next+1: Log deprecation warning when accessing .length()
 - v.major: Remove .length()

Open to PRs removing docs for now.

**Comment by valscion** [comment]
Great! Wouldn't it be more friendly for chai users to tell about the deprecation in the docs instead of removing the mention altogether?

**Comment by keithamus** [comment]
Sure sounds like a better plan.

**Comment by valscion** [comment]
I'll quickly draft a PR for that now.

**Comment by valscion** [comment]
Hey @keithamus, I noticed that even using `length` as a chain precursor fails:

```coffee
describe 'overriding properties', ->
  beforeEach ->
    global.expect = require("chai").expect
    global.when = require("when")

  it 'works without overrides', ->
    expect('something').to.have.length(9)

  it 'breaks for each property', ->
    chai = require "chai"
    chai.Assertion.addChainableMethod 'have', ->
    expect('something').to.have.length(9) # Fails with: TypeError: Property 'length' of object [object Function] is not a function

  it 'breaks the length method', ->
    chai = require "chai"
    chai.Assertion.addChainableMethod 'to', ->
    expect('something').to.have.length(9) # Fails with: TypeError: Property 'length' of object [object Function] is not a function

  it 'does not break the lengthOf method', ->
    chai = require "chai"
    chai.Assertion.addChainableMethod 'to', ->
    expect('something').to.have.lengthOf(9)

  it 'breaks the chain precursor way', ->
    chai = require "chai"
    chai.Assertion.addChainableMethod 'to', ->
    expect([1, 2]).to.have.length.above(1) # Fails with: TypeError: Object 0 has no method 'of'
```

**Comment by keithamus** [comment]
Sounds like that may be different bug. Please feel free to file a new issue.

**Comment by matthijsgroen** [comment]
Is there still progress in this? What is the hold up at the moment?
