### ISSUE TITLE
Expect to throw force string equality instead of inclusion

### ISSUE THREAD

**Issue by totty90** [chaijs/chai#436]
```js
expect(fn).to.throw(Error, "test")
```

will pass even if the error thrown in like this `new Error('test2'`). I would expect to don't pass as "test" is not equal to "test2".

In your docs you say:

>string inclusion test for the error's message.

So it passes if the string is included. Is there any way to change the behaviour of this?

**Comment by keithamus** [comment]
@totty90 you can easily new up an error and achieve your desired result, something like this should work:

```js
expect(fn).to.throw(new Error("test"));
```

Having said that - I do think our `throw()` assertion needs some work, see also #430. I'm going to devote some time to this soon, to try and change it for `3.0.0`

**Comment by niftylettuce** [comment]
Same bug.

**Comment by niftylettuce** [comment]
See https://github.com/chaijs/chai/pull/551

**Comment by gurdiga** [comment]
> @totty90 you can easily new up an error and achieve your desired result, something like this should work:
>
> ```js
> expect(fn).to.throw(new Error("test"));
> ```

It seems like this doesn’t work. =/

It looks like the _expected_ and _actual_ errors are compared strictly, and the result is that the assertion fails even if the error constructor and messages correspond. I have prepared [a quick jsfiddle demo with chai v.3.4.1](https://jsfiddle.net/gurdiga/8snw50ka/):
```js
function throwingFunction() {
    throw new Error('A specific error message');
}

chai.expect(throwingFunction).to.throw(new Error('A specific error message'));
```
Check the browser console to find the assertion error message:
```
Uncaught AssertionError: expected [Function: throwingFunction] to throw 'Error: A specific error message' but 'Error: A specific error message' was thrown
```
I’m wondering if there I’m missing something. 8-|

**Comment by keithamus** [comment]
Hey @gurdiga - yes I was actually wrong above, passing two error instances will check for referential equality. `4.0.0` will change this (among other things). But we have a few outstanding PRs that I want to get merged in before I cut a release.

**Comment by gurdiga** [comment]
Sounds like a plan! Thank you! 8-)

>

**Comment by lucasfcosta** [comment]
Since we've got #683 merged, this has been solved.
Thanks everyone for your input :smile:
