### ISSUE TITLE
.match() aliased to .matches()

### ISSUE THREAD

**Issue by thejameskyle** [chaijs/chai#438]
So it can be written like this:

```js
chai.expect({ foo: 'bar' }).to.have.property('foo').that.matches(/^bar$/)
```

**Comment by keithamus** [comment]
Sounds fine to me. [assertions.js#L988-L1009](https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L988-L1009) is where the match function is, and right above it you can see an example of how to make aliases of a method (basically make it a function to reference, then add two methods).
