### ISSUE TITLE
Not working in IE 10

### ISSUE THREAD

**Issue by vitalets** [chaijs/chai#459]
Hi, I include chai in IE10 and getting error about trailing comma.
https://github.com/chaijs/chai/blob/master/chai.js#L3695
````js
var info = {
    parent: parsed.length > 1 ? _getPathValue(parsed, obj, parsed.length - 1) : obj,
    name: last.p || last.i,
    value: _getPathValue(parsed, obj),
  };
````

can we do something with it?
Thanks!

**Comment by csnover** [comment]
(Incidentally Chai works fine in IE10, this user is probably loading it into some quirksmode page that is using the ES3 JScript engine so Chai won’t work anyway.)

**Comment by TheSavior** [comment]
I am also seeing this error when running chai through the closure compiler as part of my app bundle:

```
[echo] Precompiling assets
     [exec] rake aborted!
     [exec] Closure::Error: /closure_compiler.17643.3664:5503: ERROR - Parse error. Internet Explorer has a non-standard intepretation of trailing commas. Arrays will have the wrong length and objects will not parse at all.
     [exec]   };
     [exec]    ^
     [exec] 
     [exec] 1 error(s), 0 warning(s)
```
