### ISSUE TITLE
should.throw(Error) returns error "Message can not be handled"

### ISSUE THREAD

**Issue by reharik** [chaijs/chai#462]
Hi, I'm trying to test that an error is thrown. my test, as in title is fn.should.throw(Error), I've also tried fn.should.throw(new Error("proper error message")); both return  "Error: Message can not be handled. No ReceiptHandle." 
not sure what to do about this. for now, I'll just do my own try catch.  But thought I'd mention it.
Thanks,
r

**Comment by keithamus** [comment]
Hey @reharik thanks for the issue.

Sounds like you're probably dealing with an error elsewhere in the app. That error seems to be very specific to your code. What happens if you just try doing `try { fn(); } catch(e) { }`? I'd imagine the same error comes back.

**Comment by reharik** [comment]
omg. sorry doing too many things at once.  Yes that is my message. duh.  However, I can't get the throw assertion to succeed. I tried the above, as well as "expect(mut(null, fullMessage)).to.throw(Error);"
they all return my error, which is the code "throw(new Error( "Message can not be handled. No ReceiptHandle."))"
my try catch works though.
thanks,
r

**Comment by meeber** [comment]
This is over a year old so doubt you're still dealing with it, but just in case someone stumbles upon this via google...

This won't work:

```js
expect(mut(null, fullMessage)).to.throw(Error);
```

But this will work:

```js
expect(function () {
  mut(null, fullMessage)
}).to.throw(Error);
```

And if no parameters need to be passed, this will work as well:

```js
expect(mut).to.throw(Error);
```

The key distinction is that the final two examples are testing a function, whereas the first example is calling a function.
