### ISSUE TITLE
Why null === undefined

### ISSUE THREAD

**Issue by ricardofbarros** [chaijs/chai#465]
Running the following sample throws an error.

```js
var chai = require('chai')
var assert = chai.assert

var undf

assert.notEqual(null, undf)
```

**Comment by keithamus** [comment]
Hey @ricardofbarros thanks for the issue.

As the [docs suggest, `notEqual` performs a non-strict non equality test](http://chaijs.com/api/assert/#notEqual-section), and in JavaScript `null == undefined`. You'll want to use [`assert.notStrictEqual()`](http://chaijs.com/api/assert/#notStrictEqual-section). To quote:

> ### .notEqual(actual, expected, [message])

> @param{ Mixed }actual
> @param{ Mixed }expected
> @param{ String }message
> Asserts non-strict inequality (!=) of actual and expected.

> `assert.notEqual(3, 4, 'these numbers are not equal');`


> ### .notStrictEqual(actual, expected, [message])

> @param{ Mixed }actual
> @param{ Mixed }expected
> @param{ String }message
> Asserts strict inequality (!==) of actual and expected.

> `assert.notStrictEqual(3, '3', 'no coercion for strict equality');`


I'm going to close this issue, but if you have any more problems feel free to comment on this issue or raise a new one.

**Comment by ricardofbarros** [comment]
Oww sorry, didn't even see the full API, my bad I though that `.notEqual` was a strict compare, thank you :+1:
