### ISSUE TITLE
Should deepEqual use hasOwnProperty?

### ISSUE THREAD

**Issue by raineorshine** [chaijs/chai#466]
I found this out the hard way when a library was returning an instance of a constructor instead of a generic object. It looked the same via console.log, but the test was failing.

```
var Person = function(name) { this.name = name; }
Person.prototype.toString = function() { return 'My name is ' + this.name; }

var bob1 = new Person('bob')
var bob2 = { name: 'bob' }
expect(bob1).to.deep.equal(bob2) // false
```

The test output was pretty unhelpful:

```
  0 passing (32ms)
  1 failing

  1) semver-utils should parse good ranges:

      AssertionError: expected [ Array(1) ] to deeply equal [ Array(1) ]
      + expected - actual


      at Context.<anonymous> (test/spec.js:14:12)
```

It seems like the default `deepEqual` behavior should only check properties for which hasOwnProperty is true [which is the behavior of node's built-in assert.deepEqual](https://github.com/joyent/node/blob/master/lib/assert.js#L187-L229). Or an alternative `deepOwnEqual` with that behavior should be provided.

**Comment by stevenvachon** [comment]
+1

**Comment by Sinewyk** [comment]
It probably should.

**Comment by Sinewyk** [comment]
Just FYI, chai seems to be an outsider regarding deep equality behavior.

Libs seems to have converged on the node [assert.deepEqual](https://nodejs.org/api/assert.html#assert_assert_deepequal_actual_expected_message) behavior.

Notable differences:
```
> function Foo(x) {this.x = x}
undefined
> Foo.prototype.bar = function(){console.log(x)}
[Function]
> var a = new Foo(1)
undefined
> var b = {x: 1}
undefined
> assert.deepEqual(a,b)
undefined
> require('chai').expect(a).to.deep.equal(b);
AssertionError: expected { x: 1, bar: [Function] } to deeply equal { x: 1 }
```

Logging seems a bit iffy in this case.

If we try with
```javascript
function Foo() {
  this.a = 1;
  this.b = 2;
  this.c = 3;
  this.d = 4;
}
var a = new Foo();
var b = {a: 1, b: 2, c: 3, d: 4};
```
`assert.deepEqual(a, b)` does not throw.

but of course
```
> require('chai').expect(a).to.deep.equal(b)
AssertionError: expected { Object (a, b, ...) } to deeply equal { a: 1, b: 2, c: 3, d: 4 }
```

which isn't really helping.

There's some work to be done somewhere.

Reference: [shouldjs](https://github.com/shouldjs/should.js) implements the hasOwnProperty check https://github.com/shouldjs/equal/blob/master/index.js#L279 in their helper lib [should-equal](https://github.com/shouldjs/equal),
nodejs assert (the reference I suppose) also does the same for non strict deepEqual https://github.com/nodejs/node/blob/master/lib/assert.js#L209
and [mjackson/expect](https://github.com/mjackson/expect) also implements hasOwnProperty by using [substack/node-deep-equal](https://github.com/substack/node-deep-equal)

We should probably get on the same page. With a strict and non strict deep equal behavior.

**Comment by keithamus** [comment]
These are all good points @metaraine @Sinewyk. 

I think this needs a good plan of action, because it will be very impactful to our users.

**Comment by Sinewyk** [comment]
Hmm, I'm coming back to this because expect just moved from node-deep-equal to is-equal.

I would say best create a own flag
```javascript
expect(A).to.deep.own.equal(B);
```
to emulate other behaviors as a opt-in. With the appropriate documentation it should be ok.

There's still the matter of which library will power the own flag. Do we edit https://github.com/chaijs/deep-eql or use something else ? Ultimately your choice probably ^^.

**Comment by stevenvachon** [comment]
`deep.own.equal()` +1

**Comment by r-tanner-f** [comment]
deep.own.equal() + 1

**Comment by r-tanner-f** [comment]
For bonus fun, the AssertionError's expected and actual properties *do* deep equal. :) I'd assume whatever is generating those properties *is* checking hasOwnProperty.

**Comment by Sinewyk** [comment]
I suspect objDisplay which uses Object.keys, Object.keys has a hasOwnPrototype check built-in.

**Comment by keithamus** [comment]
Thanks everyone for your input here.

We've added this to our Roadmap https://github.com/chaijs/chai/projects/2! We'll be releasing chai 5 soon, but for now I'll close this issue because it is tracked on our roadmap.
