### ISSUE TITLE
expect(5).to.be.a.string does not throw error

### ISSUE THREAD

**Issue by cappslock** [chaijs/chai#476]
So I have done this, and it does not throw an error:
```
expect(5).to.be.a.string;
```
After playing a bit and checking the docs, I realize that this is not the intended use of string in a chain, and what I actually want is this:
```
expect(5).to.be.a("string");
```
Great! But I wonder if there are invalid assertions that exist because of the first case's perceived intuitiveness when you get used to writing natural language chains. Would it be possible to detect when that case pops up and throw an error, or are there difficulties/tradeoffs which prevent that?

**Comment by keithamus** [comment]
Hey @cappslock thanks for the issue.

We have some ideas in the pipeline about solving this class of problem, namely #407 and #457. I suggest subscribing to those issues if you want updates about this.

I'll close this for now, as #407 and #457 cover solving problems like these pretty perfectly.
