### ISSUE TITLE
What to expect when you're expecting

### ISSUE THREAD

**Issue by astorije** [chaijs/chai#501]
I was making tests trying to be right on #496 (:smile:) and found that if you assert:
 
```js
expect(3).to.include(2);
```

You end up with:

```js
     TypeError: undefined is not a function
      at Assertion.include (lib/chai/core/assertions.js:217:30)
      at Assertion.assert (lib/chai/utils/addChainableMethod.js:83:49)
      at Context.<anonymous> (test/expect.js:1131:18)
```

The `assert.include(3, 2);` twin assertion reacts similarly, but the key difference is that the `assert.include(haystack, needle)` method definition explicitly says that the haystack should be `{Array|String}` (so one just needs to read the doc). The type of the argument given to `expect()` is never specified in the doc (or at least I couldn't find it), meaning this should `Mixed`.

Making sure the type is controlled for `expect(...).to.include(...)` is similar to issue #491 and PR #496.

I am guessing there are other cases like that but I haven't tested them all. I am not sure if there should be a global way to do that in the code or if we should handle that on a case-by-case basis as what we are leaning to on #496.

**Comment by keithamus** [comment]
Good call as usual @astorije. We should check for other primitives in assertions like these.

I think for these kind of assertions we should probably throw an error explaining the problem. In this instance maybe `AssertionError: expected 3 to include 2, but cannot include multiple values` or something. Thoughts?

**Comment by astorije** [comment]
What do you mean by `cannot include multiple values`?

I would go for something simple and explicit like `AssertionError: argument of expect() must be an Array or a String, number given` (or `3 given`).
It's not necessary or useful to remind the value (`2`) as this is not causing any error and therefore can be misleading.

**Comment by keithamus** [comment]
Agree, yours sounds much better than mine. `3 given` I think would be best. PR welcome :smile:

**Comment by astorije** [comment]
Okay, I'll see if I can find an hour to send you that within the next few of days. I'd personally prefer `[type] given` as a user, but it's up to you.

**Comment by berkerpeksag** [comment]
This is also fixed in https://github.com/chaijs/chai/commit/d7d9420a24a50d88468644386a82f7b0b08262bf (just pasting the merge commit) and can be closed now.
