### ISSUE TITLE
.not. interpretation creates invalid sentences for humans

### ISSUE THREAD

**Issue by TimeForAChange** [chaijs/chai#510]
`not` negates *everything* that comes after it. That conflicts with how a human would interpret a sentence with `and`:

```javascript
    it ('should not include 2 and 3', function () {
        expect([1, 4, 5, 6, 7, 8]).to.not.include(2).and.include(3);
    });
```

As a human I would read this as "should *not* include 2, but *should* include 3".

Since the goal is human readable tests I think `not` should stop negating at an `and` statement so that I can write (note the 2nd `not`)

```javascript
    it ('should not include 2 and 3', function () {
        expect([1, 4, 5, 6, 7, 8]).to.not.include(2).and.not.include(3);
    });
```

**Comment by abenhamdine** [comment]
+1
Yes, totally agree, this is a well-known gotcha of chai.
But changing this behaviour is a huge breaking change...

**Comment by keithamus** [comment]
Thanks for the issue @TimeForAChange. 

It's a tough one, as you say - it isn't entirely grammatically correct. The `and` word is actually a noop, so doesn't change anything - and could be omitted, it's just there to help the code read better - which in this case obviously hasn't worked.

The good news is that you could re-use `not` as much as you want - it is idempotent. So these assertions all produce the same behaviour:

```js
expect([1, 4, 5, 6, 7, 8]).not.include(2).include(3);
expect([1, 4, 5, 6, 7, 8]).to.not.include(2).and.not.include(3);
```
