### ISSUE TITLE
Array empty test broken.

### ISSUE THREAD

**Issue by rcollette** [chaijs/chai#519]
I have a test where I have confirmed that I am running an expectation on a zero length array yet I get the following when I test for empty.  This started in 3.3 and it works fine in 3.2
```
'[]'  //Stringified array contents.

	AssertionError: expected [ Array(0) ] to be empty
	    at node_modules/chai/chai.js:210
	    at node_modules/chai/chai.js:687
	    at addProperty (node_modules/chai/chai.js:3901)
```

**Comment by keithamus** [comment]
Hey @rcollette thanks for the issue.

Could you show some code (either what you have or a reduced test case) that is breaking? Is this definitely something that has changed only with the change of 3.2 to 3.3 or did you upgrade other packages?

**Comment by rcollette** [comment]
I am unable to reproduce this in a plnkr.   Closing since there is little you can do without a reproduction.
http://plnkr.co/edit/3y1d5u?p=preview
