### ISSUE TITLE
Document possible `a`/`an` matcher parameters

### ISSUE THREAD

**Issue by jurko-gospodnetic** [chaijs/chai#520]
The values passed to `a`/`an` matchers seem to correspond to the `type-detect` library's results reported for specific objects. That means that since that library got introduced, e.g. `new Error(...)` is no longer detected as a `object` and is now detected as an `error` instead.

Could the documentation on those matchers be updated?

**Comment by keithamus** [comment]
Thanks for the issue @jurko-gospodnetic, that sounds like a great idea! PR very much wanted :smile:

**Comment by keithamus** [comment]
I'll point out that the site has yet to be updated - it's getting quite stale but we need to spend some time redeveloping it to have automated builds. 

The documentation for `an` is [here (L127-155 of assertions.js)](https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L127-L155) and the docs have been updated for the new behaviour (with an exception of Error missing). Feel free to include error as an example, and when the new site gets built it'll be reflected!

**Comment by jurko-gospodnetic** [comment]
Added pull request #521 for this.
