### ISSUE TITLE
catch error when "expect(fn).to.throw(Error)"

### ISSUE THREAD

**Issue by java9s** [chaijs/chai#524]
Hi,
  I was trying to use expect(fn).to.throw(Error) feature to check if my function throws error with wrong input.
My observation is that when my method throws error, the control does not reach done() and my scenario does not pass. I have to implement try-catch myself and then include done() in catch to get rid of the error and also to pass the test.

Example:
```js
var myfunction = function myFuction(msg){
  if(msg === undefined){
    throw new Error();
  }
}
```

my implementation in spec.js
```js
try{
  expect(myfunction).to.throw(Error);
}catch(Error){
  done();
}
```

Expectation:
My sugesstion is that if chai can implement the try catch and give the control back, then we do not have to explicitly write try catch and include the done() in the catch.
Well, i am new to javascript and i was stuck for sometime how to get rid of the error and make my test pass. 

Thank you,
Regards,
java9s

**Comment by keithamus** [comment]
Hey @java9s thanks for the issue.

I'm not really sure what you mean by trying to do a `try/catch`. You expect calling `myFunction` with no arguments to throw an error, right?

`expect(myFunction).to.throw(Error)` will do one of two things: if the `myFunction` call throws, then the assertion will do nothing, it'll be a noop. If the `myFunction` call does not throw, then the assertion itself will throw an `AssertionError`. 

If you want, you can invert that behaviour by doing `expect(myFunction).to.not.throw(Error)` (notice the `.not`) - this will do nothing if `myFunction` __does not__ throw, and will itself throw an `AssertionError` if the `myFunction` call __does__ throw.

Also, you should only need `done()` if you're working with asynchronous code (I'm assuming here, that you're using Mocha). Having a test like:

```js
it('should throw when given no arguments', function () {
  expect(myFunction).to.throw(Error);
});
```

Is a perfectly valid test. You need no more than that, given the implementation you suggested.

**Comment by vdanniel** [comment]
Hi Keithamus, 

it('should throw when given no arguments', function () {
  expect(myFunction).to.throw(Error);
}); 

is not working. 
I am having a similar issue. 

expect(await eventProcessor.processEvent(null)).to.throw(Error);

does not pass. but it should as processEvent will throw an error if argument is null.

**Comment by rogadev** [comment]
![image](https://user-images.githubusercontent.com/61405141/160914805-fc672ea5-c6ae-4467-aede-4075ae0cb202.png)
```js
it('should throw an error if the first parameter is not an array', () => {
        expect(() => first('not an array')).to.throw(Error)
      })
      ```
Any idea why I'm getting this issue? Is it related to the initial issue posted here?
