### ISSUE TITLE
expect(value).to.be.in(list) requested.

### ISSUE THREAD

**Issue by Droogans** [chaijs/chai#532]
I know you can get this with `contains.members`, but it does not play well with https://github.com/domenic/chai-as-promised/, which would take well to this feature.

Current:

```js
somePromise.then(function (result) {
    expect(list).to.contain.members([result]);
});
```

With this new feature, it could be written more simply as

```js
expect(somePromise).to.eventually.be.in(list);
```

**Comment by keithamus** [comment]
Hey @Droogans thanks for the issue.

How does it not play well with chai-as-promised? Does the following not work?

```js
expect(somePromise).to.eventually.contain.members([result]);
```

If it doesn't... I'll tentatively say this is a bug with chai-as-promised.

**Comment by Droogans** [comment]
In this example, `somePromise` resolves to a string. That's why it's `be.in`, which would function like [the `in` operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/in), which checks if a string is contained within an array.

Here's some examples of what I'm talking about in a simpler (synchronous) form.

```js
expect('a').to.contain.members(['a', 'b', 'c']);

> "AssertionError: expected 'a' to be an array"
```

Switching the first argument to a list type fails too.

```js
expect(['a']).to.contain.members(['a', 'b', 'c']);

> "AssertionError: expected [ 'a' ] to be a superset of [ 'a', 'b', 'c' ]"
```

I think it reads nicer to `expect('a').to.be.in(['a', 'b', 'c'])` instead.

**Comment by keithamus** [comment]
So I think what you're looking for, is to assert that one value is equal to one of a set of values - the equivalent of `['a', 'b', 'c'].indexOf('a') !== -1`. Is this correct?

**Comment by Droogans** [comment]
Yes, that would assert the condition properly.

**Comment by keithamus** [comment]
Now that I'm following, I agree that this is missing in Chai, and could be useful.

I'm a little wary of using `in` as an assertion - mostly because it doesn't convey enough information about what the assertion does. How do you feel about something like `expect('a').to.be.oneOf('a', 'b', 'c')` instead?

**Comment by Droogans** [comment]
The name `oneOf` is fine -- the argument type isn't a list though.

I create lists of data to enumerate over in my tests, often. One of the first checks I make, however, is that something I'm interested in appears in that list, so I like to reuse that bit in both places.

```js
var types = ['a', 'b', 'c'];

it('should have a main type', function () {
    expect(mainType).to.eventually.be.oneOf(types);
});

types.forEach(function (type) {
    it('should find type ' + type + ' somewhere on the page', function () {
        expect(getByType(type)).to.eventually.be.ok; // whatever, blah blah blah
    });
})
```

**Comment by keithamus** [comment]
Ok, well I'd accept a PR with `oneOf(Array)` as a new assertion. Would you like to formulate a PR? I'd be happy to offer guidance where needed.

**Comment by Droogans** [comment]
Yeah I could spare some time this evening and see what I can get done by tonight.

[Do you have a CLA](https://github.com/chaijs/chai/search?utf8=%E2%9C%93&q=CLA)?

**Comment by keithamus** [comment]
We do not, but I'll quote our [CONTRIBUTING.md](https://github.com/chaijs/chai/blob/master/CONTRIBUTING.md#pull-requests):

> __IMPORTANT__: By submitting a patch, you agree to allow the project owner to license your work under the same license as that used by the project.
