### ISSUE TITLE
Map deep equality.

### ISSUE THREAD

**Issue by dmwyatt** [chaijs/chai#536]
```
const state1 = {x: new Map([['one', 'one']])};
const state2 = {x: new Map([[1, 1]])};
expect(state1).to.deep.equal(state2);
```

Expect currently passes this.  Should `deep.equal` be updated to check Maps, or should this be a new plugin?

**Comment by keithamus** [comment]
Hey @dmwyatt thanks for the issue.

There is an issue in [deep-eql](https://github.com/chaijs/deep-eql), our deep equality lib: https://github.com/chaijs/deep-eql/issues/4 for this very thing.

The work for this needs to be done there, and I've described how a PR could be made. Feel free to read the details of that issue, and we'll develop a solution there.

**Comment by keithamus** [comment]
Just doing some issue cleanup - I'm going to close this one as we have https://github.com/chaijs/deep-eql/issues/4 which should be the canonical issue for this. Rest assured it's going to get fixed, but you might want to subscribe to https://github.com/chaijs/deep-eql/issues/4 for updates.
