### ISSUE TITLE
chaijs.com down, returning 500s

### ISSUE THREAD

**Issue by JaKXz** [chaijs/chai#542]
:frowning:

**Comment by stenrap** [comment]
It's been down all day. Right after I gave my team a presentation about chai and how we'll be using it in our unit tests. :)

**Comment by keithamus** [comment]
Hey y'all, closing this in favour of https://github.com/chaijs/chai-docs/issues/94. Please use that for now for reporting issue about this. We're working hard to get the server back up for now. If you want to help please read through https://github.com/chaijs/chai-docs/issues/94 and https://github.com/chaijs/chai-docs/issues/74
