### ISSUE TITLE
[suggestion] Create gitter chat room

### ISSUE THREAD

**Issue by hellboy81** [chaijs/chai#564]

**Comment by keithamus** [comment]
We actually do have a Gitter ([chaijs/chai](https://gitter.im/chaijs/chai)) and a Slack ([chai-js.slack.com](https://chai-js.slack.com)). They're not very well advertised (I'm the only one on the slack channel :laughing:).

We should probably add a link in the readme. Pull requests welcome :smile:

**Comment by keithamus** [comment]
FYI I just setup a slackin heroku deploy so if you want an invite to the slack channel, you can visit https://chai-slack.herokuapp.com/ and it'll auto-invite you :smile: 

I suppose we should add the slackin url to our README. Once again that URL is https://chai-slack.herokuapp.com/
