### ISSUE TITLE
expecting an undefined function to have been called erroneously succeeds

### ISSUE THREAD

**Issue by djbeaumont** [chaijs/chai#569]
We noticed the following strange behaviour when implementing `dirty-chai` to meet our coding standards. The following call succeeds:
```
expect(undefined).to.have.been.called;
```

Whereas with dirty-chai it fails as expected:
```
expect(undefined).to.have.been.called();
```

I have reproduced this in a repo with our various dependencies available here: https://github.com/djbeaumont/chai-undefined I've also tested it with v3.4.1, the latest version on npm as of writing.

**Comment by keithamus** [comment]
Hey @djbeaumont thanks for the issue.

My understanding is that dirty-chai rewrites all properties into methods, so `to.be.called` will not work. Having said that, chai official doesn't "support" dirty-chai - I mean to say you'd be much better off filing an issue on the [dirty-chai issue tracker](https://github.com/prodatakey/dirty-chai/issues) as you'd be more likely to get help there.

I'll close this one for now. If you file an issue on dirty-chai's issue tracker, please do reference this one - and if we find it is actually our issue I'll reopen and investigate. Thanks :smile:
