### ISSUE TITLE
Need each language word

### ISSUE THREAD

**Issue by jamespedid** [chaijs/chai#603]
I'm finding the expectation library difficult to assert many things over a collection of object. For example, I might want to verify that every object in a collection has the property "foo" with the value of "bar".

To do this, I would hope to do

    expect(collection).to.each.have.property("foo", "bar")

The "each" connective should apply the property assertion to each element of the collection.

**Comment by keithamus** [comment]
Hey @jamespedid thanks for the issue.

Have a look at [Chai Things](https://github.com/chaijs/chai-things) - it gives you a way to assert over a set of items in an Array, for example `expect(collection).to.all.have.property('foo', 'bar')`.

Hopefully this is what you're after. I'll close the issue for now - but if this isn't what you want, let me know and I can re-open this issue and we can discuss it further.
