### ISSUE TITLE
Return False if assert fails

### ISSUE THREAD

**Issue by pulkitguptasjsu** [chaijs/chai#609]
**is it possible to modify chai.assert to return false instead of throwing showDiff if assert fails ?**

As of now I am able to print fail msg on console .. but still unable to return a value/Boolean 

Assertion.prototype.assert = function (expr, msg, negateMsg, expected, _actual, showDiff) {
    var ok = util.test(this, arguments);
    if (true !== showDiff) showDiff = false;
    if (true !== config.showDiff) showDiff = false;

    if (!ok) {
      var msg = util.getMessage(this, arguments)
        , actual = util.getActual(this, arguments);
      	 console.log("Sorry Buddy .. Test case Fail ");
     /* throw new AssertionError(msg, {
          actual: actual
        , expected: expected
        , showDiff: showDiff
      }, (config.includeStack) ? this.assert : flag(this, 'ssfi'));*/
    }
  };

**Comment by meeber** [comment]
Hi @pulkitguptasjsu, apologies for the delay. Is this still an outstanding issue for you?

**Comment by maurop123** [comment]
Is this possible to do? Would be handy :wave:

**Comment by keithamus** [comment]
Hey @mention thanks for the issue.

Chai 5 will allow you to define a custom `onError` handler. By default this will throw, but overriding it will allow you to - for example - console.log instead. The returned value from any assertion will not be `false` though, however it will have a property of `result` which will be `true` or `false`.

We don't have a definite time of when Chai 5 will be released, but it should be soon-ish. You can follow along on our roadmap https://github.com/chaijs/chai/projects/2!
