### ISSUE TITLE
Incorrect version on chaijs.com homepage

### ISSUE THREAD

**Issue by paul-barry-kenzan** [chaijs/chai#616]
The current version listed on the home page is incorrect and should be updated to match the latest release. 

<img width="504" alt="screen shot 2016-02-09 at 2 08 12 pm" src="https://cloud.githubusercontent.com/assets/12274057/12927532/ba47eddc-cf36-11e5-8b48-648e9d9f639f.png">

**Comment by keithamus** [comment]
Hey @paul-barry-kenzan thanks for the issue.

We're in the process of migrating the chai website to github-pages. http://chaijs.com points to the older version while we get everything right. http://chaijs.github.io/chai-docs is the _temporary_ url for the new version. In the next few weeks we hope to update http://chaijs.com to the new pages.

I'll close this for now, as the chai team are aware of this, and its on the cards.
