### ISSUE TITLE
Monospaced fonts on home page fail to specify a fallback

### ISSUE THREAD

**Issue by martine** [chaijs/chai#617]
All the code samples on the home page are in an ugly serifed font for me.

The CSS has: "    font-family: Monaco, Bitstream Vera Sans Mono, Lucida Console, Terminal;" which means that unless you have one of exactly that set of fonts installed, you get browser default.

The fix is to add "monospace" to the end of the list.

**Comment by keithamus** [comment]
Hey @martine thanks for the issue.

Fancy making a PR for this?

**Comment by martine** [comment]
I'm not sure where the home page HTML is hosted, got a pointer?

**Comment by martine** [comment]
nm, found it.

**Comment by keithamus** [comment]
Hah, sorry I didn't read the url thoroughly enough. Thought you'd already filed this in the chai-docs repo :smile:
