### ISSUE TITLE
No stack on assertion error in PhantomJS

### ISSUE THREAD

**Issue by mjomble** [chaijs/chai#618]
Steps to reproduce:

1. Install PhantomJS
    ```
    npm install -g phantomjs-prebuilt
    ```

2. Download the chai browser build into a dir, save it as `chai.js`.

3. Create `test.html` in the same dir with these contents:

    ```html
    <script src="chai.js"></script>
    <script>
    try {
      chai.expect(1).to.equal(2);
    }
    catch (error) {
      console.log('Stack on chai assertion error:', error.stack);
    }
    
    try {
      throw new Error('regular');
    }
    catch (error) {
      console.log('Stack on regular error:', error.stack);
    }
    
    window.close();
    </script>
    ```

4. Create `test.js` in the same dir with these contents:

    ```javascript
    var page = require('webpage').create();
    page.onConsoleMessage = console.log.bind(console);
    page.onClosing = phantom.exit;
    page.open('test.html');
    ```

5. Execute on the command line in that dir:

    ```
    phantomjs test.js
    ```

Expected result:
* Both the assertion error and the regular error have stack information.

Actual result:
* The regular error has stack information, but the assertion error's stack is undefined.

In Chrome, however, both errors have a proper stack.

Tested with chai 3.5.0 and PhantomJS 2.1.1

**Comment by keithamus** [comment]
Thanks for the issue @mjomble.

This seems to be a PhantomJS quirk. I went on a hunch that phantomjs will only apply the stack to a thrown error, which seems to be true:

```html
<!-- your test.html, modified -->
<script>
console.log('Stack from a non-thrown error', new Error().stack);
var e = new Error();
console.log('Stack from a not-yet thrown error (e)', e.stack);
try {
  throw e;
} catch(e) {
  console.log('Stack from the now-thrown error (e)', e.stack);
}
window.close();
</script>
```

```bash
$ # running with the new test.html:
$ phantomjs test.js
Stack from a non-thrown error undefined
Stack from a not-yet thrown error (e) undefined
Stack from the now-thrown error (e) global code@file:///Users/keith/test/test.html:6:10
```

[Here's how we generate stack traces within Chai](https://github.com/chaijs/assertion-error/blob/6d135142020ec38aa91c0f1fce685ed35c2c6634/index.js#L69-L74) (through the `assertion-error` module). As you see, right now we try `Error.captureStackTrace` - and if that doesn't work we just try `new Error().stack`.

The fix for this seems to be to intentionally throw an error to capture its stack, this will get stack traces working within Phantom. Essentially changing [L73](https://github.com/chaijs/assertion-error/blob/6d135142020ec38aa91c0f1fce685ed35c2c6634/index.js#L73) from:

```js
    this.stack = new Error().stack;
```
to
```js
    try {
      throw new Error();
    } catch(e) {
      this.stack = e.stack;
    }
```

Fancy making a PR in the assertion-error repo? After we merge and release we'll need to update chai.js upstream.

**Comment by mjomble** [comment]
Yep, I can make a PR.

**Comment by keithamus** [comment]
sweet :smile:

**Comment by eekboom** [comment]
When will there be a release that includes this fix?

**Comment by keithamus** [comment]
Soon @eekboom, soon.

**Comment by unruly-paul** [comment]
Any update on when this will be released? Cheers.

**Comment by meeber** [comment]
@unruly-paul This fix was released in assertion-error v1.0.2, which should be pulled in automatically when installing chai v3.5.0 via npm, as it's covered by semver. Are you still seeing missing stack traces in PhantomJS?

**Comment by unruly-paul** [comment]
Thanks for quick response @meeber.

Still missing them, but I think it was more a shot in the dark/ hope that this was the problem, especially as looking at it a bit more I think we aren't getting the error at all (let alone the stack trace...)

Running on command line it says which test failed but doesn't give error at all, although it does if we run in Chrome. We've just updated PhantomJS & Mocha, which seems to have caused it to stop working, seems like more investigation/ Googling is needed!

Thanks though.

**Comment by xcafebabe** [comment]
Hi @meeber, if you notice in line (5569)[https://github.com/chaijs/chai/blob/master/chai.js#L5569], chai.js is not using the patch from assertion-error v.1.0.2.  For instance karma-chai module use this build.

We should wait until chai.js get the update. Or do a quick workaround in your local chai module and apply patch from comment https://github.com/chaijs/chai/issues/618#issuecomment-182536178

**Comment by meeber** [comment]
@xcafebabe Yup you're right, I forgot that we don't currently regenerate the `chai.js` file on every commit to the master branch. On the plus side, we'll be releasing an alpha release of Chai 4.0 very soon that will have this change. And going forward we plan on releasing new versions more rapidly using [semantic release] (https://github.com/semantic-release/semantic-release).

An interim solution is to clone the chai repo and run `npm install && npm test` and it will regenerate `chai.js` with the patch included.
