### ISSUE TITLE
Wrong date on 3.5.0 release

### ISSUE THREAD

**Issue by mjomble** [chaijs/chai#619]
The title here - https://github.com/chaijs/chai/releases/tag/3.5.0 - is currently "3.5.0 / 2015-01-28" but should have 2016 in it :)

The date is wrong here as well: http://chaijs.github.io/chai-docs/ but I'm guessing it uses the same data source.

**Comment by keithamus** [comment]
Oh damn. Old habits die hard :stuck_out_tongue_winking_eye:. Thanks @mjomble, fixed.
