### ISSUE TITLE
Can we use two plugins on the same expectation?

### ISSUE THREAD

**Issue by Getz85** [chaijs/chai#625]
I try to use [Chai As Promised](http://chaijs.com/plugins/chai-as-promised) with [Chai Stats](http://chaijs.com/plugins/chai-stats) to test the result of a promise which is an array of objects containing number.

I tried : 
```javascript
  return expect(returnPromiseFunction().to.eventually.almost.eql(
        [{
          "id": 1,
          "percentage": 0.2886}, {
          "id": 2,
          "percentage": 0.356}], 4);
```
All my tests were ok, even if I modify the expection array to force it failed...

After that, I tried the simple equaltity:

```javascript
  return expect(returnPromiseFunction().to.eventually.almost.equal(
        [{
          "id": 1,
          "percentage": 0.2886}, {
          "id": 2,
          "percentage": 0.356}], 4);
```

And I got an error:

> AssertionError: expected { state: 'pending' } to equal [ Array(2) ] up to 4 decimal places

I assume that the 'eventually' statement (coming from chai as promised) is not compatible with the 
'almost' one (coming from chai stats)? Is it an issue with Chai, Chai AS Promised or Chai Stats? Maybe I use it the wrong way?

**Comment by meeber** [comment]
Hi @Getz85, apologies for the delay. Is this still an outstanding issue for you?
