### ISSUE TITLE
`expect.fail()` parameter order

### ISSUE THREAD

**Issue by kthelgason** [chaijs/chai#630]
In many cases where I find `expect.fail()` useful I don't have any expected and actual values. What I actually want to do is fail the test with a helpful message. Having the message as the 3rd param is IMO not intuitive and not that helpful. I get that there must have been some discussion on this, perhaps my use cases differ from the common ones. 

I get that this probably won't change, but I thought I would open up this issue anyway just for the sake of discussion :smile:

**Comment by keithamus** [comment]
Hey @kthelgason thanks for the issue.

If you want to fail a test, but don't have `expected` or `actual` - you're probably better off just throwing an error! All `expect.fail()` does is throw Chai's `AssertionError` - which is a especially extended Error class that has `expected` and `actual` values built in. An example:

```js
it('should fail', function () {
  throw new Error('this fails!');
});
```

I'll close this - as the above will work perfectly well, and is the recommended pattern. If you want to continue discussing it though, feel free! If you have any more issues you'd like to discuss feel free to open another issue :smile:

**Comment by kthelgason** [comment]
Thanks for the quick reply @keithamus.

That definitely makes sense, and is exactly what I expected `.fail` to do. I see the point of not having a library assertion to do that, I guess I just had some built-in assumptions from RSpec.

Thanks for your awesome work btw! :fire:

**Comment by alexbooker** [comment]
@keithamus Thanks for the solution.

**Comment by alexbooker** [comment]
What I  like about `expect.fail()` compared to `throw new Error()` is that it's consistent -- both in terms of its syntax and output.

Importing and throwing `AssertionError` (instead of `Error`) makes the output consistent with `expect.fail()` and makes the test a bit clearer:

```javascript
import {expect, assert, AssertionError} from 'chai'
...

throw new AssertionError('foo')
```
