### ISSUE TITLE
Uncaught Error: Wait timed out after

### ISSUE THREAD

**Issue by seleniumlucio** [chaijs/chai#631]
Hi
I am using Selenium and Chai and  have the following 
` return expect(function() {
        returnHelper.check(true);
    }).to.throw(Error);`

When calling the Function I am  getting a Uncaught Error: Wait timed out after (which is what I have expected)
How can I tell Chai to expect this Error and catch it

**Comment by keithamus** [comment]
Hey @seleniumlucio thanks for the issue.

Could you please provide me with some more details about this, perhaps make a reduced test case that I could run on my machine to figure out what is going wrong. Thanks.

**Comment by seleniumlucio** [comment]
Thanks for your quick replay
I am using Selenium with Chai : 
I am calling to 
`expect( ->
        myfunction.check(true)  
      ).not.to.throw(Error)
`
and inside myfunction I have the following : 
`driver.wait ->
      driver.isPresent(selector)
  , TIMEOUT
The selector is not exist so it will always throw a timeout exception

**Comment by lucasfcosta** [comment]
Well, your function seems to be async, so it won't be caught by simply doing:

```js
try {
  asyncFunctionThrowsError();
} catch(e) {
  console.log('this won't be printed');
}
```

You can check this by running a simple script on node:

```
function throwsErrorAsync() {
  setTimeout(function() {
    throw new Error('async error');
  }, 2000);
}

try {
  throwsErrorAsync();
} catch (e) {
  console.log('If this gets printed the error was caught');
}
```
Since this is basically what the [throw assertion](https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L1303) does your exception won't be caught by chai too.

@keithamus may be able to give you more information on how to work around this.

**Comment by keithamus** [comment]
Great, thanks @seleniumlucio and @lucasfcosta.

Looks like @lucasfcosta is right - its an async function, which Chai does not currently support. If it returned a Promise, you could use [chai-as-promised](https://github.com/domenic/chai-as-promised) but if it is async via callbacks, you'll need to assert inside the callback, perhaps like so:

```
it('should throw', function(done) {
  returnHelper.check(true, function (err, value) {
    expect(err).to.be.an('error');
    done();
  });
});
```

I'll close this - as it's not an issue that will be fixed any time soon with Chai. However, please feel free to continue the discussion and if you find any new issues with Chai, please feel free to raise them :smile:
