### ISSUE TITLE
`.to.have.ownProperty(key, value)` should work like `.property()`

### ISSUE THREAD

**Issue by ljharb** [chaijs/chai#646]
`expect({ a: 1 }).to.have.ownProperty('a', 2);` passes. `expect({ a: 1 }).to.have.property('a', 2);` fails.

It would be great to have the APIs be similar.

**Comment by lucasfcosta** [comment]
Hello @ljharb, thanks for the issue! :smile: 

This has already been done at #641 and you can see the whole discussion about this at #281.
Please let me know if you have further doubts.

**Comment by ljharb** [comment]
Yay, thanks! When might a release be cut?
