### ISSUE TITLE
Update doc?

### ISSUE THREAD

**Issue by unional** [chaijs/chai#649]
Include accepts object too:
http://chaijs.com/api/assert/#method_include
https://github.com/chaijs/chai/blob/master/test/assert.js#L435

**Comment by unional** [comment]
Also these:
- changesBy
- changesButNotBy
- decreaseBy
- decreasesButNotBy
- increasesBy
- increasesButNotBy

**Comment by lucasfcosta** [comment]
Hi @unional, thanks for the issue!
[You seem to be right](https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L180). Feel free to send us a PR at [chai-docs](https://github.com/chaijs/chai-docs) if you want to :smile:

**Comment by unional** [comment]
How to make changes to the docs? I looked at `chai-docs` it seems to be code for the site with some static contents. For this `include()`, it is pulling from the source (i.e. `/chai.js`)? Is this missing info is because `chai-docs` pickup an older version of `chai` (i.e. not at tag `3.5.0`)?

**Comment by lucasfcosta** [comment]
Oh I'm sorry, actually, the docs are auto generated.
You can find more info on how they're generated at this [Makefile](https://github.com/chaijs/chai-docs/blob/gh-pages/Makefile).

Apparently it's generated using the latest available version (at NPM):

```make
api-docs: clean-api-docs
	@mkdir -p _data
	@npm install chai@latest
	@./node_modules/.bin/dox --raw < ./node_modules/chai/chai.js > _data/chai.json
```

**Comment by unional** [comment]
Yeah, so seems like the doc was not updated at 3.5.0
Saw this commit:
https://github.com/chaijs/chai/commit/78f484a3f4e51d9c48cd3bc64a86d1276b4236f2
Which is after the release.
To fix this, probably need to do a cherry-pick.

**Comment by keithamus** [comment]
Hey all! The docs will auto generate from every new release. We just need to cut a new release of chai.

There's nothing to do here. I'll release a new version of chai shortly.
