### ISSUE TITLE
deepStrictEqual

### ISSUE THREAD

**Issue by piranna** [chaijs/chai#652]
Add support for [deepStrictEqual](https://nodejs.org/api/assert.html#assert_assert_deepstrictequal_actual_expected_message) assertion as native Node.js `assert` module does.

**Comment by lucasfcosta** [comment]
Hi @piranna, thanks for the issue!

Actually I think that this may not be a common use case, but it is useful indeed, I'm just not sure if we should implement this, although I'd say it would be worth it because all we need to do is add an `strict` flag that when used alongside `deep` changes how comparisons are done depending on the type of each one of the object's keys. This would be done [at this line on `assertions.js`](https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L486). Of course we would need some tests to back it up and to update our doc comments. 

If other people share the same opinion we may go for it, thanks again for your feedback :smile:

**Comment by piranna** [comment]
Other option to make it faster to implement is to just delegate the functionality of `deepStrictEqual` to the native Node.js `assert` module... :-D

**Comment by keithamus** [comment]
Our implementation of `deepEqual` is already strict. Well, it uses [`SameValue`](http://ecma-international.org/ecma-262/6.0/#sec-samevalue), aka [`Object.is`](http://ecma-international.org/ecma-262/6.0/#sec-object.is), so it accounts for `-+0` and `NaN`.

We could simply add an alias of `deepStrictEqual` to use `deepEqual` for method name parity with Node, but Chai still won't be a drop in replacement for Node. 

BTW, we've never had a request to make `deepEqual` less strict.

**Comment by piranna** [comment]
Ah, then it's stricter than Node.js `deepStrictEqual`, cool! :-D Then a simply alias is good for me, if in the future there's a requeriment for a less strict `deepEqual`, we can add an independent implementatation for it :-)

**Comment by keithamus** [comment]
Sounds good to me :smile:. I'll change this to PR wanted.

[Here is the code](https://github.com/chaijs/chai/blob/da741e84f70be0afcc6468e6e44df9a8fba07323/lib/chai/interface/assert.js#L200-L217) which implements `assert.deepEqual` - a PR should change L215 from `assert.deepEqual = ...` to `assert.deepEqual = assert.deepStrictEqual = ...` and then add `@alias deepStrictEqual` to the JSDoc documentation between L210/211. Probably for good measure, we should also have the tests calling the alias, so [around L207 of test/assert.js](https://github.com/chaijs/chai/blob/da741e84f70be0afcc6468e6e44df9a8fba07323/test/assert.js#L207) adding `assert.deepStrictEqual({tea: 'chai'}, {tea: 'chai'});` will be fine.

**Comment by piranna** [comment]
With the description that you have done it's mostly as you have written it, but here you have the [pull-request](https://github.com/chaijs/chai/pull/653) :-)

**Comment by lucasfcosta** [comment]
Thanks @piranna !

**Comment by piranna** [comment]
> Thanks @piranna !

You are welcome :-) Any idea when this would be published in npm?

**Comment by keithamus** [comment]
No firm dates yet. We should definitely make a new release soon though as it has been a while 😟

**Comment by piranna** [comment]
Ok, I'll try to use directly GitHub master until this get published ;-) Thank you! :-D

**Comment by camiloh95** [comment]
Correct me if I am wrong but when I try 
```javascript
import * as assert from 'assert';

assert.deepStrictEqual(
    new Error('New error message'),
    new Error('New eror message')
);
```
It works, but when I try it with chai assert it does not work. So, what do you mean when you say `deepEqual` is already strict?
