### ISSUE TITLE
Link to plugins file in README is broken

### ISSUE THREAD

**Issue by Turbo87** [chaijs/chai#657]
The link to https://github.com/chaijs/chai-docs/blob/master/plugins.js#L1-L12 in the README ("Have a plugin and want it listed? Open a Pull Request at chaijs/chai-docs:plugin.js.") is currently broken. 

I would like to get https://www.npmjs.com/package/chai-files listed, but I'm not quite sure how/where it do that.

**Comment by keithamus** [comment]
Hey @Turbo87 thanks for pointing this out. I've made #658 which fixes the docs.

As it says - you'll need to add the a`chai-plugin` keyword to your package.json. That's it :smile:

**Comment by keithamus** [comment]
Just to add - our docs pages are built at least once every 24 hours. So it can take up to 25 hours for it to be displayed on the plugins page.

**Comment by Turbo87** [comment]
@keithamus I see, thanks. I guess I'll have to wait until tomorrow then. First release was 14 hours ago :wink:

**Comment by Turbo87** [comment]
@keithamus seems to have worked: http://chaijs.com/plugins/chai-files/

thanks again! :)

**Comment by keithamus** [comment]
Sweet! High fives all round :hand:
