### ISSUE TITLE
Helper function for testing AssertionError actual and expected

### ISSUE THREAD

**Issue by meeber** [chaijs/chai#675]
Currently, there's the `global.err` helper function for testing that an AssertionError is thrown with a specific message: https://github.com/chaijs/chai/blob/4f7284662ced18700008ba491735ab4629e6f7bc/test/bootstrap/index.js#L11-L22

I see some value in creating a new helper function (or modifying the existing `global.err`) to facilitate the testing of an AssertionError's `expected` and `actual` properties. It seems important to validate these values since some assertions (such as `assertKeys`) go out of their way to sort `expected` and `actual` in a particular order.

Such validation could be done without a helper function but it'd be a lot of repeated code.

Thoughts? :D

**Comment by keithamus** [comment]
Hey @meeber thanks for the issue.

Seems like you could pretty easily extend `global.err` to also feature `actual` and `expected`. Thoughts?

**Comment by meeber** [comment]
It's nice that `global.err` expects only a string or a regex as it's second argument, allowing it to be extended to accept `undefined` as an indicator that the msg validation can be skipped, without breaking current functionality. And then it could accept optional arguments for testing `actual` and/or `expected`.

But if not passing a value for the `actual` and `expected` arguments means don't validate them against the `actual` and `expected` AssertionError properties, how would one go about validating if the `actual` and `expected` AssertionError properties were equal to `undefined`?

I suppose `arguments.length` could be checked, which should indicate if `undefined` was explicitly passed in as an argument.

Actually... How about this: `global.err` still only accepts 2 arguments, but if the second one is an object instead of a string/regex, then it validates each of the object's key/value pairs against the AssertionError's key/values?

**Comment by keithamus** [comment]
Sounds completely acceptable to me. Look forward to seeing the PR 😄
