### ISSUE TITLE
.throw()

### ISSUE THREAD

**Issue by couto** [chaijs/chai#7]
`throw` is a reserved word in Javascript, so it's quite normal for linters (jslint, jshint....) to emit warnings like `Expected an identifier and instead saw 'throw' (a reserved word).` 

In fact, during tests, Internet Explorer 7, at least, breaks due that same error.

Note: I would fork and do a pull request, however english is not my first language, and I can't find a similar word to replace `throw`while keepin its value, if someone finds a similar word, I would gladly do the pull request myself.

**Comment by yanhaijing** [comment]
The question is not going to fix it?
