### ISSUE TITLE
assert.is() should exist 

### ISSUE THREAD

**Issue by zeptonaut** [chaijs/chai#708]
It would be great if you could use `assert.is()` to compare two values based on the overridden [`Object.is()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is) function.

What are the chances of something like this being implemented?

**Comment by keithamus** [comment]
Thanks for the issue @zeptonaut. 

Curious; what are you looking for from `Object.is` that `.equal` doesn't give you?

**Comment by meeber** [comment]
Unless I'm mistaken, the only time that [same value equality](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness) is currently used by Chai is when performing a `deepEqual` assertion. It might be useful to be able to perform a same value equality comparison without the other stuff that `deepEqual` does.

Just brainstorming possible syntax and aliases:

```js
assert.sameValueEqual(val1, val2);
assert.sameValue(val1, val2);
assert.egal(val1, val2);
assert.is(val1, val2);

assert.notSameValueEqual(val1, val2);
assert.notSameValue(val1, val2);
assert.notEgal(val1, val2);
assert.isNot(val1, val2);
assert.isnt(val1, val2);

expect(val1).to.sameValueEqual(val2);
expect(val1).to.egal(val2)
expect(val1).to.not.sameValueEqual(val2);
expect(val1).to.not.egal(val2)

val1.should.sameValueEqual(val2);
val1.should.egal(val2)
val1.should.not.sameValueEqual(val2);
val1.should.not.egal(val2)
```

**Comment by meeber** [comment]
Gonna close this due to lack of discussion. I think this currently falls under the category of a niche feature, most appropriately implemented via a plugin, but I'm interested to see if `Object.is` usage increases over time.

**Comment by paulmelnikow** [comment]
This is an old issue, but it’s a useful assertion to have!
