### ISSUE TITLE
How Should I Throw?

### ISSUE THREAD

**Issue by juzerali** [chaijs/chai#71]
I tried to write `should.js` style throw statements like so `(new Bill(input)).should.throw(Error);` but its not working. Where can I find resources wherein I can checkout documentation on should assertion style?

**Comment by wangpin34** [comment]
I have read above posts and tested several times. Then got following 

* Error should throw like following
```
function throwme() {
  throw new Error('I am exception');
}
```
* Test throw like following
```
  it('It throw exception', function() {
    (function() {
      throwme();
    }).should.Throw('I am exception');
  });
```

Any better idea?

**Comment by sabrinaluo** [comment]
Hi can any one help? it's wired that for a same function, both throw and not throw pass the test

https://jsfiddle.net/8t5bf261/

```
class Person {
  constructor(age) {
    if (Object.prototype.toString.call(age) !== '[object Number]') throw 'NOT A NUMBER'
    this.age = age;
  }
  howold() {
    console.log(this.age);
  }
}

var should = chai.should();
mocha.setup('bdd');

describe('Person', function() {
  it('should throw if input is not a number', function() {
    (function() {
      var p1 = new Person('sadf');
    }).should.not.throw;

    (function(){
    var p2= new Person('sdfa');
    }).should.throw;
  })
})

mocha.run();
```

**Comment by meeber** [comment]
@sabrinaluo Try using `.should.throw()` and `.should.not.throw()` (with parenthesis).

You might also want to consider using `throw Error('NOT A NUMBER')` or even `throw TypeError('NOT A NUMBER')` in your class so that the stack is captured, though I don't think this is directly related to your issue.

**Comment by sabrinaluo** [comment]
@meeber thanks, it works for me!

**Comment by mitchellporter** [comment]
Here's two examples with cleaner syntax that work fine for me:

```
it('should pass validation', function() {
      should.not.throw(() => { model.fromJson(validJson) });
});

it('should fail validation', function() {
      should.throw(() => { mode.fromJson(invalidJson) }); 
});
```
