### ISSUE TITLE
truncateThreshold should apply to more types or the documentation should be clarified

### ISSUE THREAD

**Issue by Joris-van-der-Wel** [chaijs/chai#710]
The docs on truncateThreshold currently state:

```
config.truncateThreshold
    @param {Number}
    @default 40
User configurable property, sets length threshold for actual and expected values in assertion errors. If this threshold is exceeded, the value is truncated.

Set it to zero if you want to disable truncating altogether.

chai.config.truncateThreshold = 0; // disable truncating
```

The first statement is not strictly true because truncateThreshold only applies to objects, arrays and functions. For example:

``` javascript
chai.config.truncateThreshold = 10;
chail.assert.equal('fooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo', 'foo');

// Results in:
AssertionError: expected 'fooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo' to equal 'foo'
```

**Comment by lucasfcosta** [comment]
Hi @Joris-van-der-Wel, thanks for the issue!

Actually the truncateThreshold will be applied to `Functions`, `Arrays` and `Objects` if their representation (built by [`inspect`](https://github.com/chaijs/chai/blob/master/lib/chai/utils/objDisplay.js#L31)) exceeds the threshold, as you can see [in this file](https://github.com/chaijs/chai/blob/master/lib/chai/utils/objDisplay.js#L31).

IMO enabling truncation for `Strings` could end up in non-useful `AssertionError` messages, and in most cases they won't even exceed the threshold limit. However, I agree with you that we could document it better.

Feel free to share your thoughts, for now I'd like to just improve docs 😄

**Comment by keithamus** [comment]
There are some unwritten plans to improve our inspection utilities in various ways, including ensuring `truncateTreshold` is better respected. Watch this space 😉

**Comment by Joris-van-der-Wel** [comment]
Sure!

I would not mind a second option specifically for strings/buffers/etc. The documentation was indeed the bigger concern, I was debugging my setting of the truncate option until I came upon that inspect function. 

In my specific case I was repeatedly calling a HTTP API endpoint (performance tests), and I wanted to quickly assert that the response body contained a specific string `expect(body).to.have.string('foo');`, the response body was about 20000 characters however. Interpreting the response body would take too long.

**Comment by keithamus** [comment]
The plan is for loupe (our inspection lib) to truncate intelligently, based on the `actual` and `expected`. So if you had a `trunaceThreshold` of `10` the string `foobarbazbing` would render as `'fooba...'`, but if you compared `foobarbazbing` to `foobazbingbar` then the error message would be more like `Expected '...barba' to equal '...bazba'` (obviously `10` is not a very practical truncate threshold but it illustrates the point of showing only the differences).

The idea behind this is that truncateThreshold will A) really truncate to the specified length and B) give you better, richer, more relevant information when truncated.

**Comment by lucasfcosta** [comment]
Hi @Joris-van-der-Wel, thank you very much for this issue! 😄

Recently we have been adding our priorities to a [`roadmap` board](https://github.com/chaijs/chai/projects/2) and referencing issues there to make sure we'll get things done in a better and more organised way.

Your suggestion is much appreciated and we'll certainly take it into account when refactoring `loupe`.

For now, I'll close this in order for us to get a clean slate to work on.

Thank you very much!
