### ISSUE TITLE
Uncaught AssertionError: expected null to not equal null

### ISSUE THREAD

**Issue by sirusalazar** [chaijs/chai#712]
I have this code:

assert.isNull(null) 

and it throw this error:

 Function.assert.isNotNull (node_modules/chai/lib/chai/interface/assert.js:426:36)

**Comment by meeber** [comment]
Hi @sirusalazar. That's the correct stacktrace for a failed assertion using `assert.isNotNull`. Is there any chance you inadvertently reassigned `assert.isNull` to `assert.isNotNull` previously in your code? If not, could you provide a full standalone example that demonstrates the error? I haven't been able to reproduce it with the example provided. Thanks :D

**Comment by meeber** [comment]
Closing this for bookkeeping purposes but feel free to post if you'd like to discuss this further or can provide a reproducible example. Thanks :D
