### ISSUE TITLE
"use" doesn't behave as expected as an ES6 named export

### ISSUE THREAD

**Issue by meeber** [chaijs/chai#718]
The following code throws an error:

```js
import sinonChai from "sinon-chai";
import {expect, use} from "chai";

use(sinonChai);
```

The reason it throws an error is because the necessary `this` binding is lost when calling `use` via the above syntax as opposed to calling it via `chai.use(sinonChai)`.

I'd argue that it's unexpected and undesirable for a singleton module to utilize `this` in such a way.

One possible solution might be to change [use](https://github.com/chaijs/chai/blob/2194a89e0290a3152446995afe877d4248256c91/lib/chai.js#L38-L45) from:

```js
exports.use = function (fn) {
  if (!~used.indexOf(fn)) {
    fn(this, util);
    used.push(fn);
  }

  return this;
};
```

To:

```js
exports.use = function (fn) {
  if (!~used.indexOf(fn)) {
    fn(exports, util);
    used.push(fn);
  }

  return exports;
};
```

**Comment by lucasfcosta** [comment]
Looks good to me.
Since `this` and `exports` refer to the same object (which is the `chai` module which is being exported by this file) I can't see any other side effects for this.
Nice catch 👍

**Comment by meeber** [comment]
@lucasfcosta Thanks for checking this out. I'll prolly submit a PR after work.
