### ISSUE TITLE
@keithamus should change his username to @keithamoose

### ISSUE THREAD

**Issue by meeber** [chaijs/chai#719]
Congrats on 3,000 stars to the entire Chai community but especially @logicalparadox and @keithamus for the scary amounts of time and energy they've devoted to this project. Hopefully us new guys don't screw things up too badly!

P.S. I just got off the phone with Chai Corporate HQ. They said grats on 3k stars and if we don't hit 4k by November 1st we're all sacked.

**Comment by keithamus** [comment]
We also fairly consistently get >=2,000,000 downloads of Chai every month<sup>[[1]](http://npm-stat.com/charts.html?package=chai&author=&from=&to=#months)</sup>, and in 2016 we've had more downloads of Chai so far, than we did in the whole of 2015<sup>[[2]](http://npm-stat.com/charts.html?package=chai&author=&from=&to=#years)</sup>. Chai is also one of the most depended on packages in the npm ecosystem<sup>[[3]](https://github.com/anvaka/npmrank/blob/master/sample/dependencies.md)</sup>!

**Comment by lucasfcosta** [comment]
:tada: :tada:

Awesome work guys!
Let's celebrate releasing 4.0.0 hahahaha
It's great to contribute with such talented people, I've learned a lot with you.

PS.: +1 for the username change :laugh:

**Comment by meeber** [comment]
Closing out of disappointment due to lack of change to keithamoose.
