### ISSUE TITLE
Feature request: add 'properties' assertion

### ISSUE THREAD

**Issue by mullr** [chaijs/chai#72]
There's a pretty common case that the existing deep.equal, deep.property, and contains.keys APIs don't cover, namely asserting that an object should have some properties of some given values. Namely, I'd like to be able to say:

``` javascript
obj = {...};
expect(obj).to.have.properties({
  a: 42, 
  b: "someVal"
});
```

obj is allowed to have other properties as well, but fails if a or b is absent or has a different value. 

Here's the coffeescript I hacked up to do this locally, which barely works:

``` coffeescript
chai.Assertion.addMethod 'properties', (expectedPropertiesObj) ->
  args = ([key,val] for own key,val of expectedPropertiesObj)
  args = _.flatten(args)
  this.property.apply(this, args)
```

**Comment by Zammy** [comment]
Is there plugin that does this? I just realized I have written wrong tests (they were passing although they were not doing anything). Maybe add another base test like ".properties". I am not experienced with chai but maybe you need feedback from people like me. :) I now need to write .property for each of the properties I want to check.

**Comment by eps1lon** [comment]
`to.include` works exactly like you want:

> When the target is an object, .include asserts that the given object val’s properties are a subset of the target’s properties.
>
> expect({a: 1, b: 2, c: 3}).to.include({a: 1, b: 2});

-- https://www.chaijs.com/api/bdd/#includeval-msg
