### ISSUE TITLE
Why Aren't (Expect-styled) Assertion Messages Part of Chai?

### ISSUE THREAD

**Issue by machineghost** [chaijs/chai#722]
This issue, https://github.com/chaijs/chai/issues/81, provides an incredibly short, incredibly useful `withMessage` "plug-in" for providing additional information when an expect assertion fails.

But the thing is, the "assert" style (which I thought was supposed to be functionally equivalent to the "expect" style)  already has custom messages built-in:

    assert('foo' !== 'bar', 'foo is not bar');

And why shouldn't it: the entire point of an assertion library is to let you know when/why a test failed, right?

So my question is: why isn't the `withMessage` "plug-in" part of the core library?  It would bring the "expect" style up to feature parity with the "assert" style, would add virtually nothing to the file size, and would enable more informative test failures.  What's not to like?

**Comment by machineghost** [comment]
Never mind, just discovered the optional message arguments to many of the "expect" style assertions.  It would be nice if those arguments were included in the documentation examples though.  As it is currently it's very easy to gloss over the one small line in the parameters section (I've read that page several times and only just today discovered the optional message arg).

**Comment by meeber** [comment]
@machineghost It's also possible to do this:

```js
expect(42, "my custom err message").to.equal(43);
```

Agreed on doc examples.

**Comment by jpike88** [comment]
The docs are inconsistent and need to be updated to reflect this.

I found the only way to get it working was:

`chai.config.includeStack = true;`
