### ISSUE TITLE
Map deepEquals always returns true

### ISSUE THREAD

**Issue by dpwrussell** [chaijs/chai#730]
It seems that `deepEquals` is not working correctly for Map (or whatever that is being transpiled into by babel)

```js
    it('Dummy map test', () => {

      const beforeState = new Map([[1, 'a'], [2, 'b']]);

      // Any one of these will be considered deeply equal
      // This one correctly equal
      // const afterState = new Map([[1, 'a'], [2, 'b']]);
      // None of these ones are correct
      // const afterState = new Map([[1, 'a'], [2, 'c']]);
      // const afterState = new Map([[1, 'a'], [3, 'b']]);
      const afterState = new Map();

      chai.assert.deepEqual(beforeState, afterState);
    });
```

Test run like so:
```sh
$ node_modules/mocha/bin/mocha --compilers js:babel-core/register
```

Result:
```sh
✓ Dummy map test
```

**Comment by meeber** [comment]
@dpwrussell Thanks for posting! This is a known issue in the deep-eql module used by Chai but is actively being worked on as part of a major refactor. Status of that issue can be tracked at https://github.com/chaijs/deep-eql/issues/4. Gonna close this one as a duplicate.
