### ISSUE TITLE
Throw error not working

### ISSUE THREAD

**Issue by jeremyrajan** [chaijs/chai#747]
Hi,

I am trying to catch the error which my script throws in my tests but chai doesnt seem to accept. Following is my code:

```javascript
config = null; // I am checking for null in the code and throwing an error
expect(() => script.run(cap, mock, config)).to.throw(/No configuration has been supplied/);
```

I googled and tried various options but still the same. Any help with be highly appreciated.

Cheers!

**Comment by lucasfcosta** [comment]
Hi @jeremyrajan, thanks for the issue!
Assuming your method is really throwing an error and it is not async, it should have been working.
Is `script.run` async?
Can you please provide the output of the assertion?

**Comment by jeremyrajan** [comment]
Hi @lucasfcosta , I assume it is not async as I have no callbacks attached to the function being called.

The error looks something like this:
```
Error: No configuration has been supplied
    at run (/Documents/Projects/Github/script-core/src/index.js:14:11)
    at Object.e [as run] (/Documents/Projects/Github/script-core/src/index.js:60:5)
    at expect (/Documents/Projects/Github/script-core/testing/unit_tests/index.test.js:41:30)
    at Assertion.assertThrows (/Documents/Projects/Github/script-core/node_modules/chai/lib/chai/core/assertions.js:1300:7)
    at Assertion.ctx.(anonymous function) [as throw] (/Documents/Projects/Github/script-core/node_modules/chai/lib/chai/utils/addMethod.js:41:25)
    at Context.it (/Documents/Projects/Github/script-core/testing/unit_tests/index.test.js:41:108)
    at callFn (/Documents/Projects/Github/script-core/node_modules/mocha/lib/runnable.js:326:21)
```

Thank you :)

**Comment by meeber** [comment]
@jeremyrajan Code looks fine to me. Gonna need a complete standalone example to troubleshoot. Could you recreate the issue in a small public github repo for us to see?

**Comment by jeremyrajan** [comment]
If it makes a difference, the func is inside a try catch. As in:

```javascript
const runParent = (cap, window, client, config, features) => {
  try {
    run(cap, mock, config);
  } catch (e) {
    console.log(e);
  }
};
```

Not sure, if that affects.

**Comment by meeber** [comment]
If the thrown error is being caught in a `try`, then it would not be caught by Chai's `.throw` assertion.

**Comment by jeremyrajan** [comment]
ahhh ok! Any other way I could test it without exposing the method?

**Comment by meeber** [comment]
Depends what you're trying to do. What is your purpose for catching the error with `try`? Are you intending on handling and/or recovering from the error in some way within the `catch`? If so, it might be appropriate to test whatever the result of handling/recovering from the error is, as opposed to directly testing that the error was thrown.

**Comment by jeremyrajan** [comment]
Yes, to handle the error. As in send it to out logging systems if anything. Actually, I am running the parentRun which calls the child run function. Since I have exported it in my tests.

For ex:

```javascript
const runParent = (cap, window, client, config, features) => {
  try {
    run(cap, mock, config);
  } catch (e) {
    console.log(e);
  }
};

module.exports = {
  run: runParent
};
```

And in my tests. I am exporting the mod and then running the parent Func. If that makes sense :)

**Comment by meeber** [comment]
So right now your code prints the error to console and then swallows the error so that the rest of your program continues on unaware that an error even occurred. Is it your intention for the error to be swallowed in this way after being logged?

If not, then you'd want something like this:

```js
try {
  run(...);
} catch (e) {
  someSynchronousLoggingCall();
  throw e;
}
```

In the above case, the Chai `.throw` assertion would work as expected.

If it is your intention to swallow the error after logging it, then your best bet would probably be to create a logging module, and then stub out the logging method with something like [Sinon](http://sinonjs.org/docs/) , and then assert that the stubbed logging method was called with the error.
