### ISSUE TITLE
Cannot use chai with Rollup

### ISSUE THREAD

**Issue by StreetStrider** [chaijs/chai#748]
It seemes that I cannot use Chai's `expect` with Rollup (and possible other interfaces as well) due to the very dynamic manner of [Chai's instance constructing](https://github.com/chaijs/chai/blob/cc7799c41662f1cb07897919b9041a3a963a3eb1/lib/chai.js).

Is there any known workaround or better practice to use Chai with such very static bundlers like Rollup? Or maybe an es6-version of Chai lives somewhere?

**Comment by meeber** [comment]
@StreetStrider I haven't used Rollup before. Do you have a public repo on github where you ran into the problem? Or would you be willing to create a standalone example that demonstrates it?

**Comment by StreetStrider** [comment]
@meeber I'll work on reproducible example.

**Comment by StreetStrider** [comment]
@meeber [here](https://github.com/StreetStrider/chai-rollup-issue) is a minimal stand. `npm run rollup` to attempt to bundle.

**Comment by meeber** [comment]
@StreetStrider Thanks that helped a lot.

The error is caused by [this line](https://github.com/chaijs/deep-eql/blob/b509572ca88f6a24df9ca6b301bc84998267977e/lib/eql.js#L18) in the [deep-eql](https://github.com/chaijs/deep-eql) package. The offending line is being removed per https://github.com/chaijs/deep-eql/pull/14. Therefore, this issue should be fixed with the upcoming Chai 4 release! :D

**Comment by StreetStrider** [comment]
@meeber, thanks for investigation. Shall I try Chai's `master` or deep-eql's `keithamus:giant-refactor` to ensure everything is ok?

**Comment by meeber** [comment]
I'd say comment out that line in deep-eql in your node_modules and see if that fixes the problem on your main project. (Neither Chai's master branch nor the giant-refactor are ready to go yet.)

**Comment by StreetStrider** [comment]
@meeber everything working. Thank you for your help and tips.
I look forward to use updated Chai.

**Comment by StreetStrider** [comment]
attach [repo with case](https://github.com/chaijs/chai/files/352511/chai-rollup-issue.tar.gz) for history

**Comment by FezVrasta** [comment]
Any chance to get a fix for the current 3.5.*?

**Comment by keithamus** [comment]
@FezVrasta unlikely, sadly. Chai 3.5 supports older versions of node, where `Buffer` is a `Buffer` - chai 4.0 supports versions of Node where `Buffer` is really a `UInt8Array` and so we dont need to support `Buffer` specifically. That was part of the large refactoring of deep-eql, and backporting it would require a lot of work; to the point where I would say it is not worth the effort.

**Comment by FezVrasta** [comment]
Ok thanks for the info!
