### ISSUE TITLE
ES2015 generators are not considered functions by assert.isFunction

### ISSUE THREAD

**Issue by zzzzBov** [chaijs/chai#749]
Generators have a type of `generatorfunction` from [type-detect][1], which causes `isFunction` to fail despite generators being a type of function.

This is probably best shown with an example:

```
const assert = require('chai').assert;

describe('generators', function () {
  it('should be considered functions', function () {
    assert.isFunction(function*(){}); //fails
  });
});
```

Consider updating `isFunction` to use something along the lines of `fn instanceof Function`.

Alternatively consider adding an `isGenerator` function.

[1]: https://github.com/chaijs/type-detect/

**Comment by meeber** [comment]
@zzzzBov Thanks for the issue. Looks like this is already resolved with the upcoming release of chai v4 (which uses type-detect v2). Can verify via `npm install https://github.com/chaijs/chai`.
