### ISSUE TITLE
Mention on Totally Tooling Tips

### ISSUE THREAD

**Issue by gauntface** [chaijs/chai#764]
I'm a big fan of Chai for assetions and would like to mention it on Totally Tooling Tips, is this ok with the org / project?

(Totally Tooling Tips is a Video series me and Addy Osmani do here: https://www.youtube.com/watch?v=IWgNn1kqrsA&list=PLOU2XLYxmsILKwwASNS0xgfcmakbK_8JZ)

Cheers,
Matt

**Comment by keithamus** [comment]
Hmmmm.... mmmm, uuuhhhhh.. yeah totally! Let us know if you want any info from us!

**Comment by meeber** [comment]
@gauntface Just in case you need to say it during the  course of the video, be advised that @keithamus is pronounced "keith-a-moose". This is very important.

**Comment by gauntface** [comment]
Lol thank you everyone :)
