### ISSUE TITLE
Merge 4.x.x branch into master

### ISSUE THREAD

**Issue by meeber** [chaijs/chai#772]
@keithamus @lucasfcosta I'm headed to the opposite side of the world on Thursday and am gonna be stuck in airplanes for a ridiculous amount of time. That means I need a big project to keep me occupied :D

I'd like to take the opportunity to merge the 4.x.x branch into master in preparation for the canary release. Any objections? If no objections, any suggestions? I've never merged two branches together with this substantial of a commit difference (250ish and counting). Would it better to rebase the 4.x.x branch using the master branch? Or perform a traditional merge? Or some other approach? I realize that either way there's gonna be a conflict resolution stage, but I'm a bit fuzzy on the github flow for this kind of operation.

Thanks :D

**Comment by vieiralucas** [comment]
@meeber @lucasfcosta @keithamus 
Just want to remember you guys to not release 4.0.0 before https://github.com/chaijs/chai/issues/691 is closed.

Thanks

**Comment by keithamus** [comment]
No objections. Good luck and god speed, brave @meeber

**Comment by lucasfcosta** [comment]
I think a rebase would be cleaner, but I'm not sure it is the ideal way of getting those two branches together. I feel like a traditional merge would be optimal choice here, given the big commit difference. However, I'm not very experienced with it, cause I've never done such a big merge.

Anyway, good luck with that merge and have a good time on your plane :smile: 
Let me know if you need anything.

**Comment by meeber** [comment]
Still on vacay. Forgot to fetch the 4.x.x branch before my flight here and, unlike last time I flew, I couldn't get even 5 minutes of Internet during the flight. Will better prepare for the flight back this weekend and try to knock this out!

**Comment by keithamus** [comment]
First and foremost @meeber - enjoy your vacation! Here's a handy to-do for you to keep up with this:

 - [ ] enjoy vacation
 - [ ] spend quality time
 - [ ] everything else important to you personally
 - [ ] work on merging 4.x branch
