### ISSUE TITLE
minor warnings under firefox / jslint?

### ISSUE THREAD

**Issue by gregglind** [chaijs/chai#775]
when using chai, firefox has several minor complaints

```
console.log: shield-studies-addon-utils: [JavaScript Warning: "TypeError: variable obj redeclares argument" {file: "resource://gre/modules/commonjs/toolkit/loader.js -> resource://shield-studies-addon-utils/node_modules/chai/lib/chai/utils/expectTypes.js" line: 26 column: 6 source: "  var obj = flag(obj, 'object');
"}]
console.log: shield-studies-addon-utils: [JavaScript Warning: "TypeError: variable msg redeclares argument" {file: "resource://gre/modules/commonjs/toolkit/loader.js -> resource://shield-studies-addon-utils/node_modules/chai/lib/chai/assertion.js" line: 105 column: 10 source: "      var msg = util.getMessage(this, arguments)
"}]

```

These would have been cause by using `eslint` with `no-redeclare`:  <http://eslint.org/docs/rules/no-redeclare>

## Solution

- I will happily submit a patch in about 2 minutes to fix it :)
- perhaps consider incorporating an `eslint` step in the build / deploy process.

Thanks!

GL

**Comment by gregglind** [comment]
```
50278 glind ~/gits/chai [git:775-no-redeclare?]$ eslint "lib/**"

/Users/glind/gits/chai/lib/chai/assertion.js
  107:11  error  'msg' is already defined  no-redeclare

/Users/glind/gits/chai/lib/chai/core/assertions.js
  1763:11  error  'subject' is already defined  no-redeclare

/Users/glind/gits/chai/lib/chai/utils/expectTypes.js
  26:7  error  'obj' is already defined  no-redeclare

/Users/glind/gits/chai/lib/chai/utils/inspect.js
  135:9  error  'name' is already defined        no-redeclare
  136:9  error  'nameSuffix' is already defined  no-redeclare

✖ 5 problems (5 errors, 0 warnings)
```

**Comment by lucasfcosta** [comment]
Hi @gregglind, thanks for the issue and the PR! I've seen where you work at your GitHub Profile and I'd like to inform you that you currently achieved one of my life goals, which is to work for Mozilla :smile: 

Well, regarding the issue, we already thought about that and we also talked about it [here](https://github.com/chaijs/chai/issues/737#issuecomment-229646757). But, summarizing, we do plan to add it to our code, but we are planning to move everything we can to separate repositories and to that there (as @keithamus said on the comment I linked). However I feel like we could already start using it, maybe even before `4.x.x`.

@meeber @keithamus What do you think about it? Maybe we could reuse the `.eslintrc` files we've got for other ChaiJS repos.

Thanks again for getting in touch, keep up with the good work you guys are doing at Mozilla, you are my heroes.

**Comment by gregglind** [comment]
@lucasfcosta, we are always hiring and Brasileiros are welcome!  gregglind@m.....com if you want to get in touch!

**Comment by keithamus** [comment]
I'd very much like to get eslint working, but IMO I feel like we're better off focussing on splitting out the modules, as each one can be written with a standard code style in mind - than by trying to refactor this codebase to only eventually split it out later.
