### ISSUE TITLE
Deep property equality testing?

### ISSUE THREAD

**Issue by domenic** [chaijs/chai#78]
I have recently written a few tests like this:

``` js
serverRequest.should.have.property("customerId", "abc");
serverRequest.should.have.property("clientId", "123");
serverRequest.should.have.property("scope");
serverRequest.scope.should.deep.equal(["foo", "bar"]);
```

Those last two lines are sad, but necessary since `property` does strict equality testing.

I was thinking maybe we should add a third boolean argument to `property`, that will do deep equality if true? Then it'd be

``` js
serverRequest.should.have.property("customerId", "abc");
serverRequest.should.have.property("clientId", "123");
serverRequest.should.have.property("scope", ["foo", "bar"], true);
```

I guess this is also a case for the `properties` assertion of #72, heh.

Thoughts?

**Comment by glenjamin** [comment]
I know this is an old thread - but is there any equivalent of the above for the `assert()` API?
