### ISSUE TITLE
Rephrase old docs and use `target <type>` instead of  `<type> target`

### ISSUE THREAD

**Issue by lucasfcosta** [chaijs/chai#792]
Like Mr. @meeber noticed here and [here](https://github.com/chaijs/chai/pull/783#discussion_r78267204) we've got some doc comments with a phrasing that does not seem good, so a PR fixing all the places where `<type> target` is used instead of `target <type>` would be welcome.
This happens in places like [here, for example](https://github.com/chaijs/chai/blob/4.x.x/lib/chai/core/assertions.js#L507).

**Comment by zoeingram** [comment]
Hi! Is it ok if I contribute on this? It would be my first PR.  Thank you!

**Comment by nithmanoj** [comment]
I will love to submit this as my first pull request, please review task - change `<type> target` to `target <type>`. Pls note that I will not be changing `chai.js` file of main directory as told in guidelines.
