### ISSUE TITLE
Various bugs in the deepEqual algorithm

### ISSUE THREAD

**Issue by ghost** [chaijs/chai#793]
Hey! There are various bugs in your deepEqual algortihm, and a lot of features aren't support.  E.g. ES2016 lacks support. I mention some of it here in my own algorithm:
https://github.com/Kflash/boogy#boogy-vs-other-deepequal-algorithms

If you try to compare symbols you get this thrown at you: `TypeError: Cannot convert a Symbol value to a string`

**Comment by meeber** [comment]
@Kflash Chai's deep-equal is undergoing a tremendous refactor over [here](https://github.com/chaijs/deep-eql/pull/14). It's the last major feature we have planned for the upcoming release of Chai 4.0. @keithamus can speak to it better than I if the planned refactor covers the issues you've identified in the current Chai.

**Comment by Kflash** [comment]
@meeber I looked at it. Seems to cover some of it, but not sure of it's cover the circular references etc I also discovered earlier.

**Comment by keithamus** [comment]
Yes, the new deep-equal should support all types. Hopefully it will make it into 4.0 and will solve this issue, but let's keep it open for now.

**Comment by meeber** [comment]
This was addressed in the latest deep-eql release.
