### ISSUE TITLE
Is there a way to show a custom error with expect syntax?

### ISSUE THREAD

**Issue by ghost** [chaijs/chai#81]
When you use expect, errors are not always easy to interpret, especially if you have several different expects that compare similar values, e.g.: 

expect(a).to.be.true;
expect(b).to.be.true;

Now, if a or b is false, the error message shown is:
expected false to be true

with no way to determine which of the expects caused the error.

It would be nice to be able to add a custom error message, although I'm not sure about a workable syntax. Maybe this could work:

expect(a).to.be.true.else.showMessage('expected a to be true, but it was false');
expect(b).to.be.true.else.showMessage('expected b to be true, but it was false');

So now if a is false, the error shown will be:
expected a to be true, but it was false.

This might be solvable by creating a plugin, but I've not really looked into that.

**Comment by demisx** [comment]
@logicalparadox I think you meant `includeStack`

```js
chai.config.includeStack = true;
```

**Comment by snoblenet** [comment]
This is great but how to you stop the default error message displaying when add a custom message?

**Comment by santiagodoldan** [comment]
@snoblenet were you able to strip out the default error message?

**Comment by snoblenet** [comment]
@santiagodoldan no sorry

**Comment by dheerajbhaskar** [comment]
@logicalparadox hey there Jake, would you mind updating the guide for expect to also mention that you can pass in the message in the beginning (in expect) and in the end (in asserions; for assertions which are methods). For example:

```
expect(actual, 'message').to.include(expected);
expect(actual).to.include(expected, 'message');
expect(actual, 'message').to.be.true;
```

**Comment by esalling23** [comment]
Though this is closed, this link to the chai documentation goes over creating new assertions that can have custom messages *and* overwrite the `AssertionError` messages: https://www.chaijs.com/guide/plugins/#composing-an-assertion

**Comment by frederikheld** [comment]
Is there any way to get this plugin working if I use _should_ this way?
```js
const chai = require('chai')
const should = chai.should()

[...]
should.withMessage('alternative message').not.exist(foo.bar)
[...]
```

This throws a TypeError

```cmd
     TypeError: should.withMessage is not a function
```

UPDATE:
Thanks to @dheerajbhaskar I got it working like this:

```js
const chai = require('chai')
const should = chai.should()

[...]
should.not.exist(foo.bar, 'alternative message')
[...]
```

But it's less self-explanatory IMHO so I would prefer the alternative above. Any ideas?
