### ISSUE TITLE
chai.js is stale

### ISSUE THREAD

**Issue by ckedwards** [chaijs/chai#811]
I was trying to figure out why I wasn't seeing stack traces in PhantomJS with chai. After some research I noticed that it has been fixed (#618) but it is still missing from chai.js. It is not practical to have us "clone the chai repo and run npm install && npm test"  on our jenkins servers whenever we run our tests. With the current situation it is impossible to debug intermittent crashes that occur on the server.

Is there any way this file could be regenerated?

**Comment by meeber** [comment]
Yeah this is definitely a big issue. Good news is, we'll be releasing an alpha version of v4.0 soon which will include a regenerated chai.js. It'll be available through npm. Going forward, we'll be releasing way more frequently, most likely via [semantic release](https://github.com/semantic-release/semantic-release).

**Comment by ckedwards** [comment]
How soon is very soon? You said very soon a over month ago. I'm not complaining, just curious.
