### ISSUE TITLE
Opening Issues before PRs and General Contribution Workflow

### ISSUE THREAD

**Issue by lucasfcosta** [chaijs/chai#826]
I'd just like to talk all the maintainers about all the PRs we've got and how our contribution workflow should work.

Currently we have several PRs and this made me think that maybe we should start opening issues before sending PRs with changes that have not been discussed before in order for everyone to share their ideas and try having the best implementation possible if we all agree on the change that is going to be made. What do you guys think?

Also, having issues helps us keep track of what should be done and keep discussion there instead of keeping it inside PRs. Not every PR would need an issue, of course, it should just have been discussed before if it's not a fix or anything like that. IMO.

Not having issues for debating changes before they are made makes it more difficult to understand the context of changes after they've been done and does not allow everyone to share their thought before implementing something.

Also, it's important that these issues contain detailed description of what's going to be done, in order for everyone to understand and give constructive feedback.

Please let me know whether you agree or not, I'd love to hear your thoughts on this so we can find an optimal solution :heart:

**Comment by keithamus** [comment]
Yes very much agreed. I think we don't need a _new issue_ for every PR, but at the very least a comment on an issue which branches out into a PR.

**Comment by lucasfcosta** [comment]
Well, I think we already agreed on this, so let's just close this one and keep the issue tracker clean.
Thanks everyone, our contributors are awesome!
