### ISSUE TITLE
eql fails on ES 6 maps

### ISSUE THREAD

**Issue by mbarchfe** [chaijs/chai#827]
Hello,

It seems as if comparing es6 maps is not supported yet. Otherwise I would expect the following test to be succeed. However, it fails in the last line.
Is there any workaround?
Thanks
Markus

`import {Map} from 'es6-shim'
var chai = require('chai')

describe('chai', () => {

    it('can compare ES 6 maps', () => {
      let a = new Map<string, string>()
      a.set("x", "y1")
      let b = new Map<string, string>()
      b.set("x", "y2")
      chai.expect(a.get("x")).to.not.equal(b.get("x"))
      chai.expect(a).to.not.eql(b)
  });

});
`

**Comment by lucasfcosta** [comment]
Hello @mbarchfe, thanks for the issue!
Well, we're just about to release  `4.x.x` and that will include [a big refactor](https://github.com/chaijs/deep-eql/pull/14) of [`deep-eql`](https://github.com/chaijs/deep-eql), which is what we use to make deep comparisons and that should be enough to fix your problem. Stay tuned for our `canary` release, it should happen soon, we're planning things at #457!

Also, for now you can iterate through your map and check it's elements, I know it's not the best way to do it, but it will work until we get the new version out.

Please let me know if you need anything else or have any doubts.
Have a nice day :smile:

**Comment by mbarchfe** [comment]
Thanks. Looking forward to the next release.
