### ISSUE TITLE
.eql() is broken with ES6 class

### ISSUE THREAD

**Issue by jumperchen** [chaijs/chai#831]
For example,
```
class A {
    constructor(value) {
        this.value = value
    }
}
class B {
    constructor(value) {
        this.value = value
    }
}

chai.expect(new A('A')).eql(new B('A')); // will be true
```
The result will be true, but it should not be.
The issue seems to be caused by [this line (objectEqual)](https://github.com/chaijs/chai/blob/c9cb468b019aba7d71c344d2111ce0ad3010053a/chai.js#L5829)
The instance in ES6 has no the property  *prototype*, but *\__proto__*

**Comment by jumperchen** [comment]
You may use [Object.getPrototypeOf()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getPrototypeOf) instead.

**Comment by meeber** [comment]
@jumperchen Thanks for the issue. This is fixed in the upcoming v4 release of Chai via https://github.com/chaijs/deep-eql/pull/14.

**Comment by jumperchen** [comment]
Okay, so when will v4 be released?
