### ISSUE TITLE
Logo Refresh

### ISSUE THREAD

**Issue by keithamus** [chaijs/chai#845]
Hey all,

Our logo is not in the best formats across the site right now. I've taken the time to update it to an SVG format, and also at the same time try to generate a simpler style, with punchier colours, and have a small system for re-using the logomark across our modules. All in all this is a minor logo update, just slightly modernising and also having some SVGs to work with.

I'd love to get some feedback on what I've done - and also open the floor up to see if anyone else wants take the chance to iterate on our logo design.

So to start this all off see below - click for SVG version:

---

[![logo](https://cloud.githubusercontent.com/assets/118266/19454969/23cd389c-94b3-11e6-8b38-d3753f667010.png)](https://gist.github.com/keithamus/3d8cfbaeddf8bdf5f7cd94a3bdae0934)

**Comment by shvaikalesh** [comment]
Looks nice, very well designed. Awesome job. However, I would prefer Chai logo on GitHub to be without `#fffefa` background.

**Comment by keithamus** [comment]
The `#fffefa` is the top of the gradient btw - the background should be transparent.

**Comment by keithamus** [comment]
Just for quick reference, this is the current logo:

![](https://camo.githubusercontent.com/431283cc1643d02167aac31067137897507c60fc/687474703a2f2f636861696a732e636f6d2f696d672f636861692d6c6f676f2e706e67)

**Comment by lucasfcosta** [comment]
This looks awesome!
I totally loved it.

Also, I'd like to have some stickers with our logo, what do you guys think?
I'm going to a lot of conferences lately and I'd love to distribute them to the friends there (for free, obviously I would pay the production cost, which is not expensive in Brazil btw).

**Comment by meeber** [comment]
me like

**Comment by vieiralucas** [comment]
Looks amazing! Awesome job!

I want stickers to! 😸

**Comment by lucasfcosta** [comment]
Hey everyone!

Since me and @keithamus have been doing some house-cleaning, I'll close this one for now.

We'll make sure that we have awesome stickers for everyone when Chai v5 is around!

Love you all ❤️
