### ISSUE TITLE
Allow checking for non-standard errors in throw

### ISSUE THREAD

**Issue by sorgloomer** [chaijs/chai#851]
Hi there,

We have an application where we throw custom error objects with custom fields for various reasons. Is there any way to check for those custom fields? Something like:

    expect(() => { throw { code: "Foo" }; }).to.throw(e => e.code === "Foo");

**Comment by meeber** [comment]
The `throw` assertion changes the subject to the error that was thrown, so you could do like:

```js
expect(myFn).to.throw(MyCustomError).with.property("code", "foo");
```

**Comment by sorgloomer** [comment]
I was looking definitely for something like this. I will try it tomorrow. Thanks @meeber !

**Comment by sorgloomer** [comment]
Thank you very much, works like a charm!
