### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by callicles** [chaijs/chai#853]
Hey Guys!

Maybe I did not look at the right place but I could not find the distribution license for chai.
Could you point me to it?

Thank you,

**Comment by meeber** [comment]
Whoops, looks like it got removed from the README by a recent PR but we still need to add a LICENSE file to compensate. It's still listed in the package.json as MIT. Thanks for the heads up!

**Comment by keithamus** [comment]
Sorry that was my fault! A quick PR inbound to fix!
