### ISSUE TITLE
Using chai assert returns object is not a function

### ISSUE THREAD

**Issue by Blackclaws** [chaijs/chai#861]
I'm currently stuck at a rather simple testcase. 

I import mocha, chai, chai-enzyme and sinon. However this fails.

	Object is not a function (evaluating '(0, _chai2.default)(false)')

For the simple

assert(false); 

statement.

My imports look like:

import { beforeEach, afterEach } from 'mocha';
import assert from 'chai';

import sinon from 'sinon';

I'm running the whole thing using Karma.

Any clue what might be going wrong?

**Comment by meeber** [comment]
```js
import {assert} from 'chai';
```

**Comment by Blackclaws** [comment]
Ok.... I now just feel really stupid. Damn default imports

**Comment by lucasfcosta** [comment]
Hi @Blackclaws, thanks for your issue!
Actually, `chai` exports a single object and assert as one of its keys, so just using `import {assert} from 'chai'` might solve your problem.
