### ISSUE TITLE
Object have a property or an empty object assertion.

### ISSUE THREAD

**Issue by RidgeA** [chaijs/chai#867]
Hello!

My method returns either an object with some (predetermined) property or an empty object.

How I can make such assertion in BDD style (exept using ".satisfy" :-) )?

I need something like this: 
```
expect(foo).to.have.all.key('bar').or.to.be.deep.equal({})
```

**Comment by meeber** [comment]
@RidgeA I recommend against writing tests that assert on multiple outcomes. Please check out [my comment](https://github.com/chaijs/chai/issues/620#issuecomment-217957971) in this thread.

In your example, I recommend writing two separate tests. The first test sets up the specific conditions that leads to the method returning an object with the `bar` property, and then tests that the object is indeed returned under those conditions. The second test sets up the specific conditions that leads to the method returning an empty object, and then tests that an empty object is indeed returned under those conditions.

**Comment by RidgeA** [comment]
Okey, thank you!
