### ISSUE TITLE
Suppress chai outputting error string in test results when using assert.throws?

### ISSUE THREAD

**Issue by MidnightDemon** [chaijs/chai#873]
When I create error objects and use assert.thows, I see junk data show up in my test results.
I can't find an option to turn this off.  Is there one?

example..

exception: [Error: Another error here]
    ✓ should pass the error through to the callback and rethrow

**Comment by meeber** [comment]
@MidnightDemon Can you provide a small reproducible example of the issue you're running into? I haven't run into this issue before.

**Comment by MidnightDemon** [comment]
Cleaned out my dependencies and that seems to have fixed it.  Quite strange.
