### ISSUE TITLE
should.not.exist(err) timing out

### ISSUE THREAD

**Issue by zeg-io** [chaijs/chai#879]
The following is a super-simple test which is failing for me.  Basically the should.not.exist(err) is timing out and going nowhere.

The error is caught but the `done()` never gets executed.

```js
var Promise = require('promise'),
    should = require('chai').should();

var fakeResponse = {
  status: function (code) {
    return this;
  },
  json: function (jsonObj, failIt) {
    if (failIt) {
      return Promise.reject({
        errorCode: 1000,
        message: 'You forced me to do it'
      });
    } else {
      return Promise.resolve(jsonObj);
    }
  }
};

describe('Test Promise', function () {
  it('calls a promise', function (done) {
    fakeResponse.json({ test: true }, true)
    .then(function (obj) {
      obj.should.be.a('object');
      obj.test.should.equal(true);
      console.dir(obj);
      done();
    }).catch(function (err) {
      console.dir(err);
      should.not.exist(err);
      done();
    });
  });
});
```

**Comment by zeg-io** [comment]
Additional (questionably) helpful information.
When I run mocha in debug mode within Webstorm it just spins, and if I stop it I get the following error:

```
/usr/local/bin/node[2357]: ../src/debug-agent.cc:150:void node::debugger::Agent::Stop(): Assertion `(err) == (0)' failed.
 1: node::Abort() [/usr/local/bin/node]
 2: node::RunMicrotasks(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 3: node::debugger::Agent::~Agent() [/usr/local/bin/node]
 4: node::debugger::Agent::~Agent() [/usr/local/bin/node]
 5: node::Environment::~Environment() [/usr/local/bin/node]
 6: node::Start(int, char**) [/usr/local/bin/node]
 7: start [/usr/local/bin/node]
 8: 0xb
```

**Comment by meeber** [comment]
@zeg-io In your code, if the `should.not.exist(err)` assertion throws an error, then it'll be swallowed by the promise, thus `done()` will never run, and Mocha will never know that an error was thrown or that the test ended, thus resulting in the time out.

There are two ways to work with Mocha when using Promises. One way is to use `done` which as you've found out will give you problems in this scenario. The other way is to return the promise from within the test; this will notify Mocha that you're working with an async test, and it'll be able to handle the rejected Promise properly.

Example:

```js
describe('Test Promise', function () {
  it('calls a promise', function () {          // Removed done from args
    return fakeResponse.json({ test: true }, true)      // Added return statement
    .then(function (obj) {
      obj.should.be.a('object');
      obj.test.should.equal(true);
      console.dir(obj);
      // removed done
    }).catch(function (err) {
      console.dir(err);
      should.not.exist(err);
      // removed done
    });
  });
});
```

**Comment by zeg-io** [comment]
@meeber, you, sir, rock!

That was not only the correct answer, you explained exactly the reason for the error and provided corrected and commented code!

Thank you!

**Comment by meeber** [comment]
You're welcome. Happy to help!
