### ISSUE TITLE
Evaluate failure message only on failures

### ISSUE THREAD

**Issue by itaied246** [chaijs/chai#888]
I am testing `GraphQL` in my node app.
I want to assert that no errors occurred during a specific execution. 
I validate it as follows:

`expect(result.errors).to.not.exist;`

But I'm getting the useless error message:

`AssertionError: expected [ Array(1) ] to not exist`

So I tried to edit the error message like this:

`expect(result.errors, result.errors[0].message).to.not.exist;`

Now, when the query fails I can see the exact reason (`GraphQL` write the error in this path), but now when the query passes I get the following error, because errors is null:

`TypeError: Cannot read property '0' of undefined`

Is there a way to evaluate the error message only when the test actually fails?

**Comment by shvaikalesh** [comment]
Hey @itaied246, thanks for the issue.

In JavaScript, function arguments are eagerly evaluated (contrary to Haskell, for example) before the call actually happens. So there is nothing Chai can do about this.

**Comment by itaied246** [comment]
Can you help me think of a solution for this?
How can I display the error graphql outputs and avoid the TypeError?

**Comment by shvaikalesh** [comment]
You can leverage ES6 destructuring and use `.empty` assertion like this:

```js
let { errors = [] } = result
let [{ message } = {}] = errors

expect(errors, message).to.be.empty
```

**Comment by shvaikalesh** [comment]
Also you can use `lodash#get` for `result.errors[0].message` or more advanced solution like https://github.com/jasonmcaffee/nn

**Comment by itaied246** [comment]
Thanks, I think for now I will use the ES6 destructuring, but I really liked the nevernull, I will give it a shot later on.
