### ISSUE TITLE
Ability to check non-enumerable keys

### ISSUE THREAD

**Issue by dortonway** [chaijs/chai#894]
I have non-enumerable methods and I want to check their existence. I can't do it like so: `expect(object).to.include.key('function1');`
because chai checks the inclusion only in enumerable keys, but It looks not obvious.

So I have to do something like this:
`expect(object.function1).to.be.not.undefined);`

What do you think if we would get keys not by `Object.keys()`, but by `Object.getOwnPropertyNames()` to check existence of any key? Because if key is non-enumerable it doesn't mean that key doesn't exists.

You can reproduce it like so:
```
const obj = {};
Object.defineProperty(obj, 'nonEnumerableProperty', {
  value: 1,
  enumerable: false,
  configurable: false,
  writable: false,
});

it('should conclude key exists', () => expect(obj).to.include.key('nonEnumerableProperty'));
```

Output:
```
  1)  should conclude key exists:

      AssertionError: expected {} to contain key 'nonEnumerableProperty'
      + expected - actual

      -[]
      +[
      +  "nonEnumerableProperty"
      +]
      
      at Context.<anonymous> (test/test.js:75:63)
```

**Comment by vieiralucas** [comment]
Hello @dortonway, thank you for the issue.

You should use the `property` assertion for this use case.
The following should do what you want.

```javascript
const obj = {};
Object.defineProperty(obj, 'nonEnumerableProperty', {
  value: 1,
  enumerable: false,
  configurable: false,
  writable: false,
});

it('should conclude key exists', () => expect(obj).to.have.property('nonEnumerableProperty'));
```

**Comment by lucasfcosta** [comment]
Since @vieiralucas' answer should be enough to answer that question I'll close this for now.
Please let us now if you have any further problems @dortonway.
Thanks for getting in touch! 😄
