### ISSUE TITLE
Trying to make 'should' work

### ISSUE THREAD

**Issue by TylerL-uxai** [chaijs/chai#895]
I'm trying to make 'should' work, but it's undefined. I got 'expect' working perfectly.

Good job on the project! Just need help getting started http://stackoverflow.com/questions/41422101/testing-with-chai-should-exist-not-working-with-async

**Comment by shvaikalesh** [comment]
Hello @TylerL-uxai and happy holidays. Thanks for reaching out.

If you are on npm version, use should do `require('chai').should()` or

```js
import chai from 'chai'
chai.should()
```

Please, note the function call. I had issues with getting `Object#should` to work too when first started using Chai.

If you are on `master` (not `canary`), you can also do `import 'chai/register-should'` or with Mocha:

```sh
$ mocha specs -r chai/register-should -w
```

**Comment by TylerL-uxai** [comment]
Thank you for the fast response! I think my problem is with async callbacks. My question got 42 views and two upvotes on StackOverflow http://stackoverflow.com/questions/41435074/how-to-get-the-callback-of-an-async-function-in-javascript

Maybe you can answer it? I promise to do [a brief writeup on unit testing](https://github.com/kriasoft/react-starter-kit/issues/1058) to react-starter-kit, which should generate some traffic for the chai framework as well.

**Comment by shvaikalesh** [comment]
Try

```js
import { expect } from 'chai';
import { Customer } from '../../data/models';

describe('Customers Server', () => {
  it('Create a customer', async () => {
    const createCustomer = await Customer.create({ email: 'test@gmail.com' });
    expect(createCustomer).to.exist;
  });
});
```

**Comment by TylerL-uxai** [comment]
Async is built in to expect! Great!

Thanks :) That totally worked

**Comment by shvaikalesh** [comment]
You are welcome.

**Comment by TylerL-uxai** [comment]
Is there any way to get rid of the eslint error?
“no-unused-expressions” Expected an assignment or function call and instead saw an expression.

<img width="1280" alt="screen shot 2017-01-03 at 6 01 45 pm" src="https://cloud.githubusercontent.com/assets/4743518/21627650/e6790bd8-d1de-11e6-9e89-efe894d1fc16.png">

**Comment by meeber** [comment]
You'd either need to turn that rule off within a eslint config located in your test directory, or check out something like https://github.com/prodatakey/dirty-chai

**Comment by TylerL-uxai** [comment]
Thank you, meeber! I included a working [example of some tests](https://github.com/kriasoft/react-starter-kit/issues/1058) on React-Starter-Kit.
