### ISSUE TITLE
How to add method while using typescript?

### ISSUE THREAD

**Issue by SherlockGuo** [chaijs/chai#898]
i can't see any `Assertion` with 'chai' imported and the `addMethod()` method is nowhere to be found. The instruction about building a helper doesn't help much about this issue. Plus, a deep equal function with 'excluding rules' may come in handy in many situations.

Thank you for watching

**Comment by SherlockGuo** [comment]
Well i managed to find the entrance.

**Comment by andrevmatos** [comment]
Can you explain where did you find it, please? Explaining on close is a good practice.
