### ISSUE TITLE
Missing `.nested.include` and `.own.include`

### ISSUE THREAD

**Issue by meeber** [chaijs/chai#905]
The `nested` and `own` flags currently work correctly with the `.include` assertion, but it's not documented or tested. Also, this functionality isn't currently exposed via the `assert` interface.

Note that I'm already making some documentation updates that include this, but the issue with the tests and `assert` interface are still outstanding.

**Comment by meeber** [comment]
BDD docs and tests were updated to resolve most of this issue. Still outstanding: Exposing on `assert` interface and adding tests.

**Comment by zetamorph** [comment]
I would like to do this and already read the contributor guide and familiarised myself with the coding style, but just to clarify, that task would also entail exposing the .deepNestedInclude, .deepOwnInclude(and the negated versions, respectively) methods on the assert interface?

**Comment by meeber** [comment]
@zetamorph Yup, exactly. For tests, I'd recommend just duplicating the ones for each combination from the `expect` test suite, and then converting them over to `assert`-style. For example [here](https://github.com/chaijs/chai/blob/850bd7e016606ce52292c0477320279a8b9cf294/test/expect.js#L1839-L1864). It's okay to combine both the normal and negated versions into a single `it` block to make the conversion easier.

Thanks and feel free to reach out with any questions!

**Comment by zetamorph** [comment]
@meeber Thanks for the heads-up. 
I have one question: does the coding style guide, specifically for nested arrays and objects, also strictly apply to examples in the documentation?

I find that the following:

```javascript
assert.deepNestedInclude(
  {a: 
    {b: 
      [
        {x: 1}
      ]
    }
  }, 
  {'a.b[0]': 
    {x: 1}
  }
);
```
is much harder to read than this:
```javascript
assert.deepNestedInclude({ a: { b: [ { x: 1 } ] } }, { 'a.b[0]': { x: 1 } });
```

**Comment by meeber** [comment]
@zetamorph Coding examples can be written with a focus on readability. See [these examples](https://github.com/chaijs/chai/blob/850bd7e016606ce52292c0477320279a8b9cf294/lib/chai/core/assertions.js#L365-L381) from the updated BDD docs.

**Comment by zetamorph** [comment]
@meeber Ok, thanks. 
I wasn`t sure because the style guide said that parts of the codebase still follow older styles. 
I submitted a pull request, https://github.com/chaijs/chai/pull/964.
