### ISSUE TITLE
Flaky error on assert.isNumber() for a number

### ISSUE THREAD

**Issue by classiemilio** [chaijs/chai#912]
Unclear how an assertion was triggered for this, but I have a test that failed assert.isNumber() for a number. This has only happened once, so not too concerned. Has anyone else experienced something like that?

"AssertionError: expected 308 to be a number"

**Comment by meeber** [comment]
What does `typeof` think that value is?

**Comment by classiemilio** [comment]
Well, this was during a test run, so can't check that with the variable, but running typeof on a variable set to 308 shows me "number". I imagine this will be near impossible to reproduce.

**Comment by meeber** [comment]
Hard to speculate without being able to see the code/tests or get the result of `typeof` on the variable prior to the assertion. In general, there's many ways something might appear to be a number but really isn't. Here's just one example:

```js
var fakeNumber = {inspect: () => 308};
expect(fakeNumber).to.be.a('number');
```

Output:

> AssertionError: expected 308 to be a number

**Comment by classiemilio** [comment]
Hah, that's cool. Ok, I'll add logging around my assertion failures to see what the typeof is. Thanks for your help!
