### ISSUE TITLE
assert.include gives undefined always.

### ISSUE THREAD

**Issue by guptarajatkn** [chaijs/chai#913]
var mgr = "TeamManager1"
var result = assert.include(mgr, "TeamManager");
console.log(result);
console.log(assert.include(mgr, "TeamManager"));

----------------------Output--------------
undefined
undefined

**Comment by meeber** [comment]
Hi @guptarajatkn. The assertions on Chai`s `assert` interface will always return `undefined`. Their behavior is to throw an error if the assertion fails, and to not throw an error if the assertion passes.

```js
var mgr = "TeamManager1"
assert.include(mgr, "TeamManager"); // Passes; no error thrown
assert.include(mgr, "SalesRep"); // Fails; error thrown
```

**Comment by vieiralucas** [comment]
@guptarajatkn I'll close this for now.
Feel free to ask anything if you are still having problems or if you did not understand something.

Thank you
