### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by agraver** [chaijs/chai#914]
http://chaijs.com/api/bdd/ 

`.ownPropertyDescriptor(name[, descriptor[, message]])`

has an assertion

`expect('test').ownPropertyDescriptor('length').to.have.keys('value');`

which fails like this:
```
AssertionError: expected { Object (value, writable, ...) } to have key 'value'
+ expected - actual

 [
-  "configurable"
-  "enumerable"
   "value"
-  "writable"
 ]
```

> Note, either any or all should be used in the assertion. If neither are used, the assertion is defaulted to all.
>When both all and have are used, the target object must both contain all of the passed-in keys AND the number of keys in the target object must match the number of keys passed in (in other words, a target object must have all and only all of the passed-in keys).

to pass the assertion should be changed to
`expect('test').ownPropertyDescriptor('length').to.contain.keys('value');`
or
`expect('test').ownPropertyDescriptor('length').to.have.any.keys('value');`
or
`expect('test').ownPropertyDescriptor('length').to.include.keys('value');`

**Comment by agraver** [comment]
Also in 

`.throw(constructor)`
```
var err = new ReferenceError('This is a bad function.');
var fn = function () { throw err; }
expect(fn).to.throw(ReferenceError)
   .and.not.throw(/good function/);
```
test fails to pass
`AssertionError: expected [ReferenceError: This is a bad function.] to be a function`

**Comment by meeber** [comment]
@agraver thanks for the issue. The bad example in `.throw` is already fixed in the master branch. I'm currently working on a comprehensive update of our documentation which includes a correction of the bad example in `.ownPropertyDescriptor`.
