### ISSUE TITLE
why bdd style is called bdd style?

### ISSUE THREAD

**Issue by zzzgit** [chaijs/chai#935]
The BDD style,why named it BDD?

**Comment by meeber** [comment]
@zzzgit The BDD (i.e., `should` and `expect`) interfaces facilitate writing tests that are expressive and readable by non-programmers. The natural language approach to expressing behaviors and expected outcomes may aid some teams in terms of communication, collaboration, and structure throughout the development process. On the other hand, the TDD (i.e., `assert`) interface is a bit more programmer-centric.

With that said, you can certainly adhere to either a BDD or TDD driven approach using any interface. The names merely categorize the interfaces based on their most common application.

**Comment by keithamus** [comment]
@zzzgit BDD stands for `Behaviour Driven Development`. (TDD stands for `Test Driven Development`).

**Comment by zzzgit** [comment]
thanks very much
