### ISSUE TITLE
Unable to get started with plugin

### ISSUE THREAD

**Issue by openback** [chaijs/chai#936]
I'd like to start making plugins, but I'm obviously missing something, or something is missing in the docs. My two files are below. Running the spec below shows only the log of `Setting it up`, but the attempted usage results in `undefined is not a constructor (evaluating 'expect({}).to.something()')` because `something` is not defined. What am I missing?

```js
// plugin.js
export default (chai, utils) => {
  console.log('Setting it up')

  chai.Assertion.addMethod('something', () => {
    console.log('Doing something')
    // this.assert would be here...
  })
}
```

```js
// plugin.spec.js
import chai from 'chai'
import plugin from './plugin'

chai.use(plugin)

describe('chai plugin', function() {
  it('should do something', function() {
    expect({}).to.something()
  })
})
```

**Comment by meeber** [comment]
Just tested the below with Chai v3.5 and didn't run into any issues. Any chance something is going on with your transpiler?

```js
// plugin.js
module.exports = (chai, utils) => {
  console.log('setting it up');

  chai.Assertion.addMethod('something', () => {
    console.log('Doing something');
  });
};

// plugin.spec.js
const chai = require("chai");
const plugin = require("../plugin");

const expect = chai.expect;

chai.use(plugin);

describe('chai plugin', function () {
  it("should do something", function () {
    expect({}).to.something();
  });
});
```

**Comment by meeber** [comment]
Closing this for now. Feel free to re-open if you're still having issues and suspect it's a problem with Chai instead of transpiler.

**Comment by openback** [comment]
Yeah, it looks like you're right. I tried the same thing, bypassing webpack, and it worked as expected.
