### ISSUE TITLE
array.should.contain(element) is very slow

### ISSUE THREAD

**Issue by ikerr** [chaijs/chai#941]
We have some tests that are timing out after 20+ seconds when calling: `array.should.contain(element)`. The problem seems to occur when `element` has a lot of properties, and does not depend on whether or not the array actually contains the element.

I ran Chrome's JavaScript profiler to determine where the slowdown was occurring, and the results point to the `_.inspect(val)` call here: https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L345

The issue is that `inspect()` is called whether or not the test fails, causing these tests to run more slowly and in some cases time out.

**Comment by meeber** [comment]
@ikerr Thanks for the issue. It's unfortunate that Chai generates the error messages regardless of whether or not there's an error, especially in this instance with using `inspect` on a potentially huge object. I'm surprised by 20+ seconds. What kind of scale are we talking about when you say "lots of properties"? I wonder if there's some kind of circular logic going on that's causing `inspect` to freak out.

A hack could be added to each assertion's logic to avoid this kind of issue, but it'd be messy. A good solution would require the kind of architectural change discussed in #585.

**Comment by ikerr** [comment]
@meeber The object in question had a property that referenced `window`. This worked OK until I included an Emscripten module that defined itself on `window.Module`. Presumably the Emscripten module contained too many enumerable properties.

**Comment by meeber** [comment]
Unfortunately I don't foresee this as something we can fix without a major re-architectural change or messy hack. Gonna close this one given that the changes planned in #585 indirectly resolve it. Thanks!
