### ISSUE TITLE
Chai with Bluebird: Unhandled Promise Rejection error when accessing property of result in then() callback

### ISSUE THREAD

**Issue by bsodmike** [chaijs/chai#942]
Hi all,

The approach I've taken is this, where the `done()` callback is called after the expectations are set:

```javascript
it('it should do something', (done) => {
  // test setup over here.
  
  // assert expectation here.
  expect();
  done();
});
```

[Take a look at my example](https://github.com/bsodmike/bsodmike-billing-task/commit/517b028cf9e55142c171986f01fed11b91d6f5ec#diff-09baab42585bca6bc9ac3cafae40f938R93) where I've setup some Promises within an integration spec.

I've basically chained a couple promises, and in the final `then()` call, performed an evaluation via `chai` and `chai-http`,

```javascript
.then((resCharge) => {
    chai.request(server)
        .get(`/charges?customer_id=${resCharge.body.customer}`)
        .then((res) => {
          // console.log('RESULT: %s', util.inspect(res.body));

          expect(res).to.have.status(200);
          expect(res.body).to.have.all.keys(['customer', 'charges', 'chargesCount', 'hasMore', 'url']);

          /**
           * FIXME the following assertion seems to break chai, causing an
           * 'Unhandled promise rejection' warning via Bluebird.
           *
           * This needs further investigation.
           */
          // expect(res.body).to.have.property('chargesCount').and.eql('3');

          // Obtain total for all charges fetched for this customer
          let chargeTotal = 0;

          res.body.charges.forEach((chargeDetail) => {
            chargeTotal += parseInt(chargeDetail.amount, 10);
          });

          // Assert obtained charge total matches the expectation.
          const expectedTotal = charges.reduce((acc, val) => acc + val);
          expect(chargeTotal).to.eql(expectedTotal);

          done();
        })
        .catch((err) => {
          console.log('Error: %s', util.inspect(err.response.body.error));
          throw err;
        });
  })
  .catch((err) => {
    console.log('Error: %s', util.inspect(err.response.body.error));
    throw err;
  });
```

If I attempt to make any assertion on a property of the value of the `then()` callback, this raises an Unhandled promise rejection error via Bluebird.

I suppose one thing I did that could be considered strange is that I wrapped up the Promisified-chai behaviour within another Promise &mdash; simply because it makes the code so much cleaner.

Thoughts?

**Comment by bsodmike** [comment]
Based on my prior suspicion, I reverted my Promises from

```javascript
 const chargeCustomer = charge => new Promise((resolve, reject) => {
    chai.request(server)
        .post('/charges')
        .send(charge)
        .then((res) => {
          resolve(res);
        })
        .catch((err) => {
          reject(err);
        });
  });
```

to this:

```javascript
const chargeCustomer = charge => new Promise((resolve, reject) => {
  chai.request(server)
      .post('/charges')
      .send(charge)
      .end((err, res) => {
        if (err) { reject(err); }
        resolve(res);
      });
});
```

It seems like the double-Promisified `chai` calls brought about this behaviour?  Could anyone confirm this?

My spec works fine now
https://github.com/bsodmike/bsodmike-billing-task/commit/f30d37af8dc6cc49139fb8b1c9d33a208e57abeb

**Comment by vieiralucas** [comment]
Hello @bsodmike, thanks for your issue

I don't know if I fully understood your problem, so please correct me if I'm saying something wrong.

If I understood correctly, the reason you were getting a `Unhandled Promise Rejection` was because you were catching the rejection and **rethrowing** it again and since you were not returning the chai request to the promise chain the rejection would never hit the next catch.

```js
.then((resCharge) => {
   chai.request(server) // You need to return this promise.
        .get(`/charges?customer_id=${resCharge.body.customer}`)
        .then((res) => {
          // console.log('RESULT: %s', util.inspect(res.body));

          expect(res).to.have.status(200);
          expect(res.body).to.have.all.keys(['customer', 'charges', 'chargesCount', 'hasMore', 'url']);

          /**
           * FIXME the following assertion seems to break chai, causing an
           * 'Unhandled promise rejection' warning via Bluebird.
           *
           * This needs further investigation.
           */
          // expect(res.body).to.have.property('chargesCount').and.eql('3');
          // when this assertion fails, the rejection will hit the catch below

          // Obtain total for all charges fetched for this customer
          let chargeTotal = 0;

          res.body.charges.forEach((chargeDetail) => {
            chargeTotal += parseInt(chargeDetail.amount, 10);
          });

          // Assert obtained charge total matches the expectation.
          const expectedTotal = charges.reduce((acc, val) => acc + val);
          expect(chargeTotal).to.eql(expectedTotal);

          done();
        })
        .catch((err) => {
          console.log('Error: %s', util.inspect(err.response.body.error));
          throw err;
          // here you are rethrowing the error which makes the promise rejects again
          // since you were not returning this promise, the rejection will never hit this catch below \/
        });
  })
  .catch((err) => {
    console.log('Error: %s', util.inspect(err.response.body.error));
    throw err;
  });
```

1. `chai-http` will return a promise. You don't need to wrap it into a `new Promise`
2. I see you are using `mocha`. Mocha supports promises too, if you return a `Promise` from your tests you can forgot the `done`.
3. I suspect that when your test fails, they will fail because of timeout, you need to call `done` with the error, or return the promise directly to mocha and not accept a `done` parameter.

I hope I've helped make you understand, please correct me if I said anything wrong
Sorry if my explanation is a mess and hard to understand 😞

**Comment by bsodmike** [comment]
@vieiralucas bah - thanks so much Lucas, I went over this code so many times and knew I'd forgotten to call 'return' inside a `then()` block.

Thanks for points 2 & 3, that also makes things clear.

**Comment by bsodmike** [comment]
Hey @vieiralucas, this did indeed have an issue, however, the Unhandled rejection took place due to failing to return the chai request to the promise chain &mdash; but....

```javascript
          // expect(res.body).to.have.property('chargesCount').and.eql('3');
          // when this assertion fails, the rejection will hit the catch below
```

It is at this point that something interesting happened, as `err.response == undefined`!!
This error was then being re-thrown and then unhandled.

```javascript
        .catch((err) => {
          console.log('Error: %s', util.inspect(err.response.body.error));
          throw err;
          // here you are rethrowing the error which makes the promise rejects again
          // since you were not returning this promise, the rejection will never hit this catch below \/
        });
```

Also, leveraging your point (1), I was able to shrink these down,

```javascript
const chargeCustomer = charge =>
    chai.request(server)
        .post('/charges')
        .send(charge);
```

Revised version is here https://github.com/bsodmike/bsodmike-billing-task/commit/171880fb41df60c102def1d849d88385639add96

**Comment by vieiralucas** [comment]
@bsodmike I made a comment on your commit

**Comment by vp9920** [comment]
The issue still exists, but I don't think this is a chai issue. I have following code:
`function funcToTest () {
        return someAsyncFunc()
            .then((result) => {
                // and here:
                console.log(result.someProperty)
                // or even:
                result.somePropery
            });
    }`
and following tests:
`
it('should return a promise', () => {
    expect(funcToTest ()).to.be.a('promise');
});

it('should...', () => {
    return new Promise((resolve, reject) => {
        funcToTest ().then(() => {
            resolve();
        }, () => {
            reject();
        });
     });
 });
`
and it prints:
`[ERROR] 'Unhandled promise rejection', TypeError{stack:...`
but tests pass
result.someProperty exists, and console.log(result.someProperty) works
But wat is interesting: **no result property accessing, no problems**
Reproducible on node 7.10 and 6.9
