### ISSUE TITLE
to.not.exist - test incorrectly failing

### ISSUE THREAD

**Issue by gavin-johnson84** [chaijs/chai#944]
Hi,

I'm having a test incorrectly failing when using the `.to.not.exist` chain.

To verify this I've added numerous `browser.pause` to my tests and I can see that the element is removed from the DOM.

Please see my test below for reference:
```
  it("should remove the unread message counter", function () {
    this.retries(3);
    browser.reload();
    browser.url(pageUrl);
    browser.waitForExist(frameUrl);
    browser.frame($(frameUrl).value);
    browser.pause(5000);
    browser.waitForExist(selectors.notificationIcon);
    browser.click(selectors.avatars);
    browser.pause(10000);
    expect(selectors.notificationIcon).to.not.exist;
  });
```

I'm using webdriver.io for further reference.

Many thanks!

**Comment by meeber** [comment]
@gavin-johnson84 Thanks for the issue. What happens if you remove Chai from the equation by making this change:

```js
it("should remove the unread message counter", function () {
  <...stuff...>
  //commentedOut expect(selectors.notificationIcon).to.not.exist; 
  if (selectors.notificationIcon !== null && selectors.notificationIcon !== undefined) {
    throw Error("oh noes");
  }
});
```

**Comment by gavin-johnson84** [comment]
Hi @meeber, thanks for your response! I've made the following changes to my test:
```
  it("should remove the unread message counter", function () {
    this.retries(3);
    browser.reload();
    browser.url(pageUrl);
    browser.waitForExist(frameUrl);
    browser.frame($(frameUrl).value);
    browser.waitForExist(selectors.notificationIcon);
    browser.click(selectors.avatars);
    //expect(selectors.notificationIcon).to.not.exist();
    if (selectors.notificationIcon !== null && selectors.notificationIcon !== undefined) {
      throw Error("oh noes");
    }
  });
```
I get the following error when the test has run:
```
[chrome #0-6] 1) chat pro-active messages opened should remove the unread message counter:
[chrome #0-6] oh noes
[chrome #0-6] Error: oh noes
[chrome #0-6]     at Context.<anonymous> (/Users/gavin/Code/triptease/test-drive/e2e/guestpa/tests/chat/proactive-messages/proactive-messages-opened.test.js:49:13)
[chrome #0-6]     at F (/Users/gavin/Code/triptease/test-drive/e2e/node_modules/wdio-sync/node_modules/core-js/library/modules/_export.js:35:28)
```

Cheers

**Comment by meeber** [comment]
@gavin-johnson84 It threw an "oh noes" error, which means that `selectors.notificationIcon` is set to something other than `undefined` or `null`, which means that `selectors.notificationIcon` exists from Chai's perspective. You could change the example code above to `throw Error("oh noes", selectors.notificationIcon);` to see what value it has, but either way, it looks to me like Chai's `to.not.exist` is behaving as expected.

**Comment by gavin-johnson84** [comment]
@meeber, thanks! I think this may be due to my understanding of `to.not.exist` then.

`selectors.notificationIcon` appears as follows in my `selectors` file:
`notificationIcon: '.Toggle-notification-o-Jaf'`

As mentioned this component is removed from the DOM, so I was expecting this test to pass using `do.not.exist`.

Could you recommend a method to assert if `selectors.notificationIcon` is present or not please?

Many thanks!

**Comment by keithamus** [comment]
@gavin-johnson84 it looks like `browser.waitForExist` can be [reversed](http://webdriver.io/api/utility/waitForExist.html). So changing your test as follows might help:

```diff
- browser.pause(10000);
- expect(selectors.notificationIcon).to.not.exist;
+ browser.waitForExist(selectors.notificationIcon, 1000, true);
```

I'll close this issue, as I think chai is doing the right thing, and I think the above should solve your issues. Let us know how it goes, and we can re-open if needed.

**Comment by gavin-johnson84** [comment]
Hi @keithamus, thanks for your help!

My test now passes, but I'm a bit concerned about the lack of assertion.

```
  it("should remove the unread message counter", function () {
    this.retries(3);
    browser.reload();
    browser.url(pageUrl);
    browser.waitForExist(frameUrl);
    browser.frame($(frameUrl).value);
    browser.pause(5000);
    browser.waitForExist(selectors.notificationIcon);
    browser.click(selectors.avatars);
    browser.waitForExist(selectors.notificationIcon, 500, true);
  });
```

I'd played with the test, adding `expect(selectors.notificationIcon).to.exist;` to the last line and the test still passes.

Could you advise please?

Thanks

**Comment by keithamus** [comment]
`selectors.notificationIcon` is presumably some kind of string, it will always exist. If you want an assertion, you could do this, instead:

```js
expect(browser.$(selectors.notificationIcon)).to.have.lengthOf(0)
```

**Comment by gavin-johnson84** [comment]
@keithamus I've made your suggested changes and the test now fails showing the following output:
```
1) chat pro-active messages opened should remove the unread message counter:
expected '.Toggle-notification-o-Jaf' to have a length of 0 but got 26
```
This is odd as I mentioned above I can verify that the class is not shown in the DOM.

Thanks again
