### ISSUE TITLE
Deep equal can not handle minus zero values

### ISSUE THREAD

**Issue by yuri-karadzhov** [chaijs/chai#945]
```js
expect({x: 0, y: -0}).to.deep.equal({x: 0, y: 0}); // error
```

```sh
chai@3.5.0
mocha@3.2.0
node v7.7.0
npm 4.1.2
```

**Comment by shvaikalesh** [comment]
Hey @yuri-karadzhov, thanks for the issue.

Chai intentionally uses `SameValue` algorithm for equality that differentiates `-0` and `0`.

**Comment by yuri-karadzhov** [comment]
@shvaikalesh probably it has sense for some cases, but for most of them we probably should not care about zero sign. Anyway it would be nice either change behaviour or add an option.

**Comment by keithamus** [comment]
The new version of deep-eql allows you to override it's equality algorithm, but the `.deep.equal` assertion hasn't been updated to facilitate this. Check out https://github.com/chaijs/chai/issues/644 for more on this.

I'll close this issue, as we've got it in the pipeline, and https://github.com/chaijs/chai/issues/644 is the tracking issue for this.
