### ISSUE TITLE
like power-assert Features

### ISSUE THREAD

**Issue by zenjava** [chaijs/chai#946]
Have plugin like power-assert?
  assert.equal(obj.arr[ 0 ], obj.number);     

AssertionError:   # a/a.test.js:15
  
  assert.equal(obj.arr[0], obj.number)
               |   |  |    |   |      
               |   |  |    |   10     
               |   |  1    Object{arr:#Array#,number:10}
               |   [1,2,3]            
               Object{arr:#Array#,number:10}

**Comment by meeber** [comment]
@zenjava Not that I'm aware of, and I don't think this could be easily done in Chai. The `assert` interface is somewhat of a second-class citizen to the bdd interfaces, acting as a wrapper around the bdd interface, which I suspect would complicate the kind of AST wizardy being performed by Power Assert.

The mission of Power Assert and Chai are fairly different: Power Assert values a minimalistic. programmer-centric syntax (i.e., `assert` only) with visual failed assertion messages, whereas Chai values natural language assertions (i.e, `expect(foo).to.equal(2)`), which many people find helpful in reasoning about tests, and collaborating with non-programmers. Both have their pros/cons.
