### ISSUE TITLE
chai assert deepEqual gives assertionError even though the data is same

### ISSUE THREAD

**Issue by jsmankoo** [chaijs/chai#948]
Chai assert (and expect) deepEqual gives me assertionError:
```sh
{
  "name": "AssertionError",
  "message": "expected { Object (_id, campaignID, ...) } to deeply equal { Object (_id, campaignID, ...) }",
  "showDiff": true,
  "actual": {
    "_id": "package_9B3Aiz8baW",
    "campaignID": "campaign_asdf",
    "targetID": "target_asdf",
    "adFreq": {
      "value": 5,
      "unit": "daily"
    },
    "adType": "adt_01",
    "adUnit": "adu_01",
    "flights": [
      {
        "startDate": 1234,
        "endDate": 2345
      },
      {
        "startDate": 2345,
        "endDate": 3456
      }
    ],
    "runTimes": [
      {
        "from": "11:00",
        "to": "13:00"
      },
      {
        "from": "15:00",
        "to": "18:00"
      }
    ],
    "budgetPercent": 0.1
  },
  "expected": {
    "_id": "package_9B3Aiz8baW",
    "campaignID": "campaign_asdf",
    "targetID": "target_asdf",
    "adFreq": {
      "value": 5,
      "unit": "daily"
    },
    "adType": "adt_01",
    "adUnit": "adu_01",
    "flights": [
      {
        "startDate": 1234,
        "endDate": 2345
      },
      {
        "startDate": 2345,
        "endDate": 3456
      }
    ],
    "runTimes": [
      {
        "from": "11:00",
        "to": "13:00"
      },
      {
        "from": "15:00",
        "to": "18:00"
      }
    ],
    "budgetPercent": 0.1
  },
  "stack": "AssertionError: expected { Object (_id, campaignID, ...) } to deeply equal { Object (_id, campaignID, ...) }\n    at Function.assert.deepEqual (/home/jsmankoo/cluep/cluep-client-libraries/node_modules/chai/lib/chai/interface/assert.js:216:32)\n    at Context.<anonymous> (/home/jsmankoo/cluep/cluep-client-libraries/test/Campaign/Package.spec.ts:294:14)\n    at callFn (/home/jsmankoo/cluep/cluep-client-libraries/node_modules/mocha/lib/runnable.js:345:21)\n    at Test.Runnable.run (/home/jsmankoo/cluep/cluep-client-libraries/node_modules/mocha/lib/runnable.js:337:7)\n    at Runner.runTest (/home/jsmankoo/cluep/cluep-client-libraries/node_modules/mocha/lib/runner.js:444:10)\n    at /home/jsmankoo/cluep/cluep-client-libraries/node_modules/mocha/lib/runner.js:550:12\n    at next (/home/jsmankoo/cluep/cluep-client-libraries/node_modules/mocha/lib/runner.js:361:14)\n    at /home/jsmankoo/cluep/cluep-client-libraries/node_modules/mocha/lib/runner.js:371:7\n    at next (/home/jsmankoo/cluep/cluep-client-libraries/node_modules/mocha/lib/runner.js:295:14)\n    at Immediate.<anonymous> (/home/jsmankoo/cluep/cluep-client-libraries/node_modules/mocha/lib/runner.js:339:5)\n    at runCallback (timers.js:666:20)\n    at tryOnImmediate (timers.js:639:5)\n    at processImmediate [as _immediateCallback] (timers.js:611:5)"
}

```

I even test assert.equal after stringifying the two and it passes.

**Comment by meeber** [comment]
@jsmankoo I tried copying and pasting your `actual` and `expected` objects, and it passed a deep equal comparison. Is there any chance the actual objects you're dealing with have different prototypes (i.e., different inherited enumerable properties)?

**Comment by meeber** [comment]
Gonna close this due to lack of activity and ability to reproduce. Thanks!

**Comment by meeber** [comment]
@worc Chai's deep equality algorithm is documented [here](https://github.com/chaijs/deep-eql). The relevant quote is `All own and inherited enumerable properties are considered`. It's worth noting that Chai's algorithm was created in 2013, whereas Node's `assert.deepStrictEqual` was introduced in early 2015, so it's not like Chai's early developers were turning their noses at some established spec. Additionally, libraries like Lodash have their own deep equality algorithm, which also predates Node's `deepStrictEqual` (although it looks like [Lodash switched their regluar deep equal algorithm to `assert.deepStrictEqual` in late 2017](https://github.com/lodash/lodash/issues/3428)).

Anyway, if you feel like you're encountering a bug in Chai (as in, the behavior doesn't match the docs), then please open a new issue with easily reproducible code. If you feel like Chai's deep equality algorithm is wrong, then please up a ticket in [the deep-equal repo](https://github.com/chaijs/deep-eql).

**Comment by worc** [comment]
it's a weird edge that's actually called out in the deep-equal repo. error strings are compared by reference rather than value. but when using redux-saga to handle error messages, for example, you can end up with this assertion error:

`AssertionError: expected { Object (@@redux-saga/IO, PUT) } to deeply equal { Object (@@redux-saga/IO, PUT) }`

but the diff shows no difference. it makes sense once you dig deeper, one Error is not the same as another, but the output that is being compared looks like a plain object with plain strings. i don't know if that's something that should be added to the chai API docs; they're pretty sparse already and maybe just having this conversation is documentation (and searchable) enough.

**Comment by keithamus** [comment]
@worc we're working hard on a new version of Chai which will have much better error messages, including pointing out when things which "look equal" are not the same reference. Hopefully this will go a bit further to solving the error messaging problem. 

We're also happy to accept any contributions to documentation. We're hoping to improve on this area a lot soon.

**Comment by anvlkv** [comment]
Hi, I'm using 

       "chai": "^4.2.0",
       "mocha": "^5.2.0",


When I do

    blocks.forEach((b, i) => {
                Object.keys(b).forEach(prop => {
                    expect(blocks[i][prop]).to.deep.equal(exampleBlockOutput[i][prop]);
                });
            });

test passes

but when I do

    expect(blocks).to.deep.equal(exampleBlockOutput);

it fails with 
    
    AssertionError: expected [ Array(2) ] to deeply equal [ Array(2) ]
        at Context.<anonymous> (src/ra/block-stream/ra-block-stream.spec.ts:55:36)
        at Context.<anonymous> (src/ra/block-stream/ra-block-stream.spec.ts:29:13)


And If were to introduce actual difference I would see

     AssertionError: expected [ Array(2) ] to deeply equal [ Array(2) ] <Click to see difference>
        at Context.<anonymous> (src/ra/block-stream/ra-block-stream.spec.ts:55:36)
        at Context.<anonymous> (src/ra/block-stream/ra-block-stream.spec.ts:29:13)

**Comment by givanse** [comment]
I'm seeing the same behavior with chai 4.2.0 The same tests to work with chai 3.3.0

**Comment by rahulnlb1** [comment]
I used ```expect([1, 2, 3]).to.eql([1, 2, 3]);``` for assertion of deep entities and it worked for me.

**Comment by oprogramador** [comment]
For me, something like the following fails without a meaningful message:
```
expect(result).to.deep.equal([
  { foo: 'bar-0' },
  // I don't want to expect everything because it's very long
  result[1],
  result[2],
  { foo: 'bar-1' },
]);
```
The message is like: `AssertionError: expected [ { foo: 'bar-0' }, …(3) ] to deeply equal [ { foo: 'bar-0' }, …(3) ]`.

I use chai@4.3.6.

**Comment by keithamus** [comment]
If you want to see more of the object inspected, you can set `chai.config.truncateThreshold` to something larger than the default of `75`. For example `chai.config.truncateThreshold = Infinity` will always show the full object. Be prepared to see some very large error messages, though.

**Comment by oprogramador** [comment]
> If you want to see more of the object inspected, you can set `chai.config.truncateThreshold` to something larger than the default of `75`. For example `chai.config.truncateThreshold = Infinity` will always show the full object. Be prepared to see some very large error messages, though.

Thanks but I don't think that it'll give me anything because the objects seem to be exactly the same.

**Comment by keithamus** [comment]
If your object has Symbol keys which are different then the comparison will fail. Currently [loupe](https://github.com/chaijs/loupe) (the inspection engine that renders the error message) does not render Symbol keys, IIRC.
