### ISSUE TITLE
Is ECMAScript 2017 async function a function

### ISSUE THREAD

**Issue by nati-mask** [chaijs/chai#949]
I maybe **totally** missing something here, but I don't understand this:
```bash
$ node -v
v7.7.3
```
```bash
$ node --harmony
```
```javascript
> var chai = require('chai');
>
> async function foo() {};
>
> console.log(typeof foo);
function
>
> chai.assert.isFunction(foo);
AssertionError: expected [Function: foo] to be a function
    at Function.assert.isFunction (.../node_modules/chai/lib/chai/interface/assert.js:516:35)
    at ...
>
> chai.expect(foo).to.be.a('function');
AssertionError: expected [Function: foo] to be a function
    at ...
```
This behavior looks weird to me...  can someone explain?

**Comment by shvaikalesh** [comment]
Hey @nati-mask, thanks for reaching out.

Does the issue persist in `chai` from `master`?

**Comment by nati-mask** [comment]
Oh!

You're right, I've checked now. It's not happening on branch `master`, but it does on `"chai": "3.5.0"` installed yesterday from npm repo.

Waiting for the next publish, until then, skipping some tests...

Sorry for not check that before
Thanks @shvaikalesh.

**Comment by shvaikalesh** [comment]
No need to be sorry, it is OK.

Sadly, we can't backport fix to `3.5`, master is too far away.
You can use `@canary` though.

**Comment by nati-mask** [comment]
Thanks I will.
But after all it sounds like a confirmed **bug** at the **[latest (3.5.0)](https://www.npmjs.com/package/chai)** at npm though, isn't it ?

**Comment by shvaikalesh** [comment]
Yep, it is.

**Comment by meeber** [comment]
Closing this since it's resolved in master. Thanks!
