### ISSUE TITLE
expect().to.have.all.members() throws assertion error on equivalent arrays with NaN

### ISSUE THREAD

**Issue by KernelDeimos** [chaijs/chai#950]
When testing the results of a function call in one of my test cases, I got an unexpected assertion error. I replaced the function call with the output I was expecting and found I still received an assertion error.

```
expect([false,0,"",null,undefined,NaN,"positive","negative"]).to.have.all.members(
    [false,0,"",null,undefined,NaN,"positive","negative"]
);
```
```
AssertionError: expected [ Array(8) ] to have the same members as [ Array(8) ]
```

Through trial and error I found the culprit value to be `NaN`

The following produces a similar assertion error:
```
expect( [NaN] ).to.have.all.members( [NaN] );
```
```
AssertionError: expected [ NaN ] to have the same members as [ NaN ]
```

**Comment by shvaikalesh** [comment]
Hey @KernelDeimos, thanks for reaching out.

Does the issue persist in `master`?

**Comment by KernelDeimos** [comment]
I'm not sure if I did this correctly, but I ran `npm install git+https://github.com/chaijs/chai.git` and the issue persists

**Comment by vieiralucas** [comment]
I suspect that this happens because `NaN === NaN` turns out to be `false`
Since chai uses `indexOf` [here](https://github.com/chaijs/chai/blob/ef2bf66d7c7ca4b7ed292e80ac17fc9b5c2e8bac/lib/chai/core/assertions.js#L1913) which performs `strict equality`

**Comment by KernelDeimos** [comment]
Huh, I'm kind of on the fence about this myself, but the logic I was going with was "since the parameter is usually literal test values, and I put NaN there, my intention is definitely to see if NaN is a member of this array"

Using to.be.deep.equal in this situation unfortunately isn't suitable - in my first example, which reflects my situation, I also need to test against a string literal (which fails the test)

**Comment by meeber** [comment]
Although the equality of `NaN` is an unfortunate language quirk, I agree with @vieiralucas that Chai is doing what it needs to in this situation by using strict equality by default and deep equality when the `deep` flag is set.

@KernelDeimos Could you provide a bit more detail about why `deep.members` or `deep.equal` doesn't work in your situation?

**Comment by KernelDeimos** [comment]
I'm actually not sure... I just tried `deep.members` and it works, but `deep.equal` doesn't. They're definitely both arrays, but I'll look into it further tonight and see what's going on.

**Comment by meeber** [comment]
Gonna go ahead and close this issue for now but feel free to reopen if you find an issue as a result of further investigation.
