### ISSUE TITLE
isFunction + Proxy on Safari = unexpected behavior

### ISSUE THREAD

**Issue by apowers313** [chaijs/chai#952]
When creating a class that extends `Function` and returns a `Proxy` of the function, `isFunction` works fine on Chrome, FF, and node.js but incorrectly identifies the class as not a function on Safari. The error can be duplicated with this code:

``` js
var assert = chai.assert;

class MyFunc1 extends Function {
    constructor() {
        super();
    }
}

class MyFunc2 extends Function {
    constructor() {
        super();
        return new Proxy(this, {});
    }
}

// passes
assert.isFunction(function(){});

// passes
var f1 = new MyFunc1();
assert.isFunction(f1);

var f2 = new MyFunc2();
// passes
assert.instanceOf(f2, Function);
// throws
assert.isFunction(f2);
```

Safari version is 10.0.3 (12602.4.8).

**Comment by meeber** [comment]
Does this problem still occur using `chai@canary`? If so, what does https://github.com/chaijs/type-detect report such an object being?

**Comment by apowers313** [comment]
Looks like it's fixed on `chai@canary`.

**Comment by meeber** [comment]
Awesome!
