### ISSUE TITLE
Option to Show Newlines (and Other Whitespace Characters) Instead of \n

### ISSUE THREAD

**Issue by machineghost** [chaijs/chai#953]
Currently if I compare two strings containing whitespace and they don't match, I see:

    AssertionError: expected '<?xml version="1.0" encoding="utf-8"?>/n<someTag value="55">/nfoo

It would be nice if there was a way I could do something like:

    chai.config.showWhitespace = true;

and then instead see:

    AssertionError: expected '<?xml version="1.0" encoding="utf-8"?>
    <someTag value="55">
    foo

**Comment by keithamus** [comment]
Hey @machineghost thanks for the issue.

This would be awesome! We've added this to our Roadmap https://github.com/chaijs/chai/projects/2! We'll be releasing chai 5 soon, but for now I'll close this issue because it is tracked on our roadmap.
