### ISSUE TITLE
Chai `should` overwrites my own property

### ISSUE THREAD

**Issue by Stalso** [chaijs/chai#954]
I am working with **elasticsearch.js** and generating some query objects in code. One of **Elasticsearch** queris is `boolQuery`, which has `should `property. And when I want to test my query object and write something like this, I get an error.

    expect(result.filterQuery.bool.should).to.have.length(2);

As you see, `should `property of tested object must be an array with two items. But I am getting an error, because my `should `property is overwritten by **Chai**.  And I can not rename my `should ` field. How can I overcome this problem?

**Comment by sgen** [comment]
Use expect() instead?

**Comment by vieiralucas** [comment]
Hello @Stalso, thanks for your issue.

I see you're using `expect`, so you don't need to call `chai.should()`

As @sgen suggests, you can overcome this problem by using the `expect` interface.

**Comment by Inzept3D** [comment]
Hello Stalso,

I am from the Start-Up project Inzept3D, based in Bochum, Germany. Our work focusses on making communication processes between architects and their clients faster and easier by providing a 1-click SaaS solution for interactive 3D renderings.
We are currently looking for people who are experienced in programming Plugins for CAD-Software as ArchiCAD, AutoCAD, Revit etc. for exporting 3D-CAD files from CAD software to our browser based solution. I saw your contributions on GitHub and thought you might have the perfect skills for what we need.

Just shoot me an email if you are interested in working together on a great project or you need further details.

**Comment by meeber** [comment]
@Inzept3D The Chai issue tracker isn't the place to make job recruitment pitches.

**Comment by Inzept3D** [comment]
ok, sorry about that didn't know better. I am new to GitHub. What is a better place in GitHub to make job recruitment pitches? Or is it somehow possible to write private messages to other users?
