### ISSUE TITLE
assert.isFunction fails when passing an async function 

### ISSUE THREAD

**Issue by atheros** [chaijs/chai#958]
Code:

	async function a() { }
	console.log(typeof a);
	console.log(a instanceof Function);
	assert.isFunction(a);

Result:

	function
	true

	AssertionError: expected [Function: a] to be a function
		at Function.assert.isFunction (node_modules/chai/lib/chai/interface/assert.js:516:35)
		at Context.it (test/CoreTest.js:87:11)

**Comment by keithamus** [comment]
@atheros thanks for the issue. What version of chai are you using? Could you try installing `npm i chai@canary` and see if the problem persists.

**Comment by atheros** [comment]
@keithamus  thanks for quick response. Issue is present in chai 3.5.0. Tested with node 7.7.4.

chai@canary doesn't have this problem, I guess I'll switch to this version.

**Comment by keithamus** [comment]
@atheros FWIW we plan to have chai@4 released by end of April. canary is relatively battle tested.

**Comment by vforv** [comment]
Not working with 4.2.0 as well

**Comment by Vishwas1** [comment]
Having the same problem with ```"chai": "^4.0.0-canary.2",```

**Comment by victor-anderson-actual** [comment]
Is `npm i chai@canary` still a viable option since it's 2022 now? I've been looking all over the web to solve this assertion problem, but have had no luck. I made a post about it on stackoverflow [here](https://stackoverflow.com/questions/71875508/please-help-assertionerror-expected-function-to-equal?noredirect=1#comment127011214_71875508).

**Comment by brx-craig** [comment]
Still not working in ^4.3.6
`expect(Logger).to.be.an.instanceOf(Logger);`
gives
>      AssertionError: The instanceof assertion needs a constructor but Object was given.
