### ISSUE TITLE
Assertions for both null & undefined?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [chaijs/chai#959]
For when you need to ensure that something isn't null _or_ undefined, there doesn't seem to be a better option in the Assert line than:

```javascript
assert.isNotNull(value);
assert.isDefined(value);
```

Can there be an equivalent that does both?

```javascript
assert.isNotNullUrUndefined(value);
```

**Comment by lucasfcosta** [comment]
Hi @JoshuaKGoldberg, thanks for your issue!

There's already an equivalent for that in the assert interface, which is [`assert.exists`](https://github.com/chaijs/chai/blob/850bd7e016606ce52292c0477320279a8b9cf294/lib/chai/interface/assert.js#L470).

I'll close this for now. Let me know if this does not suit your needs so we can take this discussion further and reopen it if needed. 😄

**Comment by JoshuaKGoldberg** [comment]
Ah I looked all over and it was right there all along... Thanks!

**Comment by JoshuaKGoldberg** [comment]
That does suit my needs, thanks! It's missing from the docs at http://chaijs.com/api/assert/#method_assert, and therefore missing from the DefinitelyTyped typings.

I also don't see a guide on [CONTRIBUTING.md](https://github.com/chaijs/chai/blob/master/CONTRIBUTING.md) to updating the docs. Is there a route for that?

**Comment by lucasfcosta** [comment]
Hmmm, actually I think that the docs should've been generated from the code comments we've got. The whole syntax seems correct, but I guess this has not been added to our site because [the commit responsible for introducing that](https://github.com/chaijs/chai/pull/778) was made after the currently "master" version, which is `3.5.0`.
