### ISSUE TITLE
Assert that an object does not change

### ISSUE THREAD

**Issue by russellw** [chaijs/chai#961]
At the moment, chai provides a way to assert that one property of an object has not changed after a function is called. However, what you want in practice is a way to assert that the object has not changed at all. (Ideally with the option to do this shallow or deep.) Is there any chance this could be added?

**Comment by lucasfcosta** [comment]
Hi @russellw, thanks for your issue!

Even though this might be useful and a valid comparison, I think this should be considered a responsibility of the user, not Chai's. One could simply overcome this by using `lodash.cloneDeep`.

However an argument could be made that we've got a `change` function to watch for the change of a certain property in an object, so we could also make that accept a single argument, which is the object that should not change.

I'm not strongly inclined to one side or the other, but given the amount of times I've used the `change` assertion myself and the arguments above, I'd vote not to add this.

However, I'd like to hear other maintainers' opinion.

**Comment by shvaikalesh** [comment]
We can't do it for new properties and `delete` without `Proxy`. To use `Proxy`, Chai should return new object for user to manipulate. Currently, we don't have an API for that. Also, to observe deeply, we should also account for proxy invariants (kinda hard). Observing `Map` or `Set` or `Date` also requires additional efforts, like setting prototypes/patching native methods.

With all this and browser support, I would say it is plugin-land issue. Plugin can wrap https://github.com/nx-js/observer-util, for example.

**Comment by keithamus** [comment]
Hey @russellw thanks for the issue!

It looks like some good alternatives have been suggested. It seems like this would be very complex for chai to implement, and may be best as a plugin - as @shvaikalesh has mentioned.

I'll close this. I don't think chai will implement this any time soon, if at all.
