### ISSUE TITLE
inclusion/containment semantics

### ISSUE THREAD

**Issue by jfirebaugh** [chaijs/chai#97]
Chai's `include`/`contain` test equality via `Array#indexOf`, i.e. strictly.

I'm currently working on chai-jasmine (a compatibility library), and Jasmine's equivalent is `toContain`, which [winds up using natural/deep/eql equality](https://github.com/pivotal/jasmine/blob/master/src/core/Env.js#L265-273). It would be nice if this could be implemented entirely in terms of chai assertions and flags.

Options:

* Provide natural/deep/eql semantics for the `include`/`contain` assertion if the deep flag is set, e.g.:

        expect(['A', {some:'object'}, 'C']).to.deep.contain({some:'object'})

  This phrasing suggests to me that things like `expect({a: {b: {c: 'd'}}}).to.deep.contain({c: 'd'})` should also be supported. But then should arrays be recursively searched as well? (Jasmine's `toContain` does not support this.)
* Introduce another flag, e.g. `to.naturally.contain({some: 'object'})`. But what's a good word?
* Introduce another assertion. Again, what would it be called?
* Give up and don't try to write the chai-jasmine `toContain` assertion in terms of chai assertions.

Thoughts?

**Comment by keithamus** [comment]
Closing this for a more focussed discussion in #644
