### ISSUE TITLE
deepPropertyVal broken in 4.0.0

### ISSUE THREAD

**Issue by Janpot** [chaijs/chai#974]
This passes in 3.5.0 but throws in 4.0.0
```js
assert.deepPropertyVal({ x: [{ y: 'z'}] }, 'x[0].y', 'z');
```
https://runkit.com/58e241c73a5052001416471a/59283b327e818c0012e4b519

I don't have time right now to look into it

**Comment by keithamus** [comment]
Thanks @Janpot thanks for the issue. 

Take a look at the [`4.0.0` release notes](https://github.com/chaijs/chai/releases/tag/4.0.0) - we describe the problem. We've change `deep` - which used to mean "deeply equal, or nested equal"  - to now only mean deeply equal. You'll need to change your assertions to instead use `nested` where you want to assert on nested values, so your assertion becomes:

```js
assert.nestedPropertyVal({ x: [{ y: 'z'}] }, 'x[0].y', 'z');
```

Let me know how you get on with this. I'll close this for now but we can always re-open.

**Comment by Janpot** [comment]
@keithamus I just was basing myself on your docs
<img width="781" alt="screen shot 2017-05-26 at 16 38 11" src="https://cloud.githubusercontent.com/assets/2109932/26499142/c7be1468-4231-11e7-8da1-d5f6a0703973.png">

**Comment by keithamus** [comment]
@Janpot the docs should be updated shortly, right now they're currently for 3.5.0.

**Comment by Janpot** [comment]
Also, notice that `deepPropertyVal` didn't mean "deeply equal, or nested equal". It only meant "nested equal", otherwise the following would work under 3.5.0:

```js
assert.deepPropertyVal({ x: [{ y: { z: 1 }}] }, 'x[0].y', { z:1 });
```

**Comment by keithamus** [comment]
Yes exactly @Janpot. The new assertions should be:

```js
assert.propertyVal
assert.deepPropertyVal
assert.nestedPropertyVal
assert.nestedDeepPropertyVal
```

**Comment by Janpot** [comment]
@keithamus 👍 thanks

**Comment by keithamus** [comment]
Hey @Janpot, looks like the docs have just updated! You can check out the new assertions here: http://chaijs.com/api/assert/#method_nestedpropertyval

**Comment by Janpot** [comment]
Looking great!
