### ISSUE TITLE
Update supported node version badge in README

### ISSUE THREAD

**Issue by meeber** [chaijs/chai#975]
Still says >=0.10 instead of >=4

**Comment by keithamus** [comment]
This should be a case of [amending the README.md](https://github.com/chaijs/chai/blob/master/README.md) from:

```html
    <img
      alt="node:?"
      src="https://img.shields.io/badge/node-%3E=0.10-blue.svg?style=flat-square"
    />
```

to 

```html
    <img
      alt="node:?"
      src="https://img.shields.io/badge/node-%3E=>4.0-blue.svg?style=flat-square"
    />
```

Anyone who would like to take this on, please announce it at file a pull request and we'll happily merge!
