### ISSUE TITLE
Confusing error message for Set comparison

### ISSUE THREAD

**Issue by willprice** [chaijs/chai#976]
```js
require('chai').expect(new Set([1, 2])).to.eql(new Set([2, 3]))
```
Fails (correctly) but with the confusing error message:
```
AssertionError: expected {} to deeply equal {}
```
I'd expect the following error message instead:
```
AssertionError: expected Set {1, 2} to deeply equal Set {2, 3}
```
I have tested this on chai 4.0.0 and master (both exhibit the same problem)

**Comment by keithamus** [comment]
Hey @willprice thanks for the issue.

Yes we had hoped to get better inspection capabilities in for 4.0, sadly it didn't make it in time and we've sat on 4.0 for too long. This _is_ in our roadmap for 5.0 though. Until we release 5.0, adding the following should work:

```js
Set.prototype.inspect = function () {
  return `Set { ${Array.from(this.values()).join(', ')} }`;
}
```
If you don't want to add this directly to the `Set.prototype` you could always add it to the sets you intend to use in tests.

As this is on our roadmap, we're (painfully 😆 😭) aware of this issue and so I'll close this particular issue as it is an explicit goal of 5.0.

**Comment by willprice** [comment]
Hi @keithamus,

Thanks for your prompt informative response. I did have a search before hand but couldn't find one. Good to know you're aware and working on it. I really appreciate you noting a workaround, that's very helpful.

Thanks for your hard work :)
