### ISSUE TITLE
Chai Equivalent of Enzyme's expect(foo).toHaveBeenCalled()

### ISSUE THREAD

**Issue by CakeEddy** [chaijs/chai#984]
I'm converting a project to use Chai rather than Enzyme's expect() functionality.
There is one test that I can't convert because I can't find the equivalent of the following in Chai.  I'm sure it exists, but I haven't found it yet.

```
const execCommand = jest.fn();
global.document.execCommand = execCommand;
const wrapper = mount(<SomeFooter {...minProps} />);
wrapper.find('#copy-link').simulate('click');
expect(execCommand).toHaveBeenCalled();
```
Can someone point me in the right direction?

Thanks,
Eddy Jones

**Comment by keithamus** [comment]
Hey @CakeEddy thanks for the issue.

You could take a look at [chai-spies](https://github.com/chaijs/chai-spies) which offers this kind of functionality. 

Alternatively have you seen [chai-enzyme](https://github.com/producthunt/chai-enzyme)? Its a great plugin for Chai that delightfully pairs Chai and Enzyme together.

Hopefully these two give you some good options to go with. I'll close for now, hoping that these answer your questions. If not feel free to comment and we can reopen
